support/apache/peertube.conf
Here is a configuration example for Apache 2.4 to use PeerTube.
=> Add apache configuration

client/src/app/videos/shared/video.model.ts, client/src/app/videos/shared/video.service.ts, client/src/app/videos/video-list/video-list.component.ts, client/src/app/videos/video-list/video-miniature.component.html, client/src/app/videos/video-list/video-miniature.component.scss, client/src/app/videos/video-list/video-miniature.component.ts, client/src/app/videos/video-watch/video-watch.component.html, client/src/app/videos/video-watch/video-watch.component.ts, server/controllers/api/videos.js, server/middlewares/validators/videos.js, server/models/user.js, server/models/video-blacklist.js, server/models/video.js
Should close issue #19.
At first I simply thought of granting the possibility for an admin to delete (from the DB) any video on the pod.
I had some problems when updating a deleted video information (since it was deleted ...). So I thought of another implementation. An admin can delete any video on its pod and it can blacklist a remote video. Hence, the video won't show up in the video list but there is no problem when updating the video information because it is still in the DB. (plus we can add a feature in the admin part to manage blacklisted videos or even "unblacklist" a video to see it on the video list again).
I, thus, split this feature in two parts : 
I simply modified the `isRemovableBy` method on the client side and the `videoRemove` checks on the server side.
I've also moved …
=> Add ability for an administrator to remove any video

client/src/app/videos/shared/video.service.ts
Some link could appear with double // in url.
e.g : "POST /api/v1/videos//upload HTTP/1.1"
A simple PR for now, meanwhile trying to fix #96
=> Fix some inconsistency in link

client/src/app/signup/signup.component.html
A first very small PR to get into PeerTube developpment. Hope I'll have time to do more :).
=> Display error message in signup page

.github/CONTRIBUTING.md, ARCHITECTURE.md, FAQ.md, README.md
Hi! Just a simple merge request to start, by changing some wording in the documentation, as well as wrapping lines (happy to remove this second commit, if it's only a burden). Please have a look and let me know if there's anything I misunderstood or if there are any nits you'd like to add, @Chocobozzz ! Thanks!
=> Reword docs

client/src/app/shared/video/video.model.ts, client/src/app/shared/video/video.service.ts, client/src/app/videos/+video-watch/video-watch.component.html, client/src/app/videos/+video-watch/video-watch.component.ts, server/controllers/api/videos/rate.ts, server/helpers/custom-validators/videos.ts, shared/models/videos/video-rate.type.ts
My first real pull requests! @Chocobozzz can you please have a look? Thanks!
=> A few updates for the watch video view

support/docker/dev/Dockerfile, support/docker/dev/janitor.json
This `janitor.json` file should allow us to add PeerTube to https://janitor.technology.
=> Add Janitor configuration file for PeerTube.

support/doc/dependencies.md, support/doc/production.md
This angular webtorrent interface deserved better docs. :trollface:
=> Improve docs

client/src/index.html, server/tests/api/server/follows.ts, support/doc/development/server/code.md
=> Misc. typos

support/docker/production/config/custom-environment-variables.yaml, support/docker/production/config/production.yaml
This exposes missing settings inside the Docker image and through environment variables.
=> Expose SMTP and instance settings in the Docker environment variables

client/src/manifest.json
This will make the notification bar visible and might solve #282.
I also added the `"theme_color"` property, which changes the browser's address bar color.
=> Change manifest properties

support/doc/dependencies.md, support/doc/import-youtube.md, support/doc/production.md
Hello,
Here is the guide to use import-youtube
It should works out of the box, I have tested from scratch on a fresh server :-)
Thanks for this very useful tool!
=> add import-youtube guide inside documentation

server/tools/import-youtube.ts
Hello,
Here is a contribution that should fix https://github.com/Chocobozzz/PeerTube/issues/299
It retries login to the peertube server when getting one 401 error at first upload.
I have tested with a token lifetime of 100 secondes, ti works smoothly so it should works with extrem configurations :-)
Renew works for each videos
It could probably be increased if we need to manage more than one retry or add better error handling (disconnection, password changed, quota exceeded?)
I am open to discuss these points with pleasure ;-)
Regards,
=>  add try/catch to manage token expiration when importing lot of youtube videos

support/doc/production.md
=> Update Production Guide

FAQ.md
Ads, blockchain and creation incentives in general are recurring topics:
- https://framacolibri.org/t/blockchain-et-peertube/2587
- https://framacolibri.org/t/fini-framatube-peertube-posez-nous-vos-questions/1965/88
- https://framacolibri.org/t/fini-framatube-peertube-posez-nous-vos-questions/1965/100
- https://diaspodon.fr/@dada/99644524496798848
- (probably others I have forgotten)
Trying to make a coherent synthesis of the current state of our opinion is not an easy task, and I don't expect this PR to be perfect. In no way that means we have to stop talking about these subjets or close doors, but it certainly gives us material to start more interesting discussions in the future.
=> Explain our position towards steem, ads, and other incentives

support/docker/production/docker-compose.yml
Works the same, but lighter. I think it's a good idea to add them in the `docker-compose.yml` example.
=> Use alpine images with docker-compose

client/src/app/shared/forms/form-validators/user.ts
I believe this fixes #382.
To be fair, I didn't set up a development environment to actually test this as it would have taken much longer than writing the actual fix. Please review carefully.
=> Fix #382 generic error when password is too long

support/doc/docker.md
I deleted the branch on #376 by mistake so I re-open a PR.
I took into account @bnjbvr remarks too.
=> Add permissions instructions for the data volume

server/initializers/constants.ts
First PR on this project, I hope it will not be the last :smile: 
Fix #394
=> Limit comment length to 1 character

server/tools/import-videos.ts, support/doc/dependencies.md, support/doc/production.md
This should fix #391 and display the encoutered error on the CLI.
=> Replacing the err being thrown by a gracefull exit.process(1) #391

server/tools/upload.ts
A tiny change I needed and could benefit others
=> Add privacy setting to upload.js cli

server/tools/import-videos.ts
fix:if download failed, it will block, try to skip err and continue to download
https://github.com/Chocobozzz/PeerTube/issues/456
=> fix issue-456:if download failed, it will block, try to skip err and continue to download

config/default.yaml, config/production.yaml.example, server/controllers/static.ts, server/initializers/checker.ts, server/initializers/constants.ts
=> robots.txt config and route

config/default.yaml, config/production.yaml.example, server/initializers/checker.ts, server/initializers/constants.ts, server/lib/job-queue/job-queue.ts, server/lib/redis.ts
=> DB selection in redis

client/src/app/core/server/server.service.ts, client/src/app/menu/menu.component.ts, config/default.yaml, config/production.yaml.example, package.json, server/controllers/api/config.ts, server/controllers/api/users.ts, server/helpers/utils.ts, server/initializers/checker.ts, server/initializers/constants.ts, server/middlewares/validators/users.ts, shared/models/server/server-config.model.ts, yarn.lock
=> IPvX registration filtering via CIDR (supports whitelists and blacklists)

support/docker/production/config/custom-environment-variables.yaml, support/docker/production/config/production.yaml
This is a very basic pull request to improve support for transcoding options in the Docker image.
=> Allow to setup transcoding in the docker image

FAQ.md
"Which" seems more appropriate than "what". (disclaimer: I'm not a native speaker though (french))
You can check here that the link works: https://github.com/Chocobozzz/PeerTube/blob/ff085ff62e09e7efc45f08b0c60d4012917da026/FAQ.md
=> FAQ: Fix out of date summary with broken link + rephrase

client/src/app/videos/+video-watch/comment/video-comments.component.html, client/src/app/videos/+video-watch/video-watch.component.html
fixes #595
partial #450 implementation
=> Improve discoverability by fixing helper and showcasing origin instance

client/src/app/login/login.component.html, client/src/app/login/login.component.scss
Links wasn't really obvious and needed some accessibility.
=> Enable default link behavior and accessibility for login page

client/src/assets/player/utils.ts, server/controllers/services.ts
following discourse on https://macgirvin.com/display/f0c095b75575ca33ba198110b947550a1c2dd3eb285968133140a905ba5769d1 pointed out by @anmol26s
=> (embed) sandbox the iframe

scripts/create-transcoding-job.ts, server/tests/cli/create-transcoding-job.ts, support/doc/tools.md
Add `-r [resolution]` to the `create-transcoding-job` script ;)
=> Add resolution to create-transcoding-job script

client/src/app/videos/+video-watch/video-watch.component.scss
changed a tag from flex to inline to avoid misclicks in firefox
=> Fixes account link width on video page is too much #574

support/doc/dependencies.md, support/doc/production.md
Signed-off-by: Pierre-Alain TORET <pierre-alain.toret@protonmail.com>
=> Update doc for CentOS 7 devtoolset-7

client/src/assets/player/peertube-videojs-plugin.ts
=> filter to Cap the maximum resolution to the screen resolution

FAQ.md, README.md
FAQ.md
- "the name" -> "a name"
- "re install" -> "reinstall"
- Changed the sentence structure to accomodate the flow of "objective -> method to achieve the objective -> reason why the objective is desired", rather than "how we are going to do it -> what we are trying to do -> why it is important"
README.md
- "It's the reason" -> "That is why" 
- "in it" -> "on it"
- "This program is free software" -> "This is a free software": reduce redundancy (program and software), and introduce a proper article
- "redistribute it and/or modify it" -> "redistribute and/or modify it"
- "version 3 of the License, or (at your option) any later version" -> "version 3 of the License or (at your option) later": reduce use of two "version" in one sentence (version 3 or later implies any version higher than 3 …
=> make edits in documents

FAQ.md, README.md
The question was legitimatly raised in the latest AMA on r/freesoftware and we
should explain why most of the project's activity is still happening on GitHub.
=> Add a precision in the FAQ regarding why we are mainly using GitHub for now

support/doc/dependencies.md
Related to: https://github.com/Chocobozzz/PeerTube/issues/778
=> support/doc/dependencies.md: Add Gentoo documentation

client/package.json, client/src/app/videos/+video-watch/modal/video-share.component.html, client/src/app/videos/+video-watch/modal/video-share.component.scss, client/src/app/videos/+video-watch/video-watch.module.ts, client/src/locale/source/angular_en_US.xml, client/yarn.lock
Adding QR-Code to the Share Menu to close #683
=> QR Code #683

server/controllers/activitypub/client.ts, server/controllers/feeds.ts, server/controllers/static.ts, server/helpers/utils.ts, server/initializers/constants.ts, server/middlewares/cache.ts, server/models/nodeinfo/index.d.ts
=> Adding initial support for nodeinfo

support/doc/translation.md
Instead of the French translation page
=> [FIX] doc: correct URL to PeerTube project

support/doc/api/html/index.html, support/doc/api/openapi.yaml
=> Fix routing for search in API docs

config/default.yaml, config/production.yaml.example, server/initializers/checker.ts, server/initializers/constants.ts, server/initializers/database.ts
=> adding ORM pool configuration

shared/models/i18n/i18n.ts
Pour que tout soit bien ordonné :)
=> [typo]Harmonisation

client/package.json, package.json
=> Change npm repo to git+https

client/src/app/shared/forms/form-validators/custom-config-validators.service.ts
Sorry, I will test next times, I didn't know why I didn't do it for auto thread.
And I don't know how to change using zanata. (And there is missing setance in zanata cause I finished the last 7% of french yesterday but there is staying some english)
=> Fix AutoThread

.github/CONTRIBUTING.md
=> Adding missing instructions to Contributing.md

client/package.json, client/src/app/app.component.html, client/src/app/app.component.ts, client/src/app/app.module.ts, client/yarn.lock
This might need a seperate module.
=> Add main keyboard shortcuts

client/src/app/login/login.component.scss, client/src/app/signup/signup.component.html, client/src/app/signup/signup.component.scss
There was a typo to A_r_mstrong so I took the opportunity to put a nameless
alternative.
I took the liberty to modify the table display so that it uses a bit better the
width of the screen.
=> Replacing placeholder and feature table display improvement

client/package.json, client/src/app/header/header.component.html, client/src/app/header/header.component.scss, client/src/app/videos/+video-watch/comment/video-comment-add.component.html, client/src/app/videos/+video-watch/comment/video-comment-add.component.scss, client/src/app/videos/+video-watch/video-watch.component.html, client/src/app/videos/+video-watch/video-watch.component.scss, client/src/app/videos/+video-watch/video-watch.module.ts, client/src/sass/application.scss, client/yarn.lock
- make the placeholder disappear on focus in the search bar
- make the texarea less obstrusive, and resize automagically
- refactor the watch view to use bootstrap 4's flexgrid
- move action buttons of the watch view to the right of the video info
- responsive tweaks and margin adjustments in the watch view
Moving to the flexgrid should ease further changes to the watch view.
=> Search placeholder, textarea resize, watch view visual tweaks

client/package.json, client/src/app/shared/video/recommendation-info.model.ts, client/src/app/videos/+video-edit/shared/video-edit.component.html, client/src/app/videos/+video-watch/video-watch.component.html, client/src/app/videos/recommendations/recent-videos-recommendation.service.spec.ts, client/src/app/videos/recommendations/recent-videos-recommendation.service.ts, client/src/app/videos/recommendations/recommendations.service.ts, client/src/app/videos/recommendations/recommended-videos.component.ts, client/src/app/videos/recommendations/recommended-videos.store.ts, client/src/setupJest.ts, client/src/tsconfig.spec.json, client/yarn.lock
I all ready do that but before moving recommendation to an other service (#1000).
I didn't added new test cause all the logic about sorting similar videos is made by the server during the search.
=> Add video recomandation by tags

support/doc/tools.md
=> further enhance tools install explanation

client/package.json, client/src/app/app.component.html, client/src/app/app.module.ts, client/src/app/menu/menu.component.html, client/src/app/menu/menu.component.scss, client/src/app/search/search.component.html, client/src/app/shared/video/video-miniature.component.html, client/src/app/shared/video/video-thumbnail.component.scss, client/src/app/videos/video-list/video-overview.component.scss, client/src/sass/include/_mixins.scss, client/yarn.lock, server/helpers/custom-validators/videos.ts
Only the homepage is concerned, but it should have decent keyboard
navigation support now.
related to #921
=> Use focus-visible polyfill to improve keyboard navigation

client/src/app/+accounts/account-about/account-about.component.ts, client/src/app/+admin/config/edit-custom-config/edit-custom-config.component.ts, client/src/app/+admin/config/shared/config.service.ts, client/src/app/+admin/follows/shared/redundancy-checkbox.component.ts, client/src/app/+admin/follows/shared/redundancy.service.ts, client/src/app/+admin/jobs/jobs-list/jobs-list.component.ts, client/src/app/+admin/users/user-list/user-list.component.ts, client/src/app/+my-account/my-account-settings/my-account-settings.component.ts, client/src/app/+my-account/my-account-video-imports/my-account-video-imports.component.ts, client/src/app/+my-account/shared/actor-avatar-info.component.ts, client/src/app/+video-channels/video-channel-about/video-channel-about.component.ts, client/src/app/core/confirm/confirm.component.ts, client/src/app/reset-password/reset-password.component.ts, client/src/app/search/search-filters.component.ts, client/src/app/shared/guards/can-deactivate-guard.service.ts, client/src/app/shared/overview/overview.service.ts, client/src/app/shared/rest/rest-extractor.service.ts, client/src/app/shared/user-subscription/subscribe-button.component.ts, client/src/app/shared/video-caption/video-caption.service.ts, client/src/app/signup/signup.component.ts, client/src/app/videos/+video-edit/video-update.component.ts, client/src/app/videos/+video-watch/modal/video-download.component.ts, client/src/app/videos/+video-watch/modal/video-share.component.ts, client/src/app/videos/+video-watch/modal/video-support.component.ts, client/src/app/videos/recommendations/recent-videos-recommendation.service.ts, client/src/assets/player/theater-button.ts
This should remove only unused imports and variables.
please review and correct me if I missed something
btw fyi: `app.module.ts` says:
>// FIXME: https://github.com/maxisam/ngx-clipboard/issues/133
and the issue seems to be fixed
=> remove unused imports

client/src/app/app.component.html, client/src/app/app.component.ts, server/controllers/api/config.ts, server/helpers/utils.ts, server/tools/cli.ts, shared/models/server/server-config.model.ts
resolves #835 and actually shows the tag name if different
=> show last commit hash alongside server version in footer

.github/ISSUE_TEMPLATE.md
The old order of items didn't really make sense to me.
=> Rewrite issue template

client/src/app/+admin/config/edit-custom-config/edit-custom-config.component.ts
These are admins, not children, seriously. I don't want this in my copy of PeerTube, and I figured other admins must be super annoyed by this too. I'm going to start patching this out of my copy, and possibly running a fork on my server.
=> Remove modal writing-on-blackboard simulator

client/src/app/shared/forms/form-validators/video-change-ownership-validators.service.ts, server/middlewares/validators/videos/videos.ts
=>  Add explicit error message that changing video ownership only works with local accounts

scripts/travis.sh, server/helpers/core-utils.ts, server/initializers/constants.ts, server/tests/helpers/core-utils.ts, server/tests/helpers/index.ts
This is something we could use to parse values from config. Check the tests to see how it works
=> add parseBytes utility function and tests

server/initializers/constants.ts, server/tests/api/videos/single-server.ts, server/tests/api/videos/video-imports.ts
=> Add Political category

README.md
* Two minor changes to `README.md`.
=> Typo and grammar

client/src/app/+admin/users/user-edit/user-edit.ts, client/src/app/+admin/users/user-list/user-list.component.ts, client/src/app/+my-account/my-account-ownership/my-account-ownership.component.ts, client/src/app/search/search.component.ts, client/src/app/shared/rest/rest-table.ts, client/tslint.json, tslint.json
both `tslint.json`s show warnings about a wrong configuration
https://palantir.github.io/tslint/rules/member-ordering/
https://palantir.github.io/tslint/rules/indent/
=> fix tslint config

support/docker/dev/Dockerfile
Use Docker best-practices for the development Dockerfile. Save 30Mo.
```bash
REPOSITORY          TAG     IMAGE ID             CREATED            SIZE
my_peertube_dev     new     05f18c1c2ca1       12 minutes ago      2.32GB
my_peertube_dev     old     4dc39bf82651       34 minutes ago      2.35GB
```
=> Improve dev Dockerfile

.github/CONTRIBUTING.md
Hello, I'm a CS french student working on PeerTube with two friends (@am97 and @clementbrizard ) as a scholar project.
We've been trying to run PeerTube on a VPS for a while and finally managed to do it. We now have a working developping environnement, with the live-reload feature.
Here is an adding proposition for the documentation.
=> Add doc for config VPS

README.md
I believe it feels more welcoming this way :)
I moved the Contributing section before the Dependencies section because, being less specific, it concerns and is useful to more people.
=> Improve Contributing section in README

server/helpers/ffmpeg-utils.ts
c.f. https://github.com/Chocobozzz/PeerTube/pull/1198#issuecomment-437827442 which is a potential improvement for compatibility.
=> (ffmpeg) force pixel format yuv420p

README.md
Provide small explanation of what is PeerTube and point to resources to learn more (combined with 'Want to see in action?' links)
I had a hard time coming up with a short and still decent explanation of what PeerTube is and how it works, feel free to improve it as you see fit 😉😊
=> Add Introduction to README (short explanation of what is PeerTube)

server/controllers/static.ts, server/tests/misc-endpoints.ts
spying on @tcitworld's stars, I found yet another well-known url to implement :sweat_smile:
=> add change-password well-known url

shared/utils/server/jobs.ts
=> increase waitJobs pendingJobs timeout to 2000

client/src/app/core/server/server.service.ts, client/src/app/shared/video/abstract-video-list.html, client/src/app/shared/video/abstract-video-list.scss, client/src/app/shared/video/abstract-video-list.ts, client/src/app/videos/video-list/video-trending.component.ts, server/controllers/api/config.ts, shared/models/server/server-config.model.ts
This PR is related to the following issue #1341 
I've just give a try to a simple help icon with a tooltip in order to explain how trending works. It looks like this : 
In my view, this solution is not really satisfying. I was thinking about something subtler, as I'm going to explain in the issue comments.
=> WIP : Indicate to users how "trending" works

client/src/app/+my-account/my-account-ownership/my-account-ownership.component.html, client/src/app/shared/icons/global-icon.component.ts
=> fix undefined change ownership icons

client/src/index.html, client/src/standalone/videos/embed.html
=> Add peertube meta tag

README.md
Was reading through the README when I noticed the year on it was still 2018. What else could I do but open a PR? ;)
=> Update year to 2019

shared/utils/videos/videos.ts
duplicate was appending as array to form-data (kept lines 376-378)
resolves #1630
=> remove duplicate uploadVideo.originallyPublishedAt

support/doc/dependencies.md
I think you might want to say that ;)
=> Typo for yarn version

support/doc/api/openapi.yaml
=> Add the video tags restrictions to the API docs

config/default.yaml, config/production.yaml.example, server/initializers/checker-before-init.ts, server/initializers/config.ts, server/initializers/constants.ts, support/docker/production/config/production.yaml
My scenario is that I'm running a migration from a previous server to PeerTube, and I'm creating users and uploading video for those users, so I need to increase a lot this limit while doing the migration.
Thanks for reviewing :)
=> Allow to control RATES_LIMIT from configuration

server/helpers/ffmpeg-utils.ts, server/lib/video-transcoding.ts, server/tests/api/videos/video-transcoder.ts
Haven't tested it yet, but this is the idea.
=> Dont transcode videos when it is not required

server/lib/video-transcoding.ts
This PR allows trancoding to succeed when `storage.videos` is a [s3fs-fuse](https://github.com/s3fs-fuse/s3fs-fuse) mounted directory. It changes the transcode procedure(s) to: 
1. Transcode video to `storage.tmp_dir` (local disk)
1. Read/compute metadata like fps
1. Move video to `storage.videos` (local disk or s3fs) as expected
By transcoding to local disk and reading metadata from there, object storage related transcoding errors like 'moov atom not found' and 'ffprobe exited with code 1' can be avoided. These issues seem to exist because object storage is 'eventually consistent'- metadata cannot be read immediately after creating a video. This commit assumes that `storage.tmp_dir` will remain a local disk directory.
Here's how I mounted my `storage.videos` directory:
$ s3fs …
=> Transcode in STORAGE.TMP_DIR for s3fs compatibility (#147)

config/default.yaml, server/initializers/config.ts, server/lib/emailer.ts
Relates to #912 
Thanks for reviewing :)
=> Allow to control emails prefix and signature with config

server/controllers/api/config.ts
This should fix https://github.com/Chocobozzz/PeerTube/issues/1850
=> Update config.ts - issue 1850

.github/CONTRIBUTING.md
=> tell the user to fork the repo

.github/CONTRIBUTING.md
Fixing a small typo in the contributing documentation.
The project seems really promising, love it :)
=> Fix CONTRIBUTING documentation client side typo

.github/CONTRIBUTING.md
Using multiple remote simplify a lot updating and pulling.
=> Update contributing to use multiple remote.

client/src/app/+admin/follows/followers-list/followers-list.component.html
This pull concerns #1914 and add a direct link to follower profile
=> Link to follower profile from administration

support/doc/dependencies.md
Update version of postgresql in rc-update and rc-service commands.
=> Update postgresql version for Gentoo

scripts/upgrade.sh
When the database is not on the same host pg_dump can't be not present
=> Check pg_dump before backup

support/docker/production/Dockerfile.stretch
Requested here: https://github.com/Chocobozzz/PeerTube/pull/1907
=> replace npm and apt-get by yarn and apt in dockerfile.stretch

support/doc/tools.md
=> Document how to synchronize YT channel to PeerTube

support/doc/dependencies.md
Add initialization for postgresql database (else there is an error when starting postresql service).
Enable Redis and PostreSQL services.
Replace "service" by "systemctl" (systemd).
Tested in local on a fresh CentOS 7 install.
=> Update CentOS 7 dependencies install

support/doc/api/openapi.yaml
Tested the API call with cURL in verbose mode.
=> Add originallyPublishedAt to PUT videos + change HTTP response to 204

support/doc/api/openapi.yaml
All changes to API documentation are tested with and compared to version 1.4.0-RC1
Updated:
- /api/v1/accounts
- /api/v1/config
Added:
- ServerConfigAbout schema
- ServerConfigCustom schema
=> Update API documentation for accounts and config

server/lib/peertube-socket.ts
don't write json multiple times.
=> fixes 2065: optimisation

support/doc/api/openapi.yaml
=> Remove feeds from API documentation

server/controllers/api/videos/index.ts
See comments on: https://github.com/Chocobozzz/PeerTube/commit/3155c8606cff211f495bf71c75c56cae85a5430f#r34881759
=> Update default value for commentsEnabled

client/src/app/+my-account/my-account-settings/my-account-danger-zone/my-account-danger-zone.component.ts, client/src/app/login/login.component.html, client/src/app/shared/forms/form-validators/user-validators.service.ts, client/src/app/videos/+video-watch/comment/video-comment-add.component.html, client/src/app/videos/+video-watch/comment/video-comments.component.ts, client/src/locale/source/angular_en_US.xml, server/lib/job-queue/handlers/activitypub-follow.ts, server/middlewares/validators/users.ts, server/tests/api/check-params/users.ts, server/tools/README.md, support/doc/plugins/guide.md
Hi,
I noticed a few spelling errors in the `angular_en_US.xml`
=> fix a few typos

.gitignore, client/src/app/+my-account/my-account-settings/my-account-video-settings/my-account-video-settings.component.html, client/src/app/+my-account/my-account-settings/my-account-video-settings/my-account-video-settings.component.ts, client/src/app/shared/users/user.model.ts, client/src/app/videos/+video-watch/video-watch.component.html, client/src/app/videos/+video-watch/video-watch.component.ts, client/src/app/videos/recommendations/recommended-videos.component.ts, server/controllers/api/users/me.ts, server/helpers/custom-validators/users.ts, server/models/account/user.ts, server/tests/api/check-params/users.ts, server/tests/api/users/users.ts, shared/models/users/user-update-me.model.ts, shared/models/users/user.model.ts
This is a continuation of #1370 that was abandoned.
I just made it work again and addressed some comments on the PR.
The one thing I didn't do (maybe quite major), was mess with the recommendation algorithm. I feel that it's out of the scope of this PR and should be done in another one to separate concerns. Changing the recommendation algorithm would entail a bigger discussion imo, since there are many way of doing it.
I hope you agree
So, this PR simply adds a checkbox for the user to autoplay recommended videos once the current video has stopped playing.
A final TODO before it's ready:
=> Autoplay next recommended video

support/doc/docker.md
Just for those of us who don't want to dig a lot but want to dig a little.
=> Link back to the source for the curl'd files.

client/src/app/+about/about-peertube/about-peertube.component.html, client/src/app/+admin/config/edit-custom-config/edit-custom-config.component.html, client/src/app/+signup/+register/register.component.html, client/src/app/+signup/shared/signup-success.component.html, client/src/app/modal/welcome-modal.component.html
This is some things I came across while translating.
=> Some language fixes

support/doc/docker.md
It felt unclear so I clarified and suggested a method for obtaining the credentials easier.
=> Clarify and expand on admin credentials detail

client/src/app/menu/menu.component.html
=> Add missing button roles for the language chooser and keyboard shortcut menu items

server/tests/api/videos/audio-only.ts
Fix code style to make CI pass on others PR
=> Fix codestyle and CI to have green tests on others PR

support/doc/dependencies.md
The current dependencies document syntax is broken on https://docs.joinpeertube.org/#/dependencies.
This update makes the page source consistent across distributions in the hopes of avoiding rendering issues.
example of current issue
=> Update dependencies.md to be consistent

support/docker/gitpod/Dockerfile
GitPod works with this implementation.
Resolve #2292
=> Fix For GitPod

client/src/app/search/advanced-search.model.ts, client/src/app/search/search-filters.component.html, client/src/app/search/search-filters.component.scss, client/src/app/search/search-filters.component.ts, client/src/app/search/search.module.ts, client/src/app/videos/+video-edit/shared/video-edit.component.scss, client/src/sass/include/_miniature.scss
Only thing I left for later: the "Show videos with subtitles (in this language)" checkbox.
=> search filtering improvements per #1654

client/src/app/shared/angular/timestamp-route-transformer.directive.ts, client/src/app/shared/forms/markdown-textarea.component.ts, client/src/app/shared/renderer/markdown.service.ts, client/src/app/videos/+video-edit/shared/video-edit.component.html, client/src/app/videos/+video-watch/comment/video-comment.component.html, client/src/app/videos/+video-watch/comment/video-comment.component.ts, client/src/app/videos/+video-watch/comment/video-comments.component.html, client/src/app/videos/+video-watch/comment/video-comments.component.ts, client/src/app/videos/+video-watch/video-watch.component.html, client/src/app/videos/+video-watch/video-watch.component.scss, client/src/app/videos/+video-watch/video-watch.component.ts, client/src/app/videos/+video-watch/video-watch.module.ts
Fix #1312 (duplicates: #1728 and #2007)
The modification is also applied to comments and video editing.
=> Add hyperlink video timestamps in description

support/doc/production.md
**Short Description**: Replace `peertube.example.com` with user's Peertube domain.
In file `/etc/nginx/sites-available/peertube`.
=> Replace `peertube.example.com` with user's Peertube domain.

client/src/app/+about/about-instance/about-instance.component.html
=> small grammar fix

client/src/app/shared/angular/video-duration-formatter.pipe.ts, client/src/app/shared/shared.module.ts, client/src/app/videos/+video-watch/video-watch.component.html
=> Add duration to video attributes in watch view

client/src/app/shared/video/modals/video-download.component.html, client/src/app/shared/video/modals/video-download.component.scss, client/src/app/shared/video/modals/video-download.component.ts, client/src/app/shared/video/video-actions-dropdown.component.ts, client/src/app/videos/+video-watch/video-watch.component.html
=> Add option to download subtitles in download modal

server/controllers/activitypub/outbox.ts, server/helpers/activitypub.ts, server/middlewares/validators/activitypub/index.ts, server/middlewares/validators/activitypub/pagination.ts
=> Add outbox page size parameter

server/controllers/activitypub/client.ts, server/controllers/api/overviews.ts, server/controllers/api/server/stats.ts, server/controllers/bots.ts, server/controllers/feeds.ts, server/controllers/static.ts, server/middlewares/cache.ts, server/middlewares/validators/feeds.ts
=> Adapt feeds content-type to accept header

client/src/app/+admin/users/user-edit/user-edit.component.html, client/src/app/+my-account/my-account-settings/my-account-change-email/my-account-change-email.component.html, client/src/app/+my-account/my-account-settings/my-account-change-password/my-account-change-password.component.html, client/src/app/+signup/+register/register-step-user.component.html, client/src/app/+video-channels/video-channel-videos/video-channel-videos.component.ts, client/src/app/+video-channels/video-channels.component.html, client/src/app/header/header.component.html, client/src/app/header/header.component.ts, client/src/app/login/login.component.html, client/src/app/reset-password/reset-password.component.html, client/src/app/shared/images/global-icon.component.ts, client/src/app/shared/video/video-thumbnail.component.html, client/src/sass/primeng-custom.scss, server/lib/client-html.ts
I left out the color changes for links, as well as anything related to contrast on the dark theme.
*note*: I took the opportunity to include plural correction for channel pages.
=> Accessibility fixes for #2149

client/src/app/+accounts/accounts.component.html, client/src/app/+admin/config/edit-custom-config/edit-custom-config.component.html, client/src/app/+admin/users/user-list/user-list.component.html, client/src/app/+admin/users/user-list/user-list.component.ts, client/src/app/+my-account/my-account-history/my-account-history.component.html, client/src/app/app.component.ts, client/src/app/shared/buttons/action-dropdown.component.html, client/src/app/shared/buttons/action-dropdown.component.scss, client/src/app/shared/buttons/action-dropdown.component.ts, client/src/app/shared/moderation/user-moderation-dropdown.component.ts, client/src/app/shared/user-subscription/remote-subscribe.component.html, client/src/app/shared/user-subscription/subscribe-button.component.html, client/src/app/shared/user-subscription/subscribe-button.component.scss, client/src/app/shared/video/video-miniature.component.html, client/src/sass/primeng-custom.scss
*note*: descriptions will need to be rewritten. The way I wrote them is more as a placeholder to get feedback on the modification.
=> Add action dropdown descriptions

client/src/app/+admin/config/edit-custom-config/edit-custom-config.component.html, client/src/app/+admin/config/edit-custom-config/edit-custom-config.component.scss, client/src/app/shared/forms/form-validators/custom-config-validators.service.ts, client/src/sass/include/_mixins.scss
=> Fix signup limit validator, and add warning message.

client/src/app/search/search-filters.component.html
This is a more clear description of what the options will do, and will be a lot easier to translate with the limited space available.
=> Clearer description of adv. search options

client/src/sass/primeng-custom.scss
=> Restyle toast notifications to tone down colors

server/models/account/user.ts
Hello,
This will update new users theme to be instance-default
=> Update default user theme to instance-default

support/docker/production/Dockerfile.buster
**Issue** : https://github.com/Chocobozzz/PeerTube/issues/2491
=> Fix missing python dependency in Dockerfile.buster

client/src/app/+about/about.component.html, client/src/app/+admin/admin.component.html, client/src/app/+admin/config/edit-custom-config/edit-custom-config.component.html, client/src/app/+admin/config/edit-custom-config/edit-custom-config.component.scss, client/src/app/+admin/plugins/shared/toggle-plugin-type.scss, client/src/app/+my-account/my-account-settings/my-account-change-email/my-account-change-email.component.scss, client/src/app/+my-account/my-account-settings/my-account-change-password/my-account-change-password.component.scss, client/src/app/+my-account/my-account-settings/my-account-danger-zone/my-account-danger-zone.component.html, client/src/app/+my-account/my-account-settings/my-account-interface/my-account-interface-settings.component.scss, client/src/app/+my-account/my-account-settings/my-account-profile/my-account-profile.component.html, client/src/app/+my-account/my-account-settings/my-account-profile/my-account-profile.component.scss, client/src/app/+my-account/my-account-settings/my-account-settings.component.html, client/src/app/+my-account/my-account-settings/my-account-settings.component.scss, client/src/app/+my-account/my-account-settings/my-account-video-settings/my-account-video-settings.component.scss, client/src/app/+my-account/shared/actor-avatar-info.component.ts, client/src/app/shared/forms/markdown-textarea.component.scss, client/src/app/shared/menu/top-menu-dropdown.component.html, client/src/sass/application.scss, client/src/sass/bootstrap.scss, client/src/sass/include/_mixins.scss, config/default.yaml, server/tests/api/server/config.ts, server/tests/client.ts
The objective is to better use the page width, and more properly signal different sections. The whole is tailored to be responsive. The left column in particular leaves place for `form-group` descriptions instead of `help` buttons which clutter the current design and fail at providing a direct insight.
Colors and `font-size`s are rebalanced in the navs and tabs as well as labels' `font-weight`, to better reflect an element's hierarchy in the page instead of basic emphasis relative to its child/parent element.
=> Settings and administration panels design rebalancing: grid, colors, font-{size, weight}

support/doc/docker.md
```
> GET /Chocobozzz/PeerTube/master/support/docker/production/.env HTTP/1.1
> Host: raw.github.com
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Location: https://raw.githubusercontent.com/Chocobozzz/PeerTube/master/support/docker/production/.env
```
=> Change raw.github.com to raw.githubusercontent.com

support/doc/api/embeds.md
player.stop() -> player.pause()
=> Fix embed api docs

support/doc/translation.md
=> Fix grammar in translation documentation

config/default.yaml, config/production.yaml.example, server/initializers/config.ts, server/lib/emailer.ts
This PR adds support for sendmail along smtp for e-mail configuration.
=> Add sendmail

client/src/app/core/plugins/plugin.service.ts, client/src/types/register-client-option.model.ts, support/doc/plugins/guide.md
This is two helpers needed for the plugin `upload-limits`.
- ~getBaseClientScriptsRoute~
- notifier (ToastModule); asked in this issue : https://github.com/Chocobozzz/PeerTube/issues/2602
=> Add notifier to plugin helpers

client/src/app/+my-account/my-account.component.scss, client/src/app/shared/buttons/action-dropdown.component.html, client/src/sass/application.scss, client/src/sass/bootstrap.scss, client/src/sass/include/_bootstrap-variables.scss, client/src/sass/primeng-custom.scss
Proposition for the issue : https://github.com/Chocobozzz/PeerTube/issues/2694
It also fixes the display of actions buttons in an `overflow` table view.
**Before**
**After**
=> Fix tables width, paginators, button on mobile / touchscreens

client/src/app/menu/menu.component.html, client/src/app/menu/menu.component.scss, client/src/app/menu/menu.component.ts
This PR fixes two issues about menu and the dropdown-user on touchscreens :
- first commit, make the left-menu scrollable (when needed) on landscape orientation https://github.com/Chocobozzz/PeerTube/issues/2699
- second commit, correct the dropdown-user placement on screen width < 500px https://github.com/Chocobozzz/PeerTube/issues/2705
=> Fix dropdown-user placement and menu-left scroll on touchscreens

client/src/app/+admin/moderation/video-abuse-list/video-abuse-list.component.html, client/src/app/shared/rest/rest.service.ts, client/src/app/shared/video-abuse/video-abuse.service.ts, server/controllers/api/videos/abuse.ts, server/helpers/custom-validators/video-abuses.ts, server/middlewares/validators/videos/video-abuses.ts, server/models/utils.ts, server/models/video/video-abuse.ts, server/tests/api/check-params/video-abuses.ts, server/tests/api/users/users.ts, server/tests/api/videos/video-abuse.ts, shared/extra-utils/videos/video-abuses.ts, shared/models/videos/abuse/video-abuse-video-is.type.ts
Same than https://github.com/Chocobozzz/PeerTube/pull/2720/files but build filters on client side
=> Use video abuse filters on client side

client/src/app/+admin/config/edit-custom-config/edit-custom-config.component.html, client/src/app/+admin/config/edit-custom-config/edit-custom-config.component.scss, client/src/app/+admin/config/edit-custom-config/edit-custom-config.component.ts, client/src/app/app.component.html, client/src/app/app.component.scss, client/src/app/app.component.ts, client/src/app/core/server/server.service.ts, config/default.yaml, config/production.yaml.example, server/controllers/api/config.ts, server/initializers/checker-after-init.ts, server/initializers/config.ts, server/middlewares/validators/config.ts, server/tests/api/check-params/config.ts, server/tests/api/server/config.ts, shared/extra-utils/server/config.ts, shared/models/server/broadcast-message-level.type.ts, shared/models/server/custom-config.model.ts, shared/models/server/index.ts, shared/models/server/server-config.model.ts
* Add ability to enabled/disable message
* Supports markdown
* Optional dismissable message
* 3 message levels: `info`, `warning`, `error` (using bootstrap theme)
=> Support broadcast messages

client/src/app/menu/language-chooser.component.html, client/src/app/menu/language-chooser.component.ts
Hello !
First contribution 😄 
This PR will add a lang attribute with the language iso code in the languages list menu.
It's related to this issue https://github.com/Chocobozzz/PeerTube/issues/2786 .
=> Add lang attribute in languages list menu

client/src/app/shared/shared-video-miniature/videos-selection.component.scss
Fixes https://github.com/Chocobozzz/PeerTube/issues/2982
=> Correct action button selection mode styles

client/src/app/shared/shared-main/misc/top-menu-dropdown.component.scss, client/src/sass/application.scss
=> correct regressions on sub-menu for account and admin

client/src/sass/bootstrap.scss
fixes https://github.com/Chocobozzz/PeerTube/issues/3043
=> Avoid lost scroll position when modal open

client/src/app/+videos/+video-watch/modal/video-support.component.ts, client/src/app/+videos/+video-watch/video-watch.component.ts
Fix issue [2995](https://github.com/Chocobozzz/PeerTube/issues/2995)
=> Resume video playback on close of support modal

server/helpers/custom-validators/videos.ts, server/helpers/express-utils.ts, server/helpers/video.ts, server/initializers/constants.ts, server/lib/activitypub/videos.ts, server/tests/api/server/config.ts
=> Refactor video extensions logic in server

support/doc/tools.md
Added documentation based off of support in matrix chat room
=> Add type information for create-transcoding-job's -r

support/doc/production.md
Is this also where you declare to follow other instances to support their bandwith/outreach? May be worthwhile to mention.
=> production.md - typo

FAQ.md
Extend server dimensioning hints a bit to also take network and disk i/o into account. Inspired by rigelkent in #3227 . Hope this helps.
Thank you for your work on PeerTube!
Mark
=> Update FAQ.md wrt performance estimates and strategies

client/src/app/+videos/+video-watch/comment/video-comment-add.component.ts, client/src/app/+videos/+video-watch/comment/video-comments.component.ts
Fix https://github.com/Chocobozzz/PeerTube/issues/3260
=> Correct break line display for re-draft comments

server/models/video/video.ts
video file picking was duplicated, I removed the duplicate code!
=> remove duplicate file checks in video model

client/src/app/+videos/+video-edit/shared/video-edit.component.html
CC license chooser:
https://creativecommons.org/choose/
https://chooser-beta.creativecommons.org/ (new version)
Inform user to pick the right license on upload.
=> add help popup for choosing license

client/src/app/shared/shared-forms/markdown-textarea.component.html, client/src/app/shared/shared-forms/markdown-textarea.component.scss, client/src/app/shared/shared-forms/markdown-textarea.component.ts
Add a tooltip and remove the grey background.
=> Small improvement of textarea maximize button

client/src/app/+login/login.component.html, client/src/app/+login/login.component.scss
=> fix forgotten/reset password UI

support/doc/dependencies.md
=> update the list to include Centos 8

support/doc/production.md, support/doc/tools.md
Update documentation to tell the reader that it's possible to change hostname.
=> add info about hostname change

server.ts, server/lib/emailer.ts
just log a warning if the SMTP server is down on startup time
fixes #3457
=> do not crash if SMTP server is down

.github/workflows/test.yml, scripts/ci.sh, scripts/parse-log.ts, server/controllers/api/search.ts, server/tests/api/check-params/live.ts, server/tests/api/check-params/video-captions.ts, server/tests/api/live/live-permanent.ts, server/tests/api/live/live-save-replay.ts, server/tests/api/live/live.ts, server/tests/api/notifications/moderation-notifications.ts, server/tests/api/notifications/user-notifications.ts, server/tests/api/search/search-index.ts, server/tests/api/server/follows.ts, server/tests/api/users/users-verification.ts, server/tests/api/videos/video-captions.ts, server/tests/api/videos/video-playlists.ts, server/tests/api/videos/videos-views-cleaner.ts, server/tests/plugins/plugin-helpers.ts, shared/core-utils/miscs/miscs.ts, shared/extra-utils/miscs/miscs.ts, shared/extra-utils/search/videos.ts, shared/extra-utils/server/servers.ts, shared/extra-utils/videos/live.ts
=> Save logs on ci failure

client/src/index.html
iOS wants it's own markup to display custom icons on the home screen.
Closes #2939
No, I couldn't find any way to test it other than create an own release and deploy it to some server. I hope this is okay anyway since the risks are low.
=> client: add iOS icon

client/src/app/modal/quick-settings-modal.component.html
Marked a string as i18n-able, spotted in production.
=> Mark 'These settings apply only to' string as i18n-able

client/src/app/shared/shared-main/angular/number-formatter.pipe.ts
Shows the decimal above 1000 views (which is then formated as 1K and otherwise was truncated). 
closes #3549
=> show first decimal for views above a thousand

client/src/app/+about/about-peertube/about-peertube.component.html
=> Add missing `i18n`

client/src/app/+about/about-follows/about-follows.component.html
=> Use correct English (About page)

package.json, server/helpers/logger.ts, server/initializers/database.ts, yarn.lock
Debugging SQL queries is never easy, so easing their read would be welcome 🙂
=> prettify SQL queries during debug

support/doc/production.md
Replace "start" by "restart".
"Start" is not enough and new certificate is not working.
- [x ] 🙅 no, because they aren't needed
=> Update production guide for certbot instructions

support/doc/dependencies.md
First time making a pull request. Please let me know if I am doing this wrong
Added instructions to help users who are setting up Peertube on an OpenBSD system
=> Add OpenBSD instructions to dependencies.md

scripts/ci.sh, server/tests/api/live/live-save-replay.ts, server/tests/api/notifications/user-notifications.ts, server/tests/api/server/stats.ts, shared/extra-utils/videos/live.ts
Check what tests fail when we set `retries=1`
=> Fix stats tests

client/src/assets/player/webtorrent/webtorrent-plugin.ts, server/controllers/api/videos/index.ts, server/models/video/video-file.ts, server/models/video/video-format-utils.ts, shared/extra-utils/videos/videos.ts
I think that some uploads issues could come from the torrent creation, that could be long. Make this torrent creation async
=> Async torrent creation

support/doc/production.md
added argument `-q` to unzip to it is silent output such as previous curl and wget commands in this guide
=> unzip silently on production guide

support/doc/production.md
database user password input documentation
user experience, usualy way is to hit enter when no indication is given, so make it explicit.
- [X ] 🙅 no, because they aren't needed
=> postgres createuser password comment

client/src/app/shared/form-validators/user-validators.ts
=> Improve validator text, I guess

support/doc/dependencies.md
@rigelk hi provide some help to @Rozen10 with his contribution about macOSX dependancies related to #3877 and #3859.
=> Update dependencies.md for macOSX.

client/src/app/+admin/follows/followers-list/followers-list.component.html, client/src/app/+admin/follows/following-list/following-list.component.html, client/src/app/+admin/follows/video-redundancies-list/video-redundancies-list.component.html, client/src/app/+admin/moderation/video-comment-list/video-comment-list.component.html, client/src/app/+admin/system/debug/debug.component.html, client/src/app/shared/shared-moderation/account-blocklist.component.html, client/src/app/shared/shared-moderation/server-blocklist.component.html
=> Add  `i18n` prop where it is missing

client/src/app/+page-not-found/page-not-found.component.html, client/src/app/+page-not-found/page-not-found.component.ts
Move video/resource switch to template, allowing sentence-wide translations that respect context and capitalization when needed.
fixes #3700
=> fix localization on page not found

support/docker/production/Dockerfile.buster
Closes https://github.com/Chocobozzz/PeerTube/issues/4045.
=> Add curl as dependency to Dockerfile.buster to allow for healthchecks

.github/workflows/test.yml, client/src/app/+about/about-follows/about-follows.component.html, scripts/ci.sh, server/tests/plugins/filter-hooks.ts, shared/extra-utils/server/jobs.ts
=> Run misc tests in parallel

server/models/video/formatter/video-format-utils.ts
Changes the audio label in the Download modal.
Does this really need a test?
=> Change audio label to "Audio"

support/doc/dependencies.md
=> Dependencies RHEL8

CHANGELOG.md, shared/models/plugins/server/managers/plugin-video-licence-manager.model.ts
Some small documentation fixes for the upcoming 3.4.0 release
=> Fix some documentation mistakes for plugin changes

client/src/app/+about/about-instance/about-instance.component.html, client/src/app/+about/about.component.html, client/src/app/menu/menu.component.html, shared/models/plugins/client/plugin-selector-id.type.ts
Adds plugin selector to elements in about page and menu dropdown.
closes #4586
=> add plugin selector to about/menu elements

client/src/app/+admin/overview/videos/video-list.component.html, client/src/app/+admin/overview/videos/video-list.component.scss
=> Add refresh button to admin > video list

client/src/app/shared/shared-video-playlist/shared-video-playlist.module.ts, client/src/app/shared/shared-video-playlist/video-playlist-element-miniature.component.html
=> Show date and views count in video playlists

client/src/app/shared/shared-video-playlist/video-playlist-element-miniature.component.html, client/src/app/shared/shared-video-playlist/video-playlist-element-miniature.component.scss, client/src/app/shared/shared-video-playlist/video-playlist-element-miniature.component.ts
Show the private badge at videos in playlists.
closes #2601
=> Show private badge in playlists

server/controllers/api/video-playlist.ts, server/tests/fixtures/peertube-plugin-test/main.js, server/tests/plugins/filter-hooks.ts, shared/models/plugins/server/server-hook.model.ts
Add `filter:api.video-playlist.videos.list.*` hooks.
closes #4775
=> Add filter:api.video-playlist.videos.list.* hooks

client/src/app/+admin/overview/users/user-list/user-list.component.html, client/src/app/+admin/overview/users/user-list/user-list.component.scss, client/src/app/+admin/overview/users/user-list/user-list.component.ts, client/src/app/helpers/utils/url.ts, client/src/app/shared/shared-main/account/actor.model.ts, client/src/app/shared/shared-moderation/blocklist.service.ts, client/src/app/shared/shared-moderation/user-ban-modal.component.html, client/src/app/shared/shared-moderation/user-ban-modal.component.scss, client/src/app/shared/shared-moderation/user-ban-modal.component.ts, client/src/app/shared/shared-moderation/user-moderation-dropdown.component.ts
I added a checkbox in the ban modal that allows to mute the user when banning it.
Closes https://github.com/Chocobozzz/PeerTube/issues/1803 - the other features requested in this ticket should be put in a separate issue.
=> Add ability to mute user when banning them

client/src/app/+videos/+video-edit/video-add-components/video-upload.component.ts, client/src/app/+videos/+video-edit/video-add.module.ts, client/src/app/+videos/+video-edit/video-update.module.ts, client/src/app/app-routing.module.ts
* Fix current titles
* Show upload progress in title
=> Fix titles on upload page

package.json, server/helpers/requests.ts, server/lib/object-storage/shared/client.ts, server/tests/api/server/proxy.ts, server/tests/shared/checks.ts, yarn.lock
See https://github.com/Chocobozzz/PeerTube/pull/4935
=> Add use proxy for s3

client/src/app/+my-library/my-video-playlists/my-video-playlist-elements.component.ts, client/src/root-helpers/plugins-manager.ts, shared/models/plugins/client/client-hook.model.ts, shared/models/plugins/client/plugin-client-scope.type.ts
Adds hooks for my library/playlist elements page.
closes #4776
=> hooks filter:api.my-lib.playlist-elems.get.*

client/src/app/shared/shared-abuse-list/abuse-details.component.html, client/src/app/shared/shared-abuse-list/abuse-details.component.ts
AbuseDetails gets infinite updated since a new array is created each render.
closes #5108
=> fix(client/AbuseDetails): infinite update loop

.eslintrc.json, server/lib/activitypub/activity.ts, server/middlewares/validators/config.ts, server/tests/api/moderation/abuses.ts, server/tests/feeds/feeds.ts, server/tools/peertube-import-videos.ts
Implement: https://github.com/Chocobozzz/PeerTube/pull/5135#discussion_r938807296
The client-side use single quotes rules, I also put them in the backend.
- notice in #754
=> Use single quotes in server/ and update eslint rules

config/default.yaml, config/production.yaml.example, server/lib/object-storage/shared/object-storage-helpers.ts
- catch and log errors with status 200
-  enable retries on part  upload errors
-  optimize part size
#5227
=> fix: validate s3 response

client/src/assets/player/shared/stats/stats-card.ts
Translates more strings inside the player statistics.
=> Translate more strings in player stats

.github/CONTRIBUTING.md
Add a single line to the documentation about redis
=> Add info about running redis server

client/src/app/+admin/admin.module.ts, client/src/app/+admin/config/edit-custom-config/edit-basic-configuration.component.html, client/src/app/+admin/config/edit-custom-config/edit-basic-configuration.component.ts, client/src/app/+admin/config/edit-custom-config/edit-custom-config.component.scss, client/src/app/+admin/overview/users/user-edit/user-edit.component.html, client/src/app/+admin/overview/users/user-edit/user-edit.component.scss, client/src/app/+admin/overview/users/user-edit/user-edit.ts, client/src/app/+admin/shared/index.ts, client/src/app/+admin/shared/shared-admin.module.ts, client/src/app/+admin/shared/user-real-quota-info.component.html, client/src/app/+admin/shared/user-real-quota-info.component.scss, client/src/app/+admin/shared/user-real-quota-info.component.ts
On looking into the code, the user edit form already had the message implemented. I edited it a bit to work on the admin config form.
I am not familiar with Angular though, and this commit does introduce some code duplication. Maybe someone else could check it?
Fixes #5247
Before:
After:
=> Add transcoding quota message to admin config page

client/e2e/src/po/admin-registration.po.ts
The text to accept registration has changed, so tests failed. I fixed it by changing to the appropriate text.
=> Fix signup e2e test

support/doc/dependencies.md
Tweaks documentation to point to a guide of how to add sudo user in Debian.
=> Pointer to Debian guide on how to add a sudo user

client/src/app/shared/shared-share-modal/video-share.component.html, client/src/app/shared/shared-share-modal/video-share.component.ts, client/src/root-helpers/video.ts
Providing responsive embed.
Fixes https://github.com/Chocobozzz/PeerTube/issues/3175
=> Add an option to provide responsive embed

.github/CONTRIBUTING.md, CODE_OF_CONDUCT.md
- Remove duplicate discrimination topic in Code of Conduct
- Correct capitalization of some brands (PeerTube, GitHub)
- Replace `npm` with `yarn` in Contributing guide, for additional consistency
=> Misc wording fixes, while learning how to test/contribute

support/doc/plugins/guide.md
Adding the path on which routes created with registerClientRoute are available.
The documentation didn't specify on with path routes created by registerClientRoute are available.
=> Enhance registerClientRoute documentation:

server/server/initializers/constants.ts
Add brazilian option for video/captions languages
Fixes https://github.com/Chocobozzz/PeerTube/issues/5962
=> Add brazilian option for video/captions languages

client/src/app/+signup/shared/signup-success-after-email.component.html, client/src/app/+signup/shared/signup-success-before-email.component.html
Minor text changes to improve English grammar.
=> Improve grammar within sign-up flow

server/server.ts
Cleanup database connection upon server exit to avoid locking, idle connections in the database.
=> fix(server): cleanup db connections upon exit

server/core/middlewares/rate-limiter.ts
Log when rate limit is exceeded, to give sysadmins better understanding of when limits are exceeded.
=> feat(server): log rate limit exceeded

CHANGELOG.md, packages/tests/src/api/check-params/video-channel-syncs.ts, server/core/lib/uploadx.ts, server/core/lib/video-pre-import.ts
=> chore: fix some comments

server/core/helpers/geo-ip.ts
Throttle geo ip db download so that it's not ran more often than once each 10 minutes. This is to handle when the geo ip db can't be downloaded, for instance because of the remote server is unreachable.
Closes #6381
=> fix(server/geo-ip): throttle db download

support/doc/api/openapi.yaml
Improve and correct API documentation
=> Improve and correct openapi documentation

client/src/app/+videos/+video-edit/shared/thumbnail-manager/thumbnail-manager.component.html, client/src/app/+videos/+video-edit/shared/thumbnail-manager/thumbnail-manager.component.scss, client/src/app/+videos/+video-edit/shared/thumbnail-manager/thumbnail-manager.component.ts, client/src/app/+videos/+video-edit/shared/video-edit.component.html, client/src/app/+videos/+video-edit/shared/video-edit.component.ts, client/src/app/+videos/+video-edit/video-update.component.html, client/src/app/shared/shared-main/video/embed.component.ts, client/src/standalone/embed-player-api/player.ts, client/src/standalone/videos/embed-api.ts, client/src/standalone/videos/embed.ts, packages/core-utils/src/common/url.ts, support/doc/api/embeds.md
Version 3 of the select from the select thumbnail from video frame documented in #1322 . 
This version does all the work in the client without requiring an update to the server side code.
#1322 
Screenshots included in pull #6346.
=> Feat-1322 Select Thumbnail from Video Frame

client/src/app/core/rest/rest-extractor.service.ts, client/src/assets/player/peertube-player.ts
In able to make it easier to debug issues.
=> client: extend logging

support/doc/production.md
The documentation says "reload" instead of "start" or "restart".
=> Fix documentation:

support/doc/api/embeds.md
=> Fixed typo in embeds.md

packages/models/src/plugins/server/server-hook.model.ts, server/core/lib/auth/oauth.ts, server/core/middlewares/validators/users/user-email-verification.ts, server/core/middlewares/validators/users/users.ts, support/doc/api/openapi.yaml
Add support for plugins to filter user email addresses. Workaround while waiting for https://github.com/Chocobozzz/PeerTube/pull/6648
#6648
=> feat: plugin support to filter email addresses

client/src/app/+login/login.component.html, client/src/app/+login/login.component.ts
Hide the "Most email addresses do not include capital letters." since it's not relevant since #6648 
related to #6570
=> client: hide email uppercase warning

client/src/app/+videos-publish-manage/shared-manage/moderation/video-moderation.component.html, client/src/app/shared/shared-user-settings/user-video-settings.component.html
Update moderation wording
Chocobozzz/PeerTube#7101
=> Update moderation wording

client/src/app/core/routing/scroll.service.ts
Before this change, ScrollService attempted to scroll down immediately after navigating, before before the page had fully loaded.
I considered making the Table component (and other data-loading componets) responsible for telling the ScrollService that data has been loaded—or to use Angular's Route.resolve property, but realized that using ResizeObserver to get the page size is a lot more reliable (and a small code change overall, so less painful :grin:).
I'm pretty sure there is some way to use RxJS observables for the `unhandledScrollEvent` variable I added, but I couldn't figure out a good way to do so. (Perhaps `combineLatestAll` with something to mark an event as "handled", but that "something" has been a bit elusive.) Would appreciate any pointers in that regard.
Also, with the …
=> Fix scroll position not being preserved when pages load slowly
