Chocobozzz/PeerTube

client/src/app/+admin/friends/friend-list/friend-list.component.html, client/src/app/+admin/friends/friend-list/friend-list.component.ts, client/src/app/+admin/friends/shared/friend.service.ts, server/controllers/api/pods.ts, server/lib/friends.ts, server/middlewares/validators/pods.ts, server/tests/api/check-params/pods.js, server/tests/api/friends-advanced.js, server/tests/api/friends-basic.js, server/tests/utils/pods.js
Should close issue #20.
I've just used the `quitFriends` method and adapt it to remove one friend.
I can see one problem with this method, though : It's not really DRY. Maybe we should add one method in the `server/lib/friends.js` to remove just one friend and call it 
- in the removeFriend method
- while iterating over the friend list in quitFriends 
?
=> Remove one pod

client/config/webpack.prod.js
Linked to issue #88.
Javascript running OOM during webpack compilation seem to be an known issue :
https://github.com/webpack/webpack/issues/1914
The last comment of this issue (https://github.com/webpack/webpack/issues/1914#issuecomment-326937497) fixed it by disabling the ModuleConcatenationPlugin. I did the same on PeerTube and the client part compiles on my PC 🎉
=> Client: Fix Javascript OOM error during webpack compilation

client/src/assets/player/peertube-videojs-plugin.ts
it's the shortest method to do it (while creating another `if `or `else if` statement add more code.)
=> hide error message in https too

support/doc/client/code.md
Webpack link used to lead to webpack 1 documentation.
Fixed it to reach lastest documentation instead.
=> Fix webpack link in client documentation

README.md
Notes:
- In Ubuntu 16.04, `sudo apt-get install postgresql` installs PostgreSQL 9.5.x (your Debian dependencies have `9.4` but hopefully `9.5` also works)
- The new NodeJS LTS is `8.x`, so I used that in the Ubuntu instructions, but left the Debian instructions unchanged (`6.x`). Please let me know if I should update.
=> Add dependencies for Ubuntu 16.04.

support/docker/dev/Dockerfile
This should allow us to set up a Docker Hub automated build containing an up-to-date PeerTube development environment.
This image is based on [ubuntu-dev](https://github.com/JanitorTechnology/dockerfiles#ubuntu-dev), so it should be really convenient and efficient to use for developers, and it's also compatible with the https://janitor.technology service.
=> Add a PeerTube development environment Dockerfile compatible with Janitor.

client/src/app/account/account-settings/account-details/account-details.component.html, client/src/app/account/account-settings/account-details/account-details.component.ts, client/src/app/account/account-settings/account-settings.component.html, client/src/app/core/auth/auth-user.model.ts, client/src/app/core/auth/auth.service.ts, client/src/app/shared/users/user.model.ts, client/src/app/videos/+video-watch/video-watch.component.ts, server/controllers/api/users.ts, server/helpers/custom-validators/users.ts, server/initializers/constants.ts, server/initializers/migrations/0130-user-autoplay-video.ts, server/middlewares/validators/users.ts, server/models/account/user.ts, server/tests/api/check-params/users.ts, server/tests/api/users.ts, server/tests/utils/users.ts, shared/models/users/user-update-me.model.ts, shared/models/users/user.model.ts
!!! WARNING : I was not able to run the tests on my machine. It uses a different approach to handle databse connexion and didn't find where to configure it... please run the tests before and don't kill me if they don't pass... and also help me running my tests :)
- create a migration file to add a boolean column in user table
- add autoPlayVideo attribute everywhere it is needed (both on client and server side)
- add tests
- add a way to configure this attribute in account-settings
- use the attribute in video-watch component to actually autoplay or not the video
Note: it was quite a pain to include a simple attribute to the user. User's data structure is declared multiple times and checks are also done at different places. It feels like things could be made implicit and not always …
=> Enh #106 : Add an autoPlayVideo user attribute

support/nginx/peertube-https
just a small change, so it does not byte people when they actually stop showing a warning and instead just fails
=> change nginx config to fix deprecation of a old module

client/src/index.html
Following with #194, that's a (for now text-only) message to explain:
- the need for JS
- the alternatives existing (none for now)
- the extent to which our code can be trusted
Maybe we should stick with something simpler?
=> Show a message on client when JavaScript is disabled

scripts/watch/client.sh, support/docker/dev/Dockerfile, support/docker/dev/create_user.sql, support/docker/dev/janitor.json, support/docker/dev/supervisord.conf
Hey @jankeromnes, can you help me please? It's almost working, but I couldn't find out how to start the postgresql daemon from supervisord. Any idea here?
edit: starting from supervisord as I did doesn't work, for some reason (?).
=> Fix Janitor configuration;

scripts/watch/client.sh, support/docker/dev/Dockerfile
PeerTube pre-build was removed in #207 because `npm run dev` already builds it on-the-fly (see [this comment](https://github.com/Chocobozzz/PeerTube/pull/207/files#r161971735)).
However, I find that `npm run dev` takes too long to produce an initial build, causing [errors](https://irccloud.mozilla.com/pastebin/11Vv9PoA/ENOENT.txt) when you try to use PeerTube right after starting `npm run dev`.
I feel like including a pre-built PeerTube in dev images is valuable and convenient. @Chocobozzz please have a look when you have time.
=> Pre-build PeerTube again in dev Dockerfile.

support/doc/production.md
on ubuntu `sudo -u` doesn't set homedirectory of the targeted user althought debian does. it requires the option `-H`. I think with this option it works in both case.
=> update yarn installation command

client/src/app/videos/+video-watch/comment/video-comment-add.component.html
Very simple addition.
`meta.enter` should be command-enter on mac, but I don't one to check this.
Issue #217
=> Issue #217: Publish comment on ctrl-enter

support/doc/production.md, support/nginx/peertube
- added precisions and suggestions about how to generate Let's Encrypt certificates. Users have reported their installations didn't work when the problem came from missing certificates (false positives).
- security defaults of Nginx follow the basic robustness principle "be conservative in what you send, be liberal in what you accept", which isn't enough with modern security standards, so we should be picky with the cipher suites we use, among other things. Extra comments (especially for the TLS1.3 protocol support parameter) make the requirement of a recent Nginx installation obvious, and the downgrade alternative remains clear to the system administrator.
All in all, we should aknowledge users will most often copy and paste the configuration files. Making them secure by default may …
=> Precisions and security enhancements to the production guide

client/src/app/videos/+video-watch/comment/video-comment.component.html, client/src/app/videos/+video-watch/comment/video-comment.component.scss, client/src/app/videos/+video-watch/comment/video-comment.component.ts, client/src/app/videos/+video-watch/comment/video-comment.model.ts, client/src/app/videos/+video-watch/comment/video-comments.component.ts, client/src/app/videos/+video-watch/video-watch-routing.module.ts
Uses GET parameters to mark comments similar to youtube, allowing to send a comment link to someone else.
I agree with Aluriak that the « x min ago » text is not a logical place to provide the link, even though this is the case in youtube. (#168)
Right now I included a link next to the `Delete` and `Reply` links, but i'm open to changing that.
=>  Issue #168: youtube-like marking of comments

support/nginx/peertube
`X-Frame-Options DENY;` doesn't permit sharing using iframe
if present we get the following message in browser : 
`
Load denied by X-Frame-Options: https://peertube.valvin.fr/videos/embed/b2cc97ef-dc05-400b-94f8-43ea61237718 does not permit framing.`
=> Remove X-Frame options in nginx config

support/doc/dependencies.md
In order to build properly rdf-canonize node nativ module gcc > 5 is needed. Tested on Ubuntu 14.04 with gcc 4.8, it didn't work. I had to install a newer gcc version and it was OK.
=> dependencies.md : Update g++ needed version

support/doc/docker.md, support/docker/production/config/custom-environment-variables.yaml, support/docker/production/config/production.yaml, support/docker/production/docker-compose.yml
Updated the docker compose file so I can keep on using it on my server. In particular, it tweaks a few configuration options in the example yaml configuration file, requests to always restart the docker images if one of them is shut down, fixes many issues in the docker-compose file (incorrect env var names, quotes, etc).
I've also added some documentation to make it clearer how to use this image with `docker-compose`.
I've build it and tested it locally and it works great (including email support).
=> [docker] Update production guidelines and docker-compose file

support/nginx/peertube
Reverts Chocobozzz/PeerTube#364
It does not work because we loose the proxy of `location /`
=> Revert "Selective route X-Frame-Options to allow embeds, fixes #322 in a better way"

README.md
To avoid to download the html file and view it locally, make documentation readable when I click on the link.
=> Readme, link to api documentation: Link to a rendered html view instead of raw html

scripts/build/client.sh, scripts/build/server.sh, scripts/clean/client/dist.sh, scripts/clean/server/dist.sh, scripts/clean/server/test.sh, scripts/client-report.sh, scripts/danger/clean/dev.sh, scripts/danger/clean/modules.sh, scripts/danger/clean/prod.sh, scripts/dev/client.sh, scripts/dev/index.sh, scripts/dev/server.sh, scripts/generate-api-doc.sh, scripts/generate-code-contributors.sh, scripts/help.sh, scripts/play.sh, scripts/release.sh, scripts/test.sh, scripts/travis.sh, scripts/upgrade.sh, scripts/watch/client.sh, scripts/watch/server.sh
Hi,
I switched all the compatible scripts to `#!/bin/sh`, I added `set -eu` on all of them, which allowed me to remove a lot of `|| exit -1`.
Then I fixed some stuff spotted by ShellCheck. A few are remaining:
```sh
In ./scripts/release.sh line 7:
PGID=$(ps -o pgid= $$ | grep -o "[0-9]*")
^-- SC2009: Consider using pgrep instead of grepping ps output.
```
I think this one is a false positive in this case. Can't find a way to do the same using `pgrep` (but I didn't searched a lot). We can leave it like this, and maybe add a shellcheck directive to disable this warning on this line if you want.
```sh
In ./scripts/release.sh line 44:
[[ "$0" = "$BASH_SOURCE" ]] && exit 0
^-- SC2128: Expanding an array without an index only gives the first element.
```
I don't see where does `$BASH_SOURCE` …
=> Clean shell scripts

server/initializers/constants.ts
until we settle on a way to specify different sign languages while keeping the bigger category of sign languages, that is.
=> add sign language to the index of languages

client/src/app/about/about.component.html, client/src/app/about/about.component.ts, client/src/app/core/server/server.service.ts, server/controllers/api/config.ts, shared/models/server/server-config.model.ts
As outlined by @Aldarone, the quota is one of the deciding factors when choosing an instance, and we should make it easy to spot.
For now I placed it in the about page as suggested (admittedly the wording could be improved…):
It conveniently pulls data from the `API/server/stats` route, which now exposes the video quota defined in the config. This way, servers publicly disclose their baseline quota for potential newcomers to know.
=> show quota in stats, display quota on the about page, fixes #405

client/src/app/menu/menu.component.scss
- removed the `margin-left` on the `.panel-block` to put it on the children
instead
- squashed the `margin-bottom` of the links into their `height` (and rounded it
to 40px, feel free to correct me)
- centered vertically the content of the links
- added the `background-color` change on hover for the links
I put the same color as the `.logged-in-block`. Maybe it should be externalized
as a SCSS variable?
I also added a CSS transition. Is it alright?
=> Add a hover effect on left menu links (#418)

.editorconfig
It could help new contributors start with the proper conventions, right in their editors.
=> add .editorconfig to maintain consistent coding styles

client/src/app/menu/menu.component.html
I hope using ```user.account.id``` is right (if I understand correctly it should).
This adds a link to view "My profile" to the dropdown, the link is the same as the link of the user under video thumbnails. Fixes  #523
=> Add a link to 'My profile' in the dropdown

support/doc/dependencies.md
In order to avoid potential issue with new non-tested nodejs version that Arch Linux is shipping.
=> Switch Arch Linux dependency to NodeJS LTS

client/src/app/videos/+video-watch/comment/video-comments.component.html, client/src/app/videos/+video-watch/comment/video-comments.component.scss, client/src/app/videos/+video-watch/video-watch.component.html, client/src/app/videos/+video-watch/video-watch.component.scss
Account helper:
---
Comment helper:
=> Add helpers in the video watch view explaining how to comment/subscribe

scripts/upgrade.sh
Remove Quotation marks on database backup files.
Example in backup folder, showing files  : 
`sql-peertube_prod-"20180507-2328".bak`
=> Fix Quotation marks on database backup files

scripts/upgrade.sh
It is now possible to pass the path to upgrade on script, as Peertube could be installed in another path than /var/www/peertube.
I couldn't find a clean way to guess the path to use, so I've chosen instead to let administrator specify the path by hand.
=> Configure path used by script upgrade.sh

support/doc/dependencies.md
Run sysrc commands instead of directly editing /etc/rc.conf.
syntax errors in /etc/rc.conf can leave the system unbootable.
=> Use sysrc command on FreeBSD

README.md
Peertube app for YunoHost is ready. People who want to self host without going into deep details for the installation,backup and restore have the option to run Peertube over the YunoHost. Hope to see many more new instances.
=> Peertube for Yunohost.

support/doc/production.md
Like #267.
Without this, Yarn will try to use `/root/.config/yarn` with the peertube user, which obviously doesn't have access.
=> Update sudo command for yarn during upgrade

client/src/app/about/about.component.html
Since Tor Browser disables WebRTC, the fallback to HTTP streaming will respect
Tor's terms of service. Anyway any recommendation to use Tor should point to
the Tor Browser, as it provides sane and secure defaults to use Tor.
Fixes #676
=> Specify Tor Browser instead of just Tor in the recommendation

client/src/app/videos/+video-watch/video-watch.component.scss
Hi there,
First of all, thanks for this amazing project. I tried to take screenshots on each responsive view.
I love fluid content. :)
Have a nice day.
=> Fix #576 - show 'Others videos' on a <1300px viewport

client/src/app/app.component.ts, client/src/sass/application.scss
- Add a transition when opening/closing the left menu
- Suppress the scroll to top when opening/closing the left menu.
Note: regarding the scroll to top, I did see the commit about it https://github.com/Chocobozzz/PeerTube/commit/a01f107bc436250706d4bc765f45335ee15b8e80#diff-30532d215cbc6539c241db5bdfc9b60eR60 
It is not clear to me how it improved the mobile version, but it is clearly annoying for the desktop one.
Still, I assume it has been done for a good reason, so I would be happy to talk about it in order to find the best solution on this matter.
=> Improve left menu

client/src/app/videos/+video-watch/modal/video-download.component.html
".torrent" is a common name for users familiar with BitTorrent, and less
impressive than "metainfo" or no information as opposed to the magnet option,
less commonly known but rather just clicked on most sites.
=> rewording download option and reorder options

package.json, server.ts, server/controllers/client.ts, yarn.lock
note: this time it should work :sweat_smile:
=> Selective route permission to use embeds, fixes #322 in a better way

.travis.yml
We don't do any git operation except include last commit name, so we only need last commit, that will make travis-ci test faster.
=> Updated travis.yml git depth 1

support/systemd/peertube.service
On very very slow server, peertube can generate error if redis isn't started.
=> Added redis-server.service to After

server/middlewares/validators/follows.ts
Follows on http server is a server error in the configuration not an error of the client.
@Chocobozzz as you ask in #852 this is reopen.
=> [Server>Middlewares>Follows] Changing error code 400 to 500

support/doc/dependencies.md
postgresql-contrib is required when running v1.0.0-beta.10.pre.1 or later.
https://github.com/Chocobozzz/PeerTube/releases/tag/v1.0.0-beta.10.pre.1
I haven't checked with other OS, but please let me know if anyone knows.
I will add it in this pull request.
=> Add postgresql-contrib to dependencies guide

support/doc/production.md
Resolves #886 
The `pg_restore` command fix is required to properly restore after any migrations have been performed on upgrade.
The tweak of the `pg_dump` command is optional as the result is equivalent to the original command. The benefit is it avoids the need to enter both the sudo password and peertube database user password. Because the `upgrade.sh` script is meant to be run entirely as the `peertube` user it makes sense as-is.
=> fix pg_restore command for post-migrations

client/src/app/reset-password/reset-password.component.html
Fixed by changing the logic - if the form is not valid or the confirmed password does not match the button will be disabled. Considered a refactor with shared module between change and reset passwords but determined the effort did not match the value.
All testing done manually.
=> correct password reset disabled binding

support/nginx/peertube
Without gzip explicitly enabled, load times suffer from transferring
over a megabyte of plaintext javascript. With gzip enabled, the bundle
is down to about 300K, and loads much faster.
This change does not enable gzip on files that are already compressed,
so images, fonts, and videos will be sent without the CPU overhead.
closes #948
=> Add gzip support to the sample nginx configuration

.gitignore, .travis.yml, client/package.json, client/src/app/shared/video/video.service.ts, client/src/app/videos/+video-watch/video-watch.component.html, client/src/app/videos/+video-watch/video-watch.component.ts, client/src/app/videos/+video-watch/video-watch.module.ts, client/src/app/videos/recommendations/recent-videos-recommendation.service.spec.ts, client/src/app/videos/recommendations/recent-videos-recommendation.service.ts, client/src/app/videos/recommendations/recommendations.module.ts, client/src/app/videos/recommendations/recommendations.service.ts, client/src/app/videos/recommendations/recommended-videos.component.html, client/src/app/videos/recommendations/recommended-videos.component.ts, client/src/app/videos/recommendations/recommended-videos.store.spec.ts, client/src/app/videos/recommendations/recommended-videos.store.ts, scripts/travis.sh
This should be a pure refactor.  The existing behavior of the "Other Videos"
section should remain the way it was before. 
---
I'm currently working on some proof-of-concepts for recommendation
providers that could work with PeerTube to provide useful video
suggestions to the user.
More info [here](http://github.com/bradsk88/peertube-recommendations) and [here](https://framacolibri.org/t/suggestion-video/3415/13)
As a first step, I want to have great clarity about how PeerTube,
itself, will surface these videos to the user.
With this branch, I'm refactoring the "recommendations" section to 
make it easier to swap out different recommender implementations 
quickly.
(this video was recorded on my instance, running the code in this PR)
=> Refactor: Separated "Other Videos" section into a dedicated component/service

client/src/assets/player/peertube-player.ts
Those speeds are much more closer to the normal speed. They are useful for listening to human speeches.
=> Add more playback speed (0.75 and 1.25)

client/src/app/+video-channels/video-channels.component.html, client/src/app/+video-channels/video-channels.component.ts, client/src/app/app.component.scss, client/src/app/app.component.ts, client/src/app/menu/menu.component.scss, client/src/app/shared/instance/instance-features-table.component.html, client/src/app/shared/instance/instance-features-table.component.scss, client/src/app/shared/instance/instance-features-table.component.ts, client/src/app/shared/video/video-miniature.component.scss, client/src/app/videos/+video-watch/video-watch.component.html, client/src/app/videos/+video-watch/video-watch.component.scss, client/src/app/videos/+video-watch/video-watch.component.ts, client/src/sass/include/_mixins.scss, client/src/sass/include/_variables.scss
I reduced the rather big margins that followed the grid refactoring. And then I went a bit overboard.
Most notable:
- make the left menu scrollbar appear only on focus/active, with a fixed and defined width for the 'menu' element to make the whole stable. (much like YouTube does)
- fix the 'other videos' margin which got disable through the grid refactoring.
- finally add component hotkeys, and fix the shortcuts (I misunderstood the doc so far, which led to second letters to activate when pressed alone…)
- make the features table show the daily quota, and use enough width to properly display the helper
- ellipsize the titles over two lines instead of one. Since we have already a quite unoptimised font size/weight/typeface for titles (just look at the use of Roboto for YouTube's titles), …
=> Various style and margin fixes, per-component hotkeys, and more

client/src/app/+my-account/my-account-settings/my-account-change-password/my-account-change-password.component.html, client/src/app/+my-account/my-account-settings/my-account-change-password/my-account-change-password.component.ts
If you leave the form but the 2 password is different a big red box appears to warn you (no need to click on the button).
The submit button is desactivated if the 2 password isn't the same.
=> Making password change erroring more friendly

support/nginx/peertube
This goes against the recommendations (preloading should be opt-in). Putting it in the example makes it likely that people enable it without knowing what it means.
https://hstspreload.org/#opt-in
=> Don't include `preload` flag in sample HSTS header

.github/CONTRIBUTING.md
I tried to run a dev instance of PeerTube on a VPS with Fedora. I tried with 1GB of RAM, then 2GB. In both cases, running `npm run dev:server` failed when the RAM got full. 
[See the screencast](https://framadrop.org/r/WPQds1jgVe#BuAlnYIxOU63BesiMhNRtKifPe5KbMFUCjEBW4F8TwU=)
I tried then with a VPS with 4GB of RAM, and it worked.
=> Add warning about RAM to contributing guide

client/src/app/core/auth/auth.service.ts, client/src/app/core/routing/login-guard.service.ts, client/src/app/login/login.component.ts
this will redirect you back to the page you wanted to go before you were redirected to the login page.
I am not sure why I need `this.redirectUrl = null`.
If I remember correctly and looking at the [example](https://angular.io/guide/router#component-less-route-grouping-routes-without-a-component) this should not be needed. But maybe the `auth.service` is not destroyed at logout.
fixes #294
=> add redirect after login

server/helpers/custom-validators/activitypub/actor.ts
One should have an oportunity to include a dot into the username.
Currently, it breaks the flow if one has an SSO in front of PeerTube which creates users with "name.surname".
=> Add dot into allowed actor username

scripts/build/client.sh, shared/models/i18n/i18n.ts
Also slightly changed names for both zh languages:
`中文 (繁體, 台灣)` _Chinese (Traditional, Taiwan)_ → `繁體中文（台灣）` _Traditional Chinese (Taiwan)_
Let me know if anything goes wrong :P
=> Enable Simplified Chinese support

client/src/app/+video-channels/video-channels.component.html, client/src/app/search/search.component.html, client/src/app/shared/shared.module.ts, client/src/app/shared/user-subscription/index.ts, client/src/app/shared/user-subscription/remote-subscribe.component.html, client/src/app/shared/user-subscription/remote-subscribe.component.scss, client/src/app/shared/user-subscription/remote-subscribe.component.ts, client/src/app/shared/user-subscription/subscribe-button.component.html, client/src/app/shared/user-subscription/subscribe-button.component.scss, client/src/app/shared/user-subscription/subscribe-button.component.ts, client/src/app/videos/+video-watch/comment/video-comment-add.component.html, client/src/app/videos/+video-watch/comment/video-comment-add.component.scss, client/src/app/videos/+video-watch/comment/video-comment-add.component.ts, client/src/app/videos/+video-watch/comment/video-comments.component.html, client/src/app/videos/+video-watch/video-watch.component.html, client/src/sass/application.scss, client/src/sass/include/_bootstrap.scss
@Chocobozzz I didn't know how to properly inject the RSS URI in the button, so I left that aside.
The advantage of this button is that it even shows for visitors. It gives them a tour of the available possibilities to subscribe, while also being interactive via a form for remote follow.
The appearance differs slightly if you are logged-in: the button is then a two-action button, whose left part subscribes directly with your local account (as the original button). The right part open the dropdown-menu.
The button is now put on the right side, much like with YT.
=> refactor subscribe button and comment-add for visitor-interact UX

scripts/upgrade.sh
The upgrade.sh script doesn't let you install pre-release versions of Peertube. This change adds a prompt if a pre-release is available. Output looks like this:
```
$ ./upgrade.sh
Which version do you want to install?
[1] v1.0.0-beta.13 (stable)
[2] v1.0.0-beta.15 (pre-release)
```
=> Add prompt to upgrade.sh to install pre-release version

server/tools/peertube-upload.ts
Closes #1134.
This PR creates a new command line flag for the `peertube-upload.js` script, `-C, --channel-id` that allows one to specify a channel to upload to rather than the default.
This was very helpful for my own scripts of uploading hundreds of videos to a custom channel, and I hope others will benefit from it too.
=> Allow specification of Channel ID in peertube-upload.js

scripts/upgrade.sh
I think "diff -u" is more readable than "diff" to see changes in config files.
=> using "diff -u", for a clearer display

scripts/upgrade.sh
Avoid hardcoded values in upgrade script.
Avoid asking for DB password.
Uses python (usually installed on your system, even with minimal installations) and some of its standard lib modules.
=> Use DB informations from config/production.yaml in upgrade script

server/tools/repl.ts, support/doc/tools.md
If you want to interact with the application libraries and objects, there is a REPL for that.
usage: `node ./dist/server/tools/repl.js`
"The default evaluator will, by default, assign the result of the most recently evaluated expression to the special variable `_` (underscore). Explicitly setting `_` to a value will disable this behavior."
- type `.help` to list commands available in the repl, notice it starts with a dot
- type `.exit` to exit, note that you still have to press CTRL-C to actually exit, or press CTRL-C (3 times) without typing `.exit` to exit
- type `context` to list all available objects and libraries in the context, note: `Promise` is also available but it's not listed in the context, in case you need promises for something
- type `env` to see the loaded environment …
=> add server/tools/repl.ts

client/tsconfig.json
as described in https://github.com/Chocobozzz/PeerTube/issues/1277#issuecomment-429799326, using `'use strict';` would be a good decision.
No problems seem to appear.
=> add useStrict flag

shared/models/videos/video-resolution.enum.ts
The current implementation after #1135 uses the same bitrate for any fps number, except for exactly 60 fps, where it uses a higher bitrate. As an extreme case, a video with 10 fps and a video with 59 fps will have the same bitrate (at the same resolution).
This is a suggestion to scale the bitrate linearly. Example bitrates (also as comment in the source code):
```
1080p10: 2420 kbps, 1080p30: 3300 kbps, 1080p60: 4620 kbps
720p10: 1283 kbps,  720p30: 1750 kbps,  720p60: 2450 kbps
```
This approach will also work correctly with e.g. 480p60 video (if enabled). It should also work correctly with different `VIDEO_TRANSCODING_FPS.AVERAGE`, `VIDEO_TRANSCODING_FPS.MAX` etc values (untested).
You can visualize the formula here: https://www.wolframalpha.com/input/?i=3300+%2B+(x+-+30)+*+(1320%2F30); …
=> Scale bitrate linearly with FPS

server/helpers/ffmpeg-utils.ts
The rebase for #1205 was quite messy, so I just applied the patch to develop instead. That broke the PR somehow, so here's the same changes again.
=> Set keyframe interval for transcoding (fixes #1147)

client/src/app/+my-account/my-account-settings/my-account-video-settings/my-account-video-settings.component.html, client/src/app/+my-account/my-account-settings/my-account-video-settings/my-account-video-settings.component.ts, client/src/app/core/auth/auth-user.model.ts, client/src/app/shared/users/user.model.ts, client/src/assets/player/peertube-player-local-storage.ts, client/src/assets/player/peertube-videojs-plugin.ts, server/controllers/api/users/me.ts, server/helpers/custom-validators/users.ts, server/initializers/constants.ts, server/initializers/migrations/0280-webtorrent-policy-user.ts, server/models/account/user.ts, shared/models/users/user-update-me.model.ts, shared/models/users/user-webtorrent-policy.type.ts
- add a key in localstorage to remember the opt-out
- add a user setting
Visitors don't have an interface to modify the setting (yet) but that requires more work (modifying buttons in videojs is no small feat) and will be the subject of another PR. Better do things incrementally.
related to #685
=> add webtorrent opt-out settings

client/src/app/+admin/moderation/video-abuse-list/video-abuse-list.component.ts, client/src/locale/source/angular_en_US.xml
To resolve #1295, I fixed these two strings to make it more obvious that it is referring to the _report_, and not the _content_, that is going to be deleted.
In order to update the i18n files, I ran `npm run build`, which gave me a lot of internationalization warnings for missing translations but only seemed to touch the `en-US` file. I hope this is OK for now, and that the translators to other languages are still able to translate these new strings without much difficulty.
PeerTube is a great project!
=> Improve some of the wording around abuse reports UI

server/tools/cli.ts
application-config.read() returns an empty object when no config data is present (i.e. when run on a new install) so test for an empty object in cli.ts instead of testing for 'null' (which fails on empty objects)
=> Fix #1328 - application-config.read() returns an empty object, test for it

server/tools/peertube-import-videos.ts
The way tool video imports works right now doesn't scale if you run multiple imports at the same time, it deletes another processes file, to fix the issue we should sha256 the url of the video being downloaded and the thumbnail as well because it can happen with thumbnails since currently it uses the same path, not allowing for multiple import jobs to run at once.
All tests pass, so that's good.
I tried to make this pull request before, but my previous account got flagged
=> allow peertube-import-videos.ts CLI script to run concurrently

client/src/app/videos/+video-watch/comment/linkifier.service.ts, client/src/app/videos/+video-watch/video-watch.component.ts, client/src/assets/player/peertube-player.ts, client/src/assets/player/settings-menu-button.ts, client/tsconfig.json
this adds the `noImplicitThis` compiler option to make the code even more type secure.
>Raise error on `this` expressions with an implied `any` type.
please review, as I am not sure if this is the best way to fix the errors
=> add noImplicitThis flag

README.md
It doesn't assume people read the preceding text
=> Replace 'Create one' with 'Create an instace' in README

server/helpers/activitypub.ts
I guess it refers to the VideoState enum used here as `state` instead.
=> Rename context stats to state

support/doc/production.md
Use install(1) instead of cp(1) and chmod(1) to install
the service file. Also, use sysrc(8) to enable the PeerTube
service in rc.conf(5).
=> Improve FreeBSD setup instructions

scripts/upgrade.sh
I just had my upgrade fail because most of my server's disk space was taken up by the video cache. So I added this quick check to the upgrade script.
The minimum free space of 1 GB is somewhat arbitary, because each Peertube installation only takes around 270 MB on my server. But it's better to have too much than too little.
=> Check free storage before upgrading

client/src/app/videos/+video-edit/video-add-components/video-upload.component.ts, support/nginx/peertube
Ideally we'd know what the specific server's configured upload limit
is before starting, but this 8GB limit is not useful if an administrator
has changed the nginx post limit on the server.
=> Remove hard-coded 8GB upload limit in client

client/src/app/+verify-account/verify-account-email/verify-account-email.component.html
I encountered this bug when working on #993 . The link is likely rarely needed (only if verification string is wrong) which is why it has not been encountered.
=> rename ask-email link to ask-send-email

server/tools/peertube-import-videos.ts
This is my solution for the '/' at the end of urls which create problems in the import videos script (issue #1453).
I forgot to open a pull request for this.
The issue was closed yersterday but is the problem resolved or not ? Cause I haven't seen any proposal to solved it.
Maybe, it wasn't a real problem.
Thanks.
=> Remove the eventual trailing '/' at the end of urls (see #1453)

support/systemd/peertube.service
* I set the `PrivateDevices=` directive to true, because I doubt that Peertube is being used on Raspberry Pies currently.
* Because the installation guide recommends `/var/www/peertube` as the home directory for the Peertube user, I think it’s safe to remove the ability for Peertube to access `/home`, `/root`, and `/run/user`.
* The service still has sys admin capabilities, and in theory can circumvent the sandbox restrictions. In the [manual](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#ReadWritePaths=) it is recommend to drop this capability for an effective sandbox.
=> More systemd service hardening

server/tests/api/server/email.ts, server/tests/api/users/users-verification.ts, shared/utils/miscs/email-child-process.js, shared/utils/miscs/email.ts
Resolves #1482 
I discovered that if MailDev instantiation fails the process is terminated with a 0 exit code. The only way to report this back as an error is to run as forked child process.
Besides the approach an alternate option is to use a different library - which I'm open to.
Now - it fails when expected (e.g. postfix listening on port 1025):
And also keeps running when expected when used in multiple test files:
I'm open to criticisms on approach with singleton class.
=> Throw error if MailDev doesn't run

client/src/app/shared/user-subscription/remote-subscribe.component.ts
Some of federation projects don't support `/authorize_interaction?acct={uri}` endpoint (e.g. [Misskey](https://github.com/syuilo/misskey)). So I propose to support WebFinger on the workflow of the remote subscribe button.
=> Add WebFinger support

support/docker/production/docker-entrypoint.sh
Hello!
Here is a little patch to speed up the docker start on large instance.
Indeed the `chown -R` is executed on all files, even if the right are already ok, which cost IO and is very long with lots of files.
The patch uses find to read (instead of write) each files and apply the chown only if necessary, which speed up the start.
From benchmark on my instance, it reduces the start from 6 minutes to less than 1 minute :)
Datalove <3
=> Patch docker entrypoint to speed up the chown at startup

server/tests/api/check-params/accounts.ts
Noticed this when searching for "Test users API validators" - both in `check-params/users.ts` & `check-params/accounts.ts` so this one must be a typo.
=> fix typo in test accounts api validators

server/lib/job-queue/handlers/video-file.ts, server/tests/api/users/user-notifications.ts
also increase timeouts on user-notification test (for less powerful machines)
resolves #1601 
I added the (originally) failing test `"My video is published"/"Should not send a notification before the video is published"`. The similar test `"New video from my subscription notification"/"Should send a new video notification when a remote video becomes public"` was okay because the private status prevented subscription notification.
I had to skip all the "import" tests as they're all failing locally for reasons I'm unsure of. I'll create another issue with some ideas later.
=> don't notify prior to scheduled update

support/nginx/peertube
As stated by https://nginx.org/en/docs/http/ngx_http_gzip_module.html, text/html is always part of the gzip_types. This removes a warning when checking the Nginx configuration files.
=> Nginx config file: remove text/html from gzip_types

client/src/app/shared/forms/form-validators/video-validators.service.ts, client/src/app/shared/video-import/video-import.service.ts, client/src/app/shared/video/video-edit.model.ts, client/src/app/shared/video/video.model.ts, client/src/app/shared/video/video.service.ts, client/src/app/videos/+video-edit/shared/video-edit.component.html, client/src/app/videos/+video-edit/shared/video-edit.component.ts, client/src/app/videos/+video-watch/video-watch.component.html, client/src/app/videos/+video-watch/video-watch.component.scss, server/controllers/api/videos/index.ts, server/helpers/custom-validators/videos.ts, server/initializers/migrations/0295-add-originally-published-at.ts, server/middlewares/validators/videos/videos.ts, server/models/video/video-format-utils.ts, server/models/video/video.ts, shared/models/activitypub/objects/video-torrent-object.ts, shared/models/videos/video-create.model.ts, shared/models/videos/video-update.model.ts, shared/models/videos/video.model.ts
This PR is related to the following issue #946.
I'm working on it with @auberanger and @am97, we are all CS students.
This first commit is the very beginning of our work, a kind of "Hello World" commit to PeerTube's code after a few documentation contributions.
Until now, we called the field `producedAt`. It can be changed of course.
=> WIP : add production date for videos

client/src/app/shared/misc/from-now.pipe.ts
Use Math.max to make negative seconds equal to zero instead. Remove redundant Math.floor operation.
=> Fix negative seconds by displaying 0 instead (#1445)

server/middlewares/validators/config.ts, server/tests/api/check-params/config.ts, server/tests/api/server/config.ts
Instead of #1471
Resolves #993
> Chocobozzz: I think we should prevent peertube from starting if it is incorrectly configured. For example, in the `checkConfig` function: https://github.com/Chocobozzz/PeerTube/blob/develop/server/initializers/checker-after-init.ts#L34
> Nutomic: But you can also change these settings in the web interface so there needs to be a warning/error as well.
> Chocobozzz: If both are implemented yep remove the warning above
@Chocobozzz you already implemented the 1st so this is just for the 2nd. I only check if email is enabled for `requiresEmailVerification` since you had `contactForm` as warning only.
I was considering some logic on the client to disable the checkbox if email is not enabled but I feel this is good enough. Let me know if you'd like me to.
=> check email enabled for requiresEmailVer config

support/doc/dependencies.md
=> Add missing python-dev dependency for Debian/Ubuntu systems

support/docker/production/.env
I was following the instructions here: https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/docker.md
However, after completing the instructions and running `docker-compose up`, I Peertube failed to start and I received the following errors:
```
peertube_1       | [testing.peertube.social:443] 2019-03-08 14:30:12.044 error: Failed to connect to SMTP postfix:25. {
peertube_1       |   "meta": {
peertube_1       |     "err": {
peertube_1       |       "stack": "Error: Invalid login: 503 5.5.1 Error: authentication not enabled\n    at SMTPConnection._formatError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:605:19)\n    at SMTPConnection._actionAUTHComplete (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1340:34)\n    at …
```
=> Fix problem with SMTP in default docker-compose setup

.github/CONTRIBUTING.md, .gitpod.yml, client/proxy.config.json, client/src/environments/environment.hmr.ts, scripts/watch/client.sh, support/docker/gitpod/Dockerfile, support/docker/gitpod/setup_postgres.sql
Hi @Chocobozzz! 👋
These days I work for gitpod.io (a free one-click online IDE for GitHub) and I really wanted to contribute a fully-automated dev setup for PeerTube. ⚡️📺⚡️
Here is what it looks like:
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/jankeromnes/PeerTube)
Notes:
- This changes the `hmr` config slightly to make the front-end proxy `/api` requests to `http://localhost:9000`, instead of the front-end referencing the backend directly.
- Please let me know if I should create a dedicated Gitpod config instead or re-using `hmr`.
I hope this can save PeerTube contributors a lot of time and troubles. Please let me know what you think. 🙂
=> Add automated dev setup using Gitpod

client/src/sass/include/_miniature.scss
A temporary fix, until a better solution is found (maybe #1158 + #1588?), that increases the blur because right now NSFW thumbnails are way too transparent.
=> _miniature.scss .blur-filter from 5px blur to 20px

support/docker/production/Dockerfile.stretch
Allow to pass extra options to the npm run build eg: --light or --light-fr to not build all client languages (speed up build time if i18n is not required)
=> Add argument to dockerfile to pass options to npm run build

client/src/app/shared/video/modals/video-download.component.ts
Use the NgActiveModal method to close it on a click by adding a specific
modalActive object and use it on download function.
See issue: Chocobozzz#1436
=> fix: Close modal after clicking on download

server/initializers/installer.ts, support/doc/production.md
Add a condition test to pass by environement a predetermined
root password for setting up.
Related work in documentation: https://framagit.org/framasoft/peertube/documentation/merge_requests/16
=> Add way to set root password by environnement.

support/docker/production/.env, support/docker/production/docker-compose.yml
Peertube was not getting the correct client IP on my instance, so here is what I did to fix it.
According to [this comment](https://github.com/docker/compose/issues/4336#issuecomment-273341619), docker-compose essentially uses a random subnet by default, so we have to specify that in docker-compose.yml. The same subnet has to be added to .env as trust_proxy.
Slightly unrelated, but can you tell me a good place to link my [peertube-compose](https://radical.town/@felix/102106907762520601) project? @rigelk suggested I add it to the wiki here, but then I have to add a new page or completely rewrite the "Ansible playbook" page, and I dont know how that should look.
=> Fix docker-compose setup so Peertube sees correct IP

client/src/app/search/search-filters.component.ts
Search filter options (for searching by duration) were out of sequence (short, long, medium) and now they are in sequence (short, medium, long)
I am not able to test this change (I do not have a working instance of PeerTube at the moment). I will make updates if necessary.
Closes #1920
=> Rearrange search filter options

support/doc/dependencies.md
The media-libs/vips package does not exist on Gentoo (and all works fine on my PeerTube POC without vips).
=> For Gentoo : update @peertube set (delete vips)

support/doc/dependencies.md
Gentoo has not "stable" keyword for yarn (cf source, next line), you need to add "testing" keyword for yarn.
Source : https://packages.gentoo.org/packages/sys-apps/yarn
=> For Gentoo : set testing keyword for yarn

client/src/sass/include/_fonts.scss
Adding the `font-display` property with `swap` improves the time until text is rendered.
Text should not be hidden due to webfont loading.
Some text content is not visible until the staggered loads of webfonts complete.
=> Add font-display

server/tools/package.json, server/tools/peertube-import-videos.ts
As a PeerTube administrator, I would like to be able to synchronize a YT channel with a PT instance with the agreement of the videos author using a crontab.
However, I cannot rely on the name of the videos on YT. So I would like the job to only fetch the videos published since the last time I ran the peertube-import-videos job.
> Usage: import-videos [options]                        
> 
> Options:
-n, --video-name <name>                Video name
-c, --category <category_number>       Category number
-l, --licence <licence_number>         Licence number
-L, --language <language_code>         Language ISO 639 code (fr or en...)
-t, --tags <tags>                      Video tags
-N, --nsfw                             Video is Not Safe For Work
-d, --video-description <description>  Video …
=> Add since parameter to peertube-import-videos

support/doc/api/openapi.yaml
When using the API I noticed originallyPublishedAt was missing from the API documentation, but the key/value pair is being accepted in /videos/upload as long as the string has a date-time format.
=> Add originallyPublishedAt in /videos/upload to the OpenAPI document

support/doc/api/openapi.yaml
The OpenAPI specification allows for specific array and string restrictions. See: https://swagger.io/docs/specification/data-models/data-types/
=> Specify the restrictions on tags array and it's string items

client/src/sass/player/peertube-skin.scss, client/src/standalone/videos/embed.ts
Small change includes removing unnecessary emojis and making the text clearer and easier to understand for people who aren't familiar with words like “P2P” and “IP is downloading” on embedded videos.
=> Cleaner warning of IP address leaking on embedded videos

package.json, server/tools/cli.ts, server/tools/peertube-import-videos.ts
The `--tmpdir <tmpdir>` parameter can be used to designate a working directory for downloading and converting imported videos.
Without this parameter PT will unceremoniously (attempt to) dump videos into its own _tools_ directory - where the user might not even have write access.
I refrained from creating a randomly-named tmpdir inside the designated directory as the file names used by pt-i-v are already randomised and as such the chance of a file name collision is negligible.
The program will error out with `--tmpdir directory_name_here: directory does not exist or is not accessible` if the designated directory does not exist.
The `--first n` and `--last n` parameters can be used to limit processing to the first or last _n_ elements of the playlist returned by `youtube-dl`. These …
=> peertube-import-videos.ts: add --tmpdir, --first, --last and --verbose [level] parameters

support/doc/tools.md
This just corrects the documentation for the video importer: the actual parameter has become --target-url and not anymore -t
=> CLI tools documentation: Change cli parameter from -t to --target-url

client/src/app/shared/user-subscription/subscribe-button.component.html, client/src/app/shared/user-subscription/subscribe-button.component.ts
Currently the button to subscribe via RSS to a channel is not working when using the Firefox browser. This is due to the automatic content-disposition Firefox assigns on links ending with file extensions (.xml and .atom), resulting in a download modal instead of showing it inline in a browser window or tab.
This pull request does not fix the automatic content-disposition, but makes the button into a link, so that Firefox users can at least use the right-click context menu and copy the link location.
This problem was already mentioned in issue #1648 , but not fixed and further discussion let it to be labeled as a future enhancement. I suggest to implement this fix now and leave the future enhancement (adding Subscribe via Atom and Subscribe via JSON) for later.
=> Fix subscribe via RSS button

client/src/app/+admin/config/edit-custom-config/edit-custom-config.component.html, client/src/app/menu/menu.component.html, client/src/app/videos/video-list/index.ts, client/src/app/videos/video-list/video-most-liked.component.ts, client/src/app/videos/videos-routing.module.ts, client/src/app/videos/videos.module.ts, shared/models/plugins/client-hook.model.ts
Related to #2095 
This PR adds a "Most liked videos" page. It can be accessed from main menu.
Videos listed in this page are retrieved from the already existing API endpoint:
`/api/v1/videos/?sort=-likes`
=> Add 'Most liked videos' page

client/src/app/+about/about-instance/about-instance.component.html, client/src/app/shared/instance/instance-statistics.component.html, client/src/app/shared/instance/instance-statistics.component.scss, client/src/app/shared/instance/instance-statistics.component.ts, client/src/app/shared/shared.module.ts
Related to #1944 
Add a statistics section at the bottom of About > Instance page.
It displays stats information available from API `/api/v1/server/stats`, i.e:
```
{
"totalLocalVideos": 613,
"totalLocalVideoViews": 10970,
"totalLocalVideoFilesSize": 110845399897,
"totalLocalVideoComments": 6,
"totalVideos": 926,
"totalVideoComments": 154,
"totalUsers": 318,
"totalInstanceFollowers": 72,
"totalInstanceFollowing": 0,
"videosRedundancy": [
{
"totalUsed": 0,
"totalVideos": 0,
"totalVideoFiles": 0,
"strategy": "most-views",
"totalSize": 10737418240
}
]
}
```
(Note that `videosRedundancy` is not represented.)
=> Add statistics section in about page

.gitignore, client/.gitignore
I always have generated files on which I have to be careful not to commit them.
They are generated during development build.
This PR adds these files to `.gitignore`:
yarn-error.log
init.mp4
client/src/locale/pending_target/
=> Add generated files to gitignore to have a clean git stage

client/src/app/shared/date/date-toggle.component.html, client/src/app/shared/date/date-toggle.component.scss, client/src/app/shared/date/date-toggle.component.ts, client/src/app/shared/shared.module.ts, client/src/app/shared/video/video-miniature.component.html, client/src/app/videos/+video-watch/video-watch.component.html
Related to #1695 
Allows to display full video published date/time by clicking on it, or hovering date.
=> Allow to toggle video publication date to display absolute date

client/package.json, client/src/app/+my-account/my-account-video-playlists/my-account-video-playlist-elements.component.html, client/src/app/+my-account/my-account-video-playlists/my-account-video-playlist-elements.component.ts, client/yarn.lock
Related issue: #2078 
This PR adds a delay (500ms) on videos reordering in playlist for small screens (< 800px). We can now scroll on playlists without unwanted drag and drop.
=> Add a drag&drop delay on playlist videos to allow user scroll on small screens

shared/extra-utils/search/videos.ts
It seems that this function is used nowhere. Do you think it's fine to remove it?
Florent
=> Remove unused function searchVideoWithPagination

server/tools/peertube-import-videos.ts
Youtube doesn't store the hour of the publish date so
set it to zero in order to compare it.
=> Fix hours in peertube-import-videos

client/src/app/login/login.component.html
The link currently points to https://joinpeertube.org/en/#instances-list , but the instance list has been moved to https://joinpeertube.org/instances#instances-list
=> Fix link for account creation on another instance

client/src/sass/bootstrap.scss
In dark theme, instance stats (at the bottom of the page `/about`) are displayed white on white.
This PR makes bootstrap `.card` use foreground and background colors from theme.
=> Fix instance statistics display in dark theme

README.md
Fixes #2236
It looks like the "create your own instance" anchor doesn't work on Docker Hub though it works on GitHub. This fixes it both places.
Also fixes some broken GitHub links (need to be `blob/develop/...`)
Thanks for PeerTube! Just installed it for myself and works like a charm.
=> More fixes to README

support/docker/production/Dockerfile.stretch
I was playing around with the Docker image, and noticed that is a lot of potential to save space, even without switching to Alpine or otherwise losing any functionality. The image from this Dockerfile has 850 mb, compared to 1.9 gb to the official release image. 
For a short explanation of the changes:
- switched to the slim image variant, because I think it is a waste of space and bandwidth to use the 330 mb stretch image when the 50 mb stretch-slim image has all the necessary tools
- there were several seperate apt install commands for no reason, and one of them was missing the --no-install-recommends flag
- the package dirmngr is not referenced anywhere in the repo, so it seems unused
On a side note, the `chocobozzz/peertube:v2.0.0-stretch` image from Docker Hub contains a 300 mb …
=> Simplify Dockerfile and slim Docker image

client/src/app/videos/+video-watch/comment/video-comment.component.html, client/src/app/videos/+video-watch/comment/video-comment.component.scss, client/src/app/videos/+video-watch/comment/video-comment.component.ts, client/src/app/videos/+video-watch/comment/video-comment.model.ts, client/src/app/videos/+video-watch/comment/video-comments.component.ts, server/controllers/activitypub/client.ts, server/controllers/api/videos/comment.ts, server/helpers/custom-validators/activitypub/video-comments.ts, server/initializers/constants.ts, server/initializers/migrations/0450-soft-delete-video-comments.ts, server/lib/activitypub/process/process-delete.ts, server/lib/activitypub/video-comments.ts, server/lib/video-comment.ts, server/models/account/account.ts, server/models/video/video-comment.ts, server/tests/api/videos/multiple-servers.ts, server/tests/api/videos/video-comments.ts, shared/models/activitypub/objects/common-objects.ts, shared/models/videos/video-comment.model.ts
Related to #507 
Currently, when deleting a comment that have replies, the comment and all the replies were removed.
This PR only soft deleted comments so that replies stay visible.
=> Soft delete comments so that entire thread is not deleted

client/src/sass/bootstrap.scss
=> lighter box-shadow for .dropdown-menu

client/src/app/shared/video/video-thumbnail.component.scss, client/src/sass/include/_miniature.scss
Initial state
Before/After
While having the duration show a bit better would by itself be sufficient, I thought that having the overlay a bit more transparent would be nice, since mouse focus on a video usually means one wants to see the thumbnail clearly.
=> miniature duration visibility and overlay background opacity

client/src/app/videos/+video-watch/video-watch.component.html, client/src/app/videos/+video-watch/video-watch.component.scss
This PR is only modifying css/html for the video-watch page, and only regarding the title block and the recommendations block. Its aim is to improve:
- long title display on small screens
- space taken when no recommendation is available
Below, on a 1100px-wide viewport before the PR, and after the PR:
=> improve video-watch title display on small screens

client/src/app/videos/+video-watch/video-watch.component.html, client/src/app/videos/+video-watch/video-watch.component.scss, client/src/sass/application.scss, client/src/sass/include/_variables.scss
I've been wondering about the look and feel of buttons in the watch page. To me, the row of buttons looks bulky in a part of the UI where visual space is scarce. The colors (especially with the support button adding yet another color) don't mix well with the gray of the buttons' background:
Option 1: transparent background and inverted support button
Option 2: transparent background and normal support button that reverts back to the current design on hover
Option 3: (my preference and the current content of the PR) option 2 + neutralize the green/red of like/dislike buttons, and (resp.) use the main color and a darker shade of the foreground color.
Note I switched text to uppercase since it balances the lack of background in terms of noticeability of the buttons.
=> Design suggestion for the action buttons row in video watch page

client/src/app/+accounts/account-video-channels/account-video-channels.component.html, client/src/app/+accounts/accounts.component.html, client/src/app/+accounts/accounts.component.scss, client/src/app/+accounts/accounts.component.ts, client/src/app/+my-account/my-account-subscriptions/my-account-subscriptions.component.html, client/src/app/+video-channels/video-channels.component.html, client/src/app/search/search.component.html, client/src/app/shared/user-subscription/subscribe-button.component.html, client/src/app/shared/user-subscription/subscribe-button.component.scss, client/src/app/shared/user-subscription/subscribe-button.component.ts, client/src/app/shared/user-subscription/user-subscription.service.ts, client/src/app/shared/video/video-miniature.component.html, client/src/app/videos/+video-watch/video-watch.component.html, client/src/sass/include/_mixins.scss
resolves #2389
still lacking:
side changes:
- uppercase account/channel nav
- single/plural for "view(s)"
- single/plural for "subscriber(s)"
=> Refactor my-subscribe-button to support full account subscription

server/lib/plugins/plugin-manager.ts
I noticed that when developing a plugin, the hooks where called multiple times. Sometimes with old code. I found the issue here. It works with plugin under development. I did not try with plugins installed directory from npm, but I'm pretty sure it will be ok.
=> Fix: unregistring a plugin did not remove properly his hooks.

server/controllers/api/config.ts
The `filter:api.user.signup.allowed.result` hook is called in two places : on the register form submit, and in getConfig.
I propose passing the request IP in the getConfig call too.
The reason why: I'm developing a plugin that will allow/disallow the registration for some countries. So I can test before the form submit if I want. 
The plugin can still know if we are in getConfig or on the form submit, by testing `params.body`.
=> Adding the request ip for hook filter:api.user.signup.allowed.result

client/src/app/+accounts/accounts.component.html, client/src/app/+accounts/accounts.component.scss, client/src/app/+accounts/accounts.component.ts, client/src/app/+my-account/my-account-video-playlists/my-account-video-playlists.component.html, client/src/app/+my-account/my-account-videos/my-account-videos.component.html, client/src/app/+my-account/my-account-videos/my-account-videos.component.ts, client/src/app/+video-channels/video-channels.component.html, client/src/app/+video-channels/video-channels.component.scss, client/src/app/+video-channels/video-channels.component.ts, client/src/sass/application.scss, client/src/sass/bootstrap.scss, client/src/sass/include/_mixins.scss, client/src/sass/include/_variables.scss
Own channels/account "Manage" buttons for quick access to administration:
Video counts:
=> Add manage buttons for own channels and account, video counts

server/controllers/api/videos/index.ts, server/helpers/ffmpeg-utils.ts, server/helpers/logger.ts, server/initializers/constants.ts, server/middlewares/validators/videos/videos.ts, server/tests/api/videos/video-transcoder.ts, shared/extra-utils/miscs/miscs.ts, shared/models/videos/video-transcoding-fps.model.ts, support/doc/api/openapi.yaml
resolves #2350
The PR defines two sets of acceptable framerates: standard and hd standard framerates, which are used to check a video's conformance to player standards. If a video uses a non-standard framerate, we check if even downsampling is possible before rejecting.
=> Downsample to the closest divisor standard framerate

client/src/app/+signup/+register/register-step-user.component.html
>  The username is a unique identifier of your account on this and all the other instances.
this is true if we consider "john@domain.com" as "an account". If by "an account" you only mean "john" then the text needs to be changed to something like:
> The username is a unique identifier of your account on this instances. Together with the domain name - it becomes unique across all instances.
In any case, English native speakers I'm open to suggestions on how to improve this :)
=> Account identifier text description

client/src/app/+signup/+register/register-step-channel.component.html
>  The channel name is a unique identifier of your channel on this and all the other instances.
this is true if we consider "cats@domain.com" as "a channel". If by "a channel" you only mean "cats" then the text needs to be changed to something like:
> The channel name is a unique identifier of your channel on this instance. Together with the domain name - it becomes unique across all instances.
In any case, English native speakers I'm open to suggestions on how to improve this :)
=> Channel identifier text description

server/tools/peertube-import-videos.ts
- Fixes #2377 
- Possibly fixes #2471 via youtube-dl `exec` or `--postprocessor-args` option
- Possibly help fixing #2385
As an additional effect, this PR dumps youtube-dl **error** output rather than only the `exec()` (error) status which makes way easier to debug youtube-dl failures.
=> peertube-import-videos passes remaining options down to youtube-dl

client/src/app/+about/about-instance/contact-admin-modal.component.ts, client/src/app/+accounts/accounts.component.html, client/src/app/+accounts/accounts.component.ts, client/src/app/+admin/admin.component.html, client/src/app/+admin/admin.component.ts, client/src/app/+admin/moderation/video-abuse-list/moderation-comment-modal.component.ts, client/src/app/+my-account/my-account-ownership/my-account-accept-ownership/my-account-accept-ownership.component.ts, client/src/app/+my-account/my-account-videos/video-change-ownership/video-change-ownership.component.ts, client/src/app/+video-channels/video-channels.component.html, client/src/app/+video-channels/video-channels.component.ts, client/src/app/menu/language-chooser.component.ts, client/src/app/modal/instance-config-warning-modal.component.ts, client/src/app/modal/welcome-modal.component.ts, client/src/app/shared/misc/list-overflow.component.html, client/src/app/shared/misc/list-overflow.component.scss, client/src/app/shared/misc/list-overflow.component.ts, client/src/app/shared/moderation/user-ban-modal.component.ts, client/src/app/shared/shared.module.ts, client/src/app/shared/video/modals/video-blacklist.component.ts, client/src/app/shared/video/modals/video-download.component.ts, client/src/app/shared/video/modals/video-report.component.ts, client/src/app/videos/+video-edit/shared/video-caption-add-modal.component.ts, client/src/app/videos/+video-watch/modal/video-share.component.ts, client/src/app/videos/+video-watch/modal/video-support.component.ts, client/src/sass/application.scss, client/src/sass/bootstrap.scss
This PR creates a list wrapper, that detects overflow in its list and hides overflowing elements to put them in a dropdown or modal, depending on the device used.
The modification is especially useful for small screens and mobile devices.
---
On mobile, after clicking the rightmost button of the sub-menu:
On desktop, without click, `md` breakpoint:
=> Add ListOverflow component to prevent sub-menu overflow

scripts/build/client.sh
Hello! 
I had CSS issues for a specific language (Spanish) and I needed to add a '--light-es' parameter to the client.sh in order to test it without losing 20 minutes for each compilation. It can be useful to have a --light parameter for each language so when developers face problems for a specific languages they don't need to  build the entire project.
=> Extend build commands

support/doc/docker.md
The link syntax was broken due to a stray newline.
=> fix markdown link

FAQ.md
FAQ previously did not explain how views are calculated for videos under 30 seconds. Minor rewording fixes based on feedback from non-technical person.
=> Explain view calculation on short videos, rewording

client/src/app/+admin/plugins/plugin-list-installed/plugin-list-installed.component.html, client/src/app/+admin/system/logs/logs.component.html, client/src/app/+my-account/my-account-history/my-account-history.component.html, client/src/app/+my-account/my-account-settings/my-account-video-settings/my-account-video-settings.component.html, client/src/app/app.component.html, client/src/app/login/login.component.html, client/src/app/modal/instance-config-warning-modal.component.html, client/src/app/shared/instance/instance-features-table.component.html, client/src/app/shared/video-playlist/video-add-to-playlist.component.html
I have searched through all HTML files in /client/scr/app for elements with a title attribute, but not i18n-title (#2506). Doing that, I also found some more strings that weren't tagged as translatable.
=> Mark additional strings as translatable

client/src/app/videos/+video-watch/comment/video-comments.component.ts
Fix for issue #2532 (https://github.com/Chocobozzz/PeerTube/issues/2532)
I saw that 'onNearOfBottom' function is incrementing the current comments page before check if it 'hasMoreItems'. This is getting an uncomplete comments set because it skip always last comments page. Another approach would be set the default value of 'this.componentPagination.currentPage' to 0 instead of 1. But, in my opinion, this is more reliable.
=> Fixing load more comments on infinite scroll

client/src/app/videos/+video-watch/comment/video-comments.component.ts, shared/models/plugins/client-hook.model.ts
I'm adding donate buttons to the comments via a plugin (peertube-plugin.bittube-airtime-module) 
I needed to add a hook to know when the comments are loaded and when the load more comments on scroll is being triggered. Would be nice to add it to the Federation in order to keep my plugin compatible with it. I also may be usefull for somebody else. Feel free to make suggestions and thanks a lot!
=> Add action hook, comments loaded

support/nginx/peertube
Using fuse storage as per #147, and assuming all videos are then in the bucket/container, this allows to make clients directly download from it instead of using PeerTube as a proxy = massive direct bandwidth reduction.
TODO:
HOW TO USE
Just uncomment lines 162-165, and set the `$cdn` variable to your base storage bucket url.
=> Add Nginx configuration to redirect videos to their CDN location

server/controllers/webfinger.ts
Hey there,
while trying to remotely subscribe to a channel on [this instance](https://thinkerview.video/) (with an account on [this instance](https://skeptikon.fr/)) I noticed an error in my JS console which **halts the remote subscription process** :
```
Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://skeptikon.fr/.well-known/webfinger?resource=acct:zm_@skeptikon.fr. Raison : l’en-tête CORS « Access-Control-Allow-Origin » est manquant.
```
> A cross-origin request has been bloqued: « Same Origin » policy doesn't allow to fetch remote ressource at https://skeptikon.fr/.well-known/webfinger?resource=acct:zm_@skeptikon.fr. Reason: CORS header « Access-Control-Allow-Origin » is …
=> Fix CSP issue on WebFinger service

client/src/app/+video-channels/video-channels.component.ts, client/src/app/videos/+video-watch/comment/video-comments.component.ts, shared/models/plugins/client-hook.model.ts
Hi!
As I did last week for comments, I added a donation button to comment replies (only if you have peertube-plugin-bittube-airtime-module)
In order to do this from my plugin, I needed to add this hook for comment replies loaded, returning the array of replies. I would be nice to keep my plugin compatible with the federation by adding this PR. It also may be useful for somebody else. Thanks in advance!
=> Action hook: thread replies loaded

support/doc/docker.md, support/docker/production/.env, support/docker/production/docker-compose.yml
Issue: https://github.com/Chocobozzz/PeerTube/issues/2545
Add DKIM generation keys and DKIM signature sending with the current image `mwader/postfix-relay`.
=> Add DKIM to docker-compose

client/src/app/+admin/config/edit-custom-config/edit-custom-config.component.html, client/src/app/+admin/config/edit-custom-config/edit-custom-config.component.scss, client/src/app/+admin/users/user-edit/user-create.component.ts, client/src/app/+admin/users/user-edit/user-edit.component.html, client/src/app/+admin/users/user-edit/user-edit.component.scss, client/src/app/+admin/users/user-edit/user-edit.ts, client/src/app/+admin/users/user-edit/user-password.component.ts, client/src/app/+admin/users/user-edit/user-update.component.ts, client/src/app/+my-account/my-account.module.ts, client/src/app/+my-account/shared/actor-avatar-info.component.html, client/src/app/shared/shared.module.ts, client/src/app/shared/users/user.model.ts, client/src/app/shared/users/user.service.ts, client/src/app/shared/video/modals/video-report.component.html, client/src/sass/include/_mixins.scss, server/middlewares/validators/users.ts, server/models/account/user.ts, server/tests/api/users/users.ts, shared/extra-utils/users/users.ts, shared/models/users/user.model.ts
The PR adds common stats to have an easier overview of a user's actions. It also uses the new layout for settings, and displays a user's avatar and display name. I use breadcrumbs to distinguish edit/create user views, and help for navigation within future listings related to a user.
=> Add overview of a user's actions in user-edit

client/package.json, client/src/app/+my-account/my-account-routing.module.ts, client/src/app/+my-account/my-account-video-channels/my-account-video-channels-routing.module.ts, client/src/app/+my-account/my-account-video-channels/my-account-video-channels.component.html, client/src/app/+my-account/my-account-video-channels/my-account-video-channels.component.scss, client/src/app/+my-account/my-account-video-channels/my-account-video-channels.component.ts, client/src/app/+my-account/my-account-video-channels/my-account-video-channels.module.ts, client/src/app/+my-account/my-account.module.ts, client/src/app/shared/video-channel/video-channel.model.ts, client/src/app/shared/video-channel/video-channel.service.ts, client/yarn.lock, server/controllers/api/accounts.ts, server/middlewares/validators/videos/video-channels.ts, server/models/video/video-channel.ts, server/tests/api/videos/video-channels.ts, shared/extra-utils/videos/video-channels.ts, shared/models/videos/channel/video-channel.model.ts
This PR shows a low-profile stats bar in the channels list, showing daily aggregated views for the videos of that channel for the past 30 days. 
Why just a thin bar? A more involved stats page would require more space, and either a dedicated view or dedicated component to integrate in the channel edit page - that's for later. This is just a proof-of-concept.
=> View stats for channels

support/docker/production/config/production.yaml
Everything under `/app/storage` should be moved to `/data`. However, `streaming-playlists` is not listed yet. So there will still be `/app/storage/streaming-playlists`. This PR fixes the problem.
=> [Docker] Move streaming-playlists to /data

client/src/app/+admin/plugins/plugin-show-installed/plugin-show-installed.component.html, client/src/app/core/plugins/plugin.service.ts, client/src/types/register-client-option.model.ts, shared/models/plugins/register-server-setting.model.ts, support/doc/plugins/guide.md
This PR adds to plugins :
- `markdown-text` and `markdown-enhanced` setting type to the server helpers
- `markdownRenderer` to the client helpers
As mentioned in this issue https://github.com/Chocobozzz/PeerTube/issues/2602, markdown is rendered with another library (marked) lazy-loaded over the internal markdown-it of PeerTube.
```js
registerSetting({
name: 'my-markdown-area',
label: 'Markdown text',
type: 'markdown-text',
default: false
})
```
```js
const { markdownRenderer } = peertubeHelpers
await markdownRenderer.textMarkdownToHTML('**My Bold Text**')
// return <strong>My Bold Text</strong>
await markdownRenderer.enhancedMarkdownToHTML('![alt-img](http://.../my-image.jpg)')
// return <img alt=alt-img src=http://.../my-image.jpg />
```
=> Add markdown support to plugins

client/src/app/videos/+video-edit/video-add.component.scss
**Issue** : https://github.com/Chocobozzz/PeerTube/issues/2676
Before
------
<div>
</div>
After
------
<div>
</div>
<div>
</div>
=> Make video-add-nav tabs scrollable on small devices

client/src/app/+accounts/account-video-channels/account-video-channels.component.scss, client/src/app/+accounts/accounts.component.scss, client/src/app/+my-account/my-account-notifications/my-account-notifications.component.scss, client/src/app/+my-account/my-account-settings/my-account-settings.component.scss, client/src/app/+my-account/my-account-subscriptions/my-account-subscriptions.component.scss, client/src/app/+my-account/my-account-video-channels/my-account-video-channel-edit.component.scss, client/src/app/+my-account/my-account-video-channels/my-account-video-channels.component.scss, client/src/app/+my-account/my-account-video-playlists/my-account-video-playlist-elements.component.scss, client/src/app/+my-account/my-account-video-playlists/my-account-video-playlists.component.scss, client/src/app/+my-account/my-account-videos/my-account-videos.component.scss, client/src/app/+video-channels/video-channels.component.scss, client/src/app/search/search.component.scss, client/src/app/shared/video/abstract-video-list.scss, client/src/sass/application.scss, client/src/sass/include/_mixins.scss, client/src/sass/include/_variables.scss
Fix `width: 100%` to textareas in small and mobile screens as it is applied for inputs  
Better display of channels headers of users.
@rigelk is this respond to this issue https://github.com/Chocobozzz/PeerTube/issues/2440 ?
<div>
</div>
`padding-bottom` on channel item + center every infos
<div>
</div>
center every infos + `flex-direction: column` to mobile and small screens
<div>
</div>
input name width 100% instead of auto
<div>
</div>
quota progress higher width than screen width instead of 100%
<div>
</div>
`flex-direction` header `column`
<div>
</div>
better display of control buttons + `flex-direction` header `column`
also add the $minimum-view (320px) in Sass variables
<div>
</div>
`flex-direction` header `column` + margin-bottom on first button
<div>
</div>
reproduce same css as …
=> Fix broken views on mobile and small screens

client/src/app/+my-account/my-account-history/my-account-history.component.scss
Small to fix broken buttons on mobile history view, for example in French language :
<div>
</div>
=> Fix broken buttons on mobile history view

client/src/sass/application.scss
Very small fix linked to this merged PR : https://github.com/Chocobozzz/PeerTube/pull/2671
The peertube-select where not included in the CSS rules for screen width under 800px, it caused an `overflow-x` on mobile view (between ~ `340px`  and  ~`400px` screen width)
=> Fix select width on view < 800px (mobile)

client/src/app/shared/menu/top-menu-dropdown.component.html, client/src/app/shared/menu/top-menu-dropdown.component.scss, client/src/app/shared/menu/top-menu-dropdown.component.ts
Here is the solution suggested for this issue :  https://github.com/Chocobozzz/PeerTube/issues/2673
Before:
<div>
</div>
Now:
<div>
</div>
Edit : it may be an issue of NgbDropdown, on small screens sometimes the dropdown is inside sometimes outside but in any case dropdown on a horizontal overflow menu is such a pain on touch screens, and not really mobile-friendly.
=> Use modal instead of dropdown menu in small/mobile views

client/src/app/app.component.html
Small fix preventing header size change when clicking on the left menu; the header elements (Logo, Title, Search Bar and Upload Button) have a weird effect of being resized / re-align vertically.
If that `border-bottom` is really useful on the left and right header elements, we can put it on the parent, so the `.header` element as proposed.
On the contrary, if that `border-bottom` on expanded view is useless (it is just a grey line inside a grey gradient...) we can drop it ? @rigelk  ?
=> Remove border-bottom on header to prevent header redimensioning

client/src/app/+admin/plugins/plugins.component.scss, client/src/app/+admin/system/jobs/jobs.component.scss, client/src/app/+admin/system/logs/logs.component.scss, client/src/sass/application.scss, client/src/sass/include/_mixins.scss
Small PR that makes the rest of the admin responsive (sub-navs, selects, buttons), what do you think ? 
<div>
</div>
_____
<div>
</div>
_____
<div>
</div>
____
<div>
</div>
=> Make admin sub-navs, selects, buttons responsive

client/src/app/+my-account/my-account-video-playlists/my-account-video-playlist-elements.component.scss, client/src/app/shared/video-playlist/video-playlist-element-miniature.component.html, client/src/app/shared/video-playlist/video-playlist-element-miniature.component.scss, client/src/app/shared/video-playlist/video-playlist-element-miniature.component.ts, client/src/app/videos/+video-watch/video-watch-playlist.component.html
This is a proposition for the issue : https://github.com/Chocobozzz/PeerTube/issues/2675
Make only the "delete option" available as YouTube does on watching playlist view to avoid dropdown menu in a scrolling content.
<div>
</div>
=> Avoid dropdown in scrolling own playlist watch (touchscreens)

client/src/app/core/menu/menu.service.ts, client/src/app/shared/menu/top-menu-dropdown.component.html, client/src/app/shared/menu/top-menu-dropdown.component.ts, client/src/app/shared/misc/screen.service.ts, client/src/sass/application.scss
This PR fix a regression on the menu of `/my-account/*` which was not horizontally scrollable anymore on screen width < 800px.
=> Fix regression my-account menu overflow-x on screen width < 800px

client/src/app/+my-account/my-account-video-channels/my-account-video-channels.component.html, client/src/app/+my-account/my-account-video-channels/my-account-video-channels.component.scss, client/src/app/+my-account/my-account-videos/my-account-videos.component.html, client/src/app/+my-account/my-account-videos/my-account-videos.component.scss, client/src/app/search/search.component.scss
This can respond to : https://github.com/Chocobozzz/PeerTube/issues/2710
The previous solution was not good enough, it broke all the `ngbTooltips` and asked some tricks for `action-dropdown` and `help-component`.
This new solution adapts  `my-account/videos` and `my-account/channels` on screen width from 800px to large screens with menu-left displayed.
This PR depends on the resolution of https://github.com/Chocobozzz/PeerTube/pull/2707
______
Previous solution : 
>I'm not sure of the proposition because it needs more tests with the dropdowns attached to the body container.
>
>This fix proposes to set `fixed` position to `.sub-header-container` and use `.main-col` container as the scrollable container, this way all fixed elements (`.header`, `.menu`, `.sub-header-container`) are …
=> Fix non-fixed header and menu when overflow-x body on touchscreens

server/controllers/activitypub/client.ts, server/controllers/api/videos/comment.ts, server/lib/activitypub/process/process-create.ts, server/lib/blocklist.ts, server/lib/notifier.ts, server/models/account/account.ts, server/models/utils.ts, server/models/video/video-abuse.ts, server/models/video/video-comment.ts, server/tests/api/users/blocklist.ts, server/tests/api/videos/multiple-servers.ts, server/tests/feeds/feeds.ts, shared/extra-utils/videos/video-comments.ts, shared/extra-utils/videos/videos.ts
Add better control for users of comments displayed on their videos:
* Do not forward comments from muted remote accounts/servers (muted by the current server or by the video owner)
* Do not list threads and hide replies (with their children) of accounts/servers muted by the video owner
* Hide from RSS comments of muted accounts/servers by video owners
Use case:
* Try to limit spam propagation in the federation
* Add ability for users to automatically hide comments on their videos from undesirable accounts/servers (the comment section belongs to videomakers, so they choose what's posted there)
=> Filter comments from muted accounts/instances

client/src/app/shared/channel/avatar.component.html, client/src/app/shared/channel/avatar.component.scss, client/src/app/shared/channel/avatar.component.ts, client/src/app/shared/video/abstract-video-list.ts, client/src/app/shared/video/video-miniature.component.html, client/src/app/shared/video/video-miniature.component.ts, client/src/app/videos/recommendations/recommended-videos.component.html, client/src/app/videos/recommendations/recommended-videos.component.ts, client/src/assets/images/global/search.svg, client/src/assets/images/menu/trending.svg
also contained in this PR: 
- svg height/width fix for `trending` and `search` icons, mainly for their use in the plugins/themes view
- `title` attribute for the avatars is now more descriptive
=> Add channel/account avatars in miniature

client/src/app/+admin/follows/following-list/following-list.component.html, client/src/app/+admin/moderation/instance-blocklist/instance-server-blocklist.component.html, client/src/app/+admin/users/user-list/user-list.component.html, client/src/app/+my-account/my-account-history/my-account-history.component.html, client/src/app/+my-account/my-account-notifications/my-account-notifications.component.html, client/src/app/+my-account/my-account-video-channels/my-account-video-channels.component.html, client/src/app/+my-account/my-account-video-playlists/my-account-video-playlists.component.html, client/src/app/+my-account/my-account-videos/my-account-videos.component.html, client/src/app/header/header.component.html, client/src/app/menu/avatar-notification.component.html, client/src/app/menu/menu.component.html, client/src/app/shared/buttons/delete-button.component.html, client/src/app/shared/buttons/edit-button.component.html, client/src/app/shared/users/user-notifications.component.html, client/src/app/shared/video-playlist/video-add-to-playlist.component.html, client/src/app/shared/video-playlist/video-playlist-element-miniature.component.html, client/src/app/videos/+video-edit/shared/video-edit.component.html, client/src/app/videos/+video-edit/video-add-components/video-import-torrent.component.html, client/src/app/videos/+video-edit/video-add-components/video-import-url.component.html, client/src/app/videos/+video-edit/video-add-components/video-upload.component.html, client/src/app/videos/+video-edit/video-update.component.html, client/src/app/videos/+video-watch/video-watch.component.html
This PR will add aria-hidden attribute to all non descriptive icons in order to improve a11y (screen readers don't have to read icons). 
For example these icons in front of the text in the left panel menu :
=> add aria-hidden to non-descriptive icons

client/src/app/menu/language-chooser.component.ts, client/src/sass/player/peertube-skin.scss
This PR will highlight the central play button on a video when it is focused in order to improve a11y.
=> change focus color instead of opacity of video play button

client/src/app/+about/about-instance/about-instance.component.html, client/src/app/shared/instance/feature-boolean.component.html, client/src/app/shared/instance/instance-features-table.component.html, client/src/app/shared/instance/instance-features-table.component.scss
This PR will improve a11y with a table caption, table structure with scope to help screen readers and aria-label for its yes/no icons.
=> add scope tags and aria-labels to instance table

client/src/app/+admin/plugins/plugin-search/plugin-search.component.html, client/src/app/shared/buttons/action-dropdown.component.html, client/src/app/shared/channel/avatar.component.scss, client/src/app/shared/menu/top-menu-dropdown.component.html, client/src/app/shared/users/user-notifications.component.html, client/src/app/shared/video/abstract-video-list.html, client/src/app/shared/video/video-miniature.component.html, client/src/app/shared/video/video-miniature.component.scss, client/src/app/videos/+video-edit/video-add-components/video-import-torrent.component.html, client/src/app/videos/+video-edit/video-add-components/video-import-url.component.html, client/src/app/videos/+video-edit/video-add-components/video-upload.component.html, client/src/app/videos/+video-watch/video-watch.component.html, client/src/app/videos/+video-watch/video-watch.component.ts, client/src/sass/application.scss
This PR will improve a11y with keyboard navigation on a video page. 
The actions buttons under a video can be activated with the keyboard (tab and enter) and the like dislike buttons now have a aria-label for screen readers.
=> add keyboard navigation for video actions

support/docker/production/.env
depends on: https://github.com/wader/postfix-relay/pull/18
=> fix opendkim permissions in docker-compose setup

server/controllers/tracker.ts
As I mentioned here https://github.com/Chocobozzz/PeerTube/issues/2826 , my instance is facing a kind of DDOS: hundreds of IPs are asking for unkwnown infoHash. I had to increase nginx worker_connections, as there are thousands of connections that timeout only after 30 minutes.
Moreover, the download traffic generates an upload traffic 4 times higher (so it can be very easy to DDOS the bandwidth).
And last, but not least, it generates GB of log files. 
So, in this PR, I added the ip for clients asking for unknownInfoshash, so we can add a rule in fail2ban.
Note: the IP is logged without taking into account CONFIG.LOG.ANONYMIZE_IP. The IP was already logged on this line without taking into account the config:
https://github.com/Chocobozzz/PeerTube/blob/435258ea3c17c10c7c2735075e59122956d45f …
=> Logging ip requesting unknown infoHash

client/src/app/+admin/plugins/plugin-list-installed/plugin-list-installed.component.html, client/src/app/+admin/plugins/plugin-search/plugin-search.component.html, client/src/app/+my-account/my-account-ownership/my-account-ownership.component.html, client/src/app/+my-account/my-account-subscriptions/my-account-subscriptions.component.html, client/src/app/+my-account/my-account-video-channels/my-account-video-channels.component.html, client/src/app/app.component.html, client/src/app/menu/menu.component.html, client/src/app/shared/channel/avatar.component.html, client/src/app/shared/channel/avatar.component.ts, client/src/app/shared/video/video-miniature.component.ts, client/src/app/videos/+video-watch/video-watch.component.html, client/src/assets/player/videojs-components/peertube-link-button.ts
This PR will improve a11y with short link title when needed.
Link title should not have verb like "go to" for screen readers.
More improving should be done with all the target="_blank" attribute on another PR with either (new window) in title/text or adding a new window icon with css :)
=> Remove uneccessary details to link titles

FAQ.md
Fixes 
> Project 'chocobozzz/PeerTube' was moved to 'framasoft/peertube/PeerTube'. Please update any links and bookmarks that may still have the old path.
warning on Framagit
=> Update framagit peertube link in FAQ

client/src/index.html
I updated the noscript tag and linked available third party applications for PeerTube, with both official doc link and the raw file because the documentation also requires JavaScript to be enabled.
Should we keep the 
> You can also develop your own as our code is open source and libre software under the <a href="https://github.com/Chocobozzz/PeerTube/blob/develop/LICENSE" target="_blank" rel="noopener">GNU AGPLv3.0</a> and documented on <a href="https://docs.joinpeertube.org/api-rest-reference.html">docs.joinpeertube.org</a>. 
part ?
=> link to third-party-application raw list in noscript

config/default.yaml, config/production.yaml.example, server/initializers/config.ts, support/docker/production/config/production.yaml
If database.name is set, we use it as the complete database name.
If unset, we use the "peertube"+database.suffix as the complete database
name.
Fixes #1620
=> Add database.name config option

support/doc/dependencies.md
Created section for CentOS 8 instructions as it deviates from CentOS 7
- There is no python binary that can be installed with a package so it must be symlinked
- Removed packages not needed from step 4
- Removed step concerning g++ as the version in CentOS 8 is usable
- Improved wording for Steps summary in both CentOS 8 and 7
=> Update CentOS insutructions in dependencies.md

client/src/app/app.component.scss, client/src/index.html, config/default.yaml, config/production.yaml.example, config/test-1.yaml, config/test-2.yaml, config/test-3.yaml, config/test-4.yaml, config/test-5.yaml, config/test-6.yaml, server/controllers/client.ts, server/initializers/config.ts, server/initializers/constants.ts, server/lib/client-html.ts, support/docker/production/config/production.yaml
This PR allows to customize main assets like logo, favicon and PWA icons, PWA manifest name and description :
~Add ability in the admin panel to upload a SVG / PNG logo and generate favicon - PWA icons.~
To test it the client must be built with `npm run clean:client` and `npm run dev:server`
=> Add ability to override client assets : logo - favicon - PWA icons - PWA manifest name and description

server/controllers/api/users/index.ts, server/lib/emailer.ts, server/lib/emails/password-reset/html.pug, server/lib/user.ts
=> Display username in password-reset mail

client/src/app/shared/shared-forms/markdown-textarea.component.scss
Since https://github.com/Chocobozzz/PeerTube/pull/2915 the maximized icon padding in markdown textarea was not correct.
Before: 
After:
=> correct maximized icon padding since new icons set implemented

client/src/sass/application.scss, client/src/sass/bootstrap.scss
Small PR which is more a visual fix.
It improves UX/UI nav transitions on desktop browsers where the vertical scrollbar is not floating over the body like touch devices do.
Now, when switching **from a vertical scrolled content to a non-scrolled content / opened modal view**, the vertical scroll will be disabled instead of hide on desktop browsers.
**This way, header (upload button and search input) and content won't be involuntarily moved horizontally to the right**.
=> disable vertical scroll instead of hide on desktop browsers

client/src/app/+admin/admin.component.scss, client/src/app/+admin/follows/followers-list/followers-list.component.html, client/src/app/+admin/follows/following-list/following-list.component.html, client/src/app/+admin/follows/video-redundancies-list/video-redundancies-list.component.html, client/src/app/+admin/moderation/abuse-list/abuse-list.component.html, client/src/app/+admin/moderation/video-block-list/video-block-list.component.html, client/src/app/+admin/plugins/plugins.component.html, client/src/app/+admin/plugins/plugins.component.scss, client/src/app/+admin/system/system.component.html, client/src/app/+my-account/+my-account-video-channels/my-account-video-channels.component.html, client/src/app/+my-account/my-account-history/my-account-history.component.html, client/src/app/+my-account/my-account-ownership/my-account-ownership.component.html, client/src/app/+my-account/my-account-subscriptions/my-account-subscriptions.component.html, client/src/app/+my-account/my-account-video-imports/my-account-video-imports.component.html, client/src/app/+my-account/my-account-video-playlists/my-account-video-playlists.component.html, client/src/app/+my-account/my-account-video-playlists/my-account-video-playlists.component.scss, client/src/app/+my-account/my-account-videos/my-account-videos.component.html, client/src/app/+my-account/my-account-videos/my-account-videos.component.scss, client/src/app/+my-account/my-account.component.scss, client/src/app/+videos/+video-edit/video-add.component.scss, client/src/app/shared/shared-main/misc/top-menu-dropdown.component.html, client/src/app/shared/shared-main/misc/top-menu-dropdown.component.scss, client/src/app/shared/shared-main/misc/top-menu-dropdown.component.ts, client/src/app/shared/shared-moderation/account-blocklist.component.html, client/src/app/shared/shared-moderation/server-blocklist.component.html, client/src/sass/application.scss, client/src/sass/bootstrap.scss, client/src/sass/include/_mixins.scss, client/src/sass/include/_variables.scss
Needs https://github.com/Chocobozzz/PeerTube/pull/2977 to update new icons.
This PR proposes to improve the navigation links effects : 
- ~Prefer changing text color instead of text bold when switching between active and non-active link to avoid to resize effects ;~ => use `opacity: 0.6` on non-active links
- Add transparent borders on non-active links to avoid involuntary resize between links or tabs ;
- ~Change color on hover event for tabs ;~
- ~Border-bottom black on hover event for links (sub-menu)~ ; => only `opacity: 1`
- Remove margin-top on active link (sub-menu) ; 
- Sub-menu fixed ;
_usefull on touchdevices_ 
- Improve Dropdown : active class on active link + remove hover open + close outside click only
_make sure the sub-menu is not too long horizontally - less confusing nav …
=> Improve navigation sub-menu and tabs effects

client/src/app/+videos/+video-watch/video-watch.component.html, client/src/app/+videos/+video-watch/video-watch.component.scss, client/src/app/+videos/+video-watch/video-watch.component.ts, client/src/app/shared/shared-main/account/avatar.component.html, client/src/app/shared/shared-main/account/avatar.component.ts
First stab at : https://github.com/Chocobozzz/PeerTube/issues/2987
fixes #2953
- No avatar channel and generic display name (Main *username* channel) channel :
*the big avatar and account name redirect to the account page*
- Generic display name (Main *username* channel) and a channel avatar is uploaded
*the small avatar is the channel avatar and redirect to the channel page*
- Display name channel and avatar channel customized
*back to regular display*
=> Hide generic channel display name and avatar on watch view

support/doc/api/openapi.yaml
httpie is great, but unfortunately it has a known limit of 512MB for file
uploads (jakubroztocil/httpie#452), and videos can often be larger than this.
curl doesn't have such a limit.
Additionally, switching examples to curl reduces the dependencies making them
more portable.
=> Switch examples to curl since httpie has a 512MB limit

client/src/app/+admin/admin.component.ts, client/src/app/+my-account/my-account.component.ts, client/src/app/+videos/+video-edit/video-add.component.html, client/src/app/+videos/+video-edit/video-add.component.scss, client/src/app/+videos/+video-edit/video-add.component.ts, client/src/app/core/auth/auth-user.model.ts, client/src/app/core/users/user.model.ts, client/src/app/menu/menu.component.html, client/src/app/menu/menu.component.ts, client/src/app/shared/shared-main/misc/top-menu-dropdown.component.html, client/src/app/shared/shared-main/misc/top-menu-dropdown.component.ts
When user video quota or daily upload limit are set to `None - no upload possible`, an alert should inform that upload is disabled for the account and the form view not displayed once clicked on the `Upload button` and accessing to `/videos/upload`.
This PR proposes a way to alert the user and hide the upload form in this case :
=> Add alert and hide upload view when no upload is possible

server/controllers/client.ts, server/lib/client-html.ts, server/models/video/video-playlist.ts, server/tests/client.ts
Fixes: https://github.com/Chocobozzz/PeerTube/issues/2989
Tests :
```bash
$ npm run build:server
$ NODE_ENV=test npm start
$ curl http://localhost:9000/videos/watch/playlist/:uuid
$ curl http://localhost:9000/accounts/:username
$ curl http://localhost:9000/video-channels/:name
```
=> Add fcbk open-graph and twitter-card metas for accounts, video-channels, playlists urls

client/src/app/+admin/follows/followers-list/followers-list.component.html, client/src/app/+admin/follows/following-list/following-list.component.html, client/src/app/+admin/follows/video-redundancies-list/video-redundancies-list.component.html, client/src/app/+admin/moderation/instance-blocklist/instance-account-blocklist.component.html, client/src/app/+admin/users/user-list/user-list.component.html, client/src/app/+my-account/+my-account-video-channels/my-account-video-channels.component.html, client/src/app/+my-account/my-account-ownership/my-account-ownership.component.html, client/src/app/+my-account/my-account-video-imports/my-account-video-imports.component.html, client/src/app/+my-account/my-account-video-playlists/my-account-video-playlists.component.html, client/src/app/+my-account/my-account-videos/my-account-videos.component.html, client/src/app/shared/shared-main/buttons/button.component.html, client/src/app/shared/shared-main/buttons/button.component.scss, client/src/app/shared/shared-main/buttons/delete-button.component.html, client/src/app/shared/shared-main/buttons/delete-button.component.ts, client/src/app/shared/shared-main/buttons/edit-button.component.html, client/src/app/shared/shared-main/buttons/edit-button.component.ts, client/src/app/shared/shared-moderation/account-blocklist.component.html, client/src/app/shared/shared-moderation/server-blocklist.component.html, client/src/app/shared/shared-moderation/user-moderation-dropdown.component.ts
- Add ability to hide label on `my-edit-button`, `my-delete-button`, `my-button`
- Replace native title of `my-edit-button`, `my-delete-button`, `my-button` by `ngbTooltip`
- Move actions tables on the left but for group actions (users view ...)
=> Improve (accessibility title) and move action-buttons on left in tables

client/src/app/shared/shared-main/misc/top-menu-dropdown.component.html
This PR reverts the recent proposition to close the dropdown sub-menu only on outside click and showing a background color on active links. 
Now, autoclose is back on click inside and outside and active class is removed, because this active effect class caused some blinking effect on the dropdown.
=> Revert user-menu dropdown active class on sub-menu and close outside-click

client/src/app/+my-account/+my-account-video-channels/my-account-video-channels.component.html, client/src/app/+my-account/+my-account-video-channels/my-account-video-channels.component.scss, client/src/app/+my-account/my-account-subscriptions/my-account-subscriptions.component.html, client/src/app/+my-account/my-account-subscriptions/my-account-subscriptions.component.scss, client/src/app/+my-account/my-account-video-playlists/my-account-video-playlists.component.html, client/src/app/+my-account/my-account-video-playlists/my-account-video-playlists.component.scss, client/src/app/+my-account/my-account-videos/my-account-videos.component.html, client/src/app/+my-account/my-account-videos/my-account-videos.component.scss, client/src/app/+my-account/my-account.component.ts, client/src/app/shared/shared-moderation/account-blocklist.component.html
fixes: https://github.com/Chocobozzz/PeerTube/issues/3030 and https://github.com/Chocobozzz/PeerTube/issues/3020
=> Fix regressions in my-account sub menu and sub titles

client/src/app/+admin/config/edit-custom-config/edit-custom-config.component.html, config/default.yaml, config/production.yaml.example, server/initializers/constants.ts, server/tests/api/server/config.ts
In addition to documenting a bit existing extensions, add `.wmv`, a missing mainstream container. Other containers added are either low-hanging fruits (3GPP, FLV replacement, OGG (`.ogg` can also be a video container), Sony/Panasonic formats which are also found in BluRay, `.nut` as ffmpeg/mplayer developed it).
=> add and document new additional video extensions supported at upload

client/src/sass/player/peertube-skin.scss
fixes: https://github.com/Chocobozzz/PeerTube/issues/3055
=> Do not display videojs poster when video is starting to avoid blinking effect

client/src/app/+admin/admin.component.scss, client/src/app/+my-account/my-account-settings/my-account-settings.component.html, client/src/app/+my-account/my-account.component.scss, client/src/app/app-routing.module.ts, client/src/app/app.component.ts, client/src/app/menu/menu.component.html, client/src/app/shared/shared-user-settings/user-video-settings.component.html, client/src/sass/application.scss
All links in the user dropdown-menu refered to `/my-account/settings` with an anchor `#video-settings`, does not scroll exactly to the the target element, plus when we are on my-settings all these links can't work properly since they have the same anchor.
It also handle the offset with the fixed sub-menu.
=> Add new anchors in my-settings and handle offset sub-menu height

client/src/app/+about/about.component.html, client/src/app/+about/about.component.ts, client/src/app/+admin/admin.component.html, client/src/app/+admin/admin.component.scss, client/src/app/+admin/admin.component.ts, client/src/app/+my-account/my-account.component.html, client/src/app/+my-account/my-account.component.scss, client/src/app/+my-account/my-account.component.ts, client/src/app/app.component.ts, client/src/app/core/wrappers/screen.service.ts, client/src/app/shared/shared-main/misc/top-menu-dropdown.component.html, client/src/app/shared/shared-main/misc/top-menu-dropdown.component.ts, client/src/sass/application.scss
fixes: https://github.com/Chocobozzz/PeerTube/issues/3061
This PR proposes to _unfixed_ the sub-menu when a broadcast-message is displayed.
It also brings a small refactor to improve the way we handle the offset of the content when the menu is fixed.
=> Disable fixed sub-menu with broadcast-message

client/src/app/+about/about-instance/about-instance.component.html, client/src/app/+about/about-instance/about-instance.component.scss
depends on : https://github.com/Chocobozzz/PeerTube/pull/3062
=> Add anchor links to about/instance

client/src/app/+admin/users/user-edit/user-create.component.ts, client/src/app/+admin/users/user-edit/user-edit.component.html, client/src/app/shared/shared-forms/form-validators/user-validators.service.ts, server/controllers/api/users/index.ts, server/middlewares/validators/users.ts, shared/models/users/user-create.model.ts
Required fix : https://github.com/Chocobozzz/PeerTube/issues/2970
=> Add channel name to create-user admin form

client/package.json, client/src/app/+videos/+video-watch/comment/video-comment-add.component.html, client/src/app/+videos/+video-watch/comment/video-comment-add.component.scss, client/src/app/+videos/+video-watch/comment/video-comment-add.component.ts, client/src/app/+videos/+video-watch/comment/video-comment.component.html, client/src/app/+videos/+video-watch/comment/video-comment.component.scss, client/src/app/+videos/+video-watch/comment/video-comment.component.ts, client/src/app/+videos/+video-watch/comment/video-comments.component.html, client/src/app/+videos/+video-watch/comment/video-comments.component.ts, client/src/app/core/renderer/markdown.service.ts, client/src/app/shared/shared-icons/global-icon.component.ts, client/src/app/shared/shared-main/misc/help.component.html, client/src/app/shared/shared-main/misc/help.component.scss, client/src/app/shared/shared-main/misc/help.component.ts, client/src/assets/images/misc/markdown.svg, client/src/sass/application.scss, client/yarn.lock, package.json, yarn.lock
- Hide mention of deleted comments without replies ;
- New delete and re-draft action on a comment **only on comments without replies** ;
- Move delete, delete and re-draft actions on options menu ;
- Add icons on delete, delete and re-draft and report actions in options menu ;
- Rename `Reply` value of add comment button to `Comment` **only for comment main thread textarea** ;
- Add Markdown help icon :
- Add uni-code emojis native display (depending on Operating System) https://apps.timwhitlock.info/emoji/tables/unicode.
=> Add ability to delete and re-draft a comment with no replies + markdown infos + unicode emojis

client/src/app/shared/shared-instance/instance-features-table.component.scss
this width caused this page to scroll because the minimum width was set to 330px and phones have less width than that. i have checked the same on peertube2.cpy.re using firefox inspect element responsive design mode.
This is my first pull request, please be gentle ;-)
=> removed minimum width css to fit mobile devices with lesser width

client/src/app/+my-account/my-account-settings/my-account-settings.component.html, client/src/app/app.component.ts, client/src/app/menu/avatar-notification.component.html, client/src/app/menu/avatar-notification.component.ts, client/src/app/menu/menu.component.html, client/src/app/menu/menu.component.ts, client/src/app/shared/shared-main/misc/top-menu-dropdown.component.html, client/src/app/shared/shared-main/misc/top-menu-dropdown.component.ts
Restore anchor scroll position on user-dropdown account settings active links : 
Scroll to top when sub-menu is fixed on active links :
=> Add restore scroll position on user-dropdown anchors links and scroll to top on active sub-menu links

client/src/app/app.component.ts, client/src/app/core/menu/menu.service.ts, client/src/app/core/routing/menu-guard.service.ts, client/src/app/core/wrappers/screen.service.ts, client/src/sass/bootstrap.scss
fixes: https://github.com/Chocobozzz/PeerTube/issues/3087
This PR changes the behaviour of the menu on touchscreens : 
- On all resolution open menu only by user, by default it's closed
- On opened menu, a content overlay is displayed and body scroll locked **to avoid the blinking detached menu effect** when scroll.
Also on modal opened (and only for touchscreens) body scroll is locked.
=> On touchscreens add content overlay for opened menu

client/src/app/+my-account/my-account-video-playlists/my-account-video-playlist-elements.component.scss, client/src/app/+videos/+video-watch/video-watch-playlist.component.html, client/src/app/+videos/+video-watch/video-watch-playlist.component.ts, client/src/app/+videos/+video-watch/video-watch.component.html, client/src/app/+videos/+video-watch/video-watch.component.ts, client/src/app/shared/shared-forms/timestamp-input.component.ts, client/src/app/shared/shared-main/angular/infinite-scroller.directive.ts, client/src/app/shared/shared-share-modal/video-share.component.ts, client/src/app/shared/shared-video-playlist/video-add-to-playlist.component.html, client/src/app/shared/shared-video-playlist/video-add-to-playlist.component.scss, client/src/app/shared/shared-video-playlist/video-add-to-playlist.component.ts, client/src/app/shared/shared-video-playlist/video-playlist-element-miniature.component.scss, client/src/app/shared/shared-video-playlist/video-playlist-element-miniature.component.ts, client/src/app/shared/shared-video-playlist/video-playlist.service.ts, server/controllers/activitypub/client.ts, server/controllers/api/video-playlist.ts, server/initializers/constants.ts, server/initializers/migrations/0530-playlist-multiple-video.ts, server/lib/activitypub/url.ts, server/middlewares/validators/videos/video-playlists.ts, server/models/video/video-playlist-element.ts, server/tests/api/check-params/video-playlists.ts, server/tests/api/videos/video-playlists.ts
See https://github.com/Chocobozzz/PeerTube/issues/3084
Remove constraints so a playlist can have multiple instances of a video.
Updated the video add to playlist dropdown:
* When a video is added in a playlist, we display an `+` icon
* On click, it opens the *advanced settings* pane where the user can update the timestamps of the video
* The user can also add more instances of the video in the playlist
* When the user opens the dropdown, the *advanced settings* pane is automatically opened if the playlist contains several instances of the video **or** if the video was added to the playlist with custom timestamps
=> Same video multiple times in the same playlist

client/src/app/+videos/+video-edit/video-add-components/video-import-torrent.component.html, client/src/app/+videos/+video-edit/video-add-components/video-import-url.component.html
tooltips on import pages showed "import mp4 file" when we can clearly import many more formats. This must have been put when we would have been only able to import mp4 files. Anyways, i have changed mp4 to say "media file" as we can import audios as well
=> import media tooltip improvement

README.md
openapi.yml link was broken on README.md
=> Fixed openapi.yml link url

support/doc/api/openapi.yaml
Fixed boolean types which were wrongly set as string, added missing downloadEnabled for `/videos/upload` and `/videos/imports` on openapi.yaml
=> Fix boolean types, add missing downloadEnabled on openapi.yaml 

package.json, server/helpers/ffmpeg-utils.ts, yarn.lock
ffmpeg seems to create some temporary files in the cwd. When PeerTube
is run in a read-only docker container, this causes all transcoding
to fail. As a workaround, we set the cwd to the configured tmp dir.
=> Fix transcoding errors in readonly docker containers

client/src/app/shared/shared-share-modal/video-share.component.html, client/src/app/shared/shared-share-modal/video-share.component.ts
It's very difficult to share the original URL for a video when you watch it on your
own instance while it's not from it but from a different instance. Right now when
you use the share UI you only can share a link so a person can watch it on your
own instance, this patch adds a checkbox to the share UI to share the origin URL
instead if needed.
=> Add possibility to share origin URL to video if it's not local

client/src/app/+videos/+video-watch/video-watch.component.html, client/src/app/+videos/+video-watch/video-watch.component.scss, client/src/app/+videos/+video-watch/video-watch.component.ts
this aims to solve https://github.com/Chocobozzz/PeerTube/issues/3167 and a separate issue where i found the warning about p2p sharing which is initially shown to all users does not show up correctly on mobile devices as is currently hidden. this pr aims to fix those things
@rigelk i was unable to add a link 
also, i have used the word "video" instead of "content" as was earlier because the word video is already used in the UI at multiple places like in share > embed> "display video title". if this isnt acceptable, i can change it back, just let me know.
=> changed video rating popover text with link to login page

client/src/app/+videos/+video-watch/comment/video-comment-add.component.html, client/src/app/+videos/+video-watch/comment/video-comment-add.component.scss, client/src/app/+videos/+video-watch/comment/video-comment-add.component.ts
Fix https://github.com/Chocobozzz/PeerTube/issues/3245
- Use CSS flex instead of a classic table to extend the columns on the full modal width and make it responsive ;
- Center the columns ;
- Populate the the markdown-it emoji list from object to array to avoid an alphabetical order of the keys.
=> Improve markdown-it emoji list column display

client/src/app/+videos/+video-watch/comment/video-comment.component.ts, client/src/app/+videos/+video-watch/comment/video-comments.component.ts
Fix https://github.com/Chocobozzz/PeerTube/pull/3261#issuecomment-723294546 
Fix #3260
=> Restore line feed before HTML rendering for markdown lists support in comments

.github/CONTRIBUTING.md
After cloning the PeerTube repo you should first `cd` into the PeerTube local repo before adding a remote, otherwise this will happen: 'fatal: not a git repository (or any of the parent directories): .git'
=> fix CONTRIBUTING.md command order

server/controllers/client.ts, support/doc/docker-traefik.md, support/nginx/peertube
In production client-overrides don't work with nginx because client assets were bypassed without considering client-overrides handled in PeerTube. 
- Fix https://github.com/Chocobozzz/PeerTube/issues/3292
- Also fixes a the doc for a docker-compose command with multiples compose files.
I tested it with production scripts, it may need more tests ? @rigelk ?
=> add client overrides to nginx configuration

README.md, support/nginx/peertube
This PR refactors the Nginx configuration for the following points:
- update tls version to include 1.3 by default. so far it was not included by default to make room for previous versions of Nginx, but since 2018 Debian stable has included Nginx in version 1.14.1, and tls 1.3 is available since Nginx 1.13.0.
- clearly indicate that new minimum required version.
- update outdated ssl_ciphers to remove cipher required to support android 4.4, since that version is unsupported since March 2020.
- reordered configuration in sections for easier maintenance: performance optimizations are separated from the vital application/websocket parts.
- move parts that always require manual configuration at the top: peertube host and server name, use server_name 
- move peertube host to a more flexible …
=> refresh nginx config and optimize delivery

client/src/app/shared/shared-forms/markdown-textarea.component.ts
- Memorize scroll position after maximized the markdown textarea, caused to the fixed position of the main component ;
- Disable auto-focus of the markdown textarea when maximized on touchscreens that may move up and hide the textarea accidentality.
Fix https://github.com/Chocobozzz/PeerTube/issues/3322
Maximize and unmaximize a texteara when body scrolled down in Administration > Configuration > Basic configuration
=> Memorize scroll position after maximized textarea / disable auto-focus on touchscreens

config/default.yaml, config/production.yaml.example, server/helpers/youtube-dl.ts, server/initializers/config.ts
It seems YouTube does not like ipv6 clients (HTTP Error 429). This extra option works around that.
=> default youtube-dl to use ipv4

client/src/app/+my-account/my-account-settings/my-account-notification-preferences/my-account-notification-preferences.component.scss
Fix notifications preferences column width in `/my-account/settings#notifications`
=> fix user preferences column width for notifications table

client/src/app/shared/shared-main/account/actor-avatar-info.component.html, client/src/app/shared/shared-main/account/actor-avatar-info.component.ts, server/helpers/ffmpeg-utils.ts, server/helpers/image-utils.ts, server/initializers/constants.ts, server/lib/avatar.ts
- Add max resolution 192x192 (after resize) in tooltip avatar upload
- Add gif support for avatar with **FFmpeg process**
Gif support only : https://github.com/Chocobozzz/PeerTube/issues/3299
~~- [ ] 👍 yes, I added tests to the test suite~~ Didn't found any unit test for Image processing
I just live tested, does it need unit test @Chocobozzz  ?
=> Add pixel size to tooltip and gif support with FFmpeg for avatar upload

client/src/app/+signup/+register/register-step-user.component.html, client/src/app/+signup/+register/register.component.scss, client/src/sass/include/_mixins.scss
updated the desired changes in registration form. now it should be 100% width on reasonable length URLs 
@rigelk please have a look at this. i think i managed to get what you were asking
**Self-test configuration**:
* NodeJS version: 
* Viewport sizes: 
* Browser name/version:
=> adjust registration form width on mobile

support/doc/api/openapi.yaml
`/users/me/history/videos` and `/users/me/history/videos/remove` were missing in openapi docs, I added them!
No related issue. just found these API endpoints were missing.
=> add My History API to openapi

client/src/app/+videos/+video-watch/video-watch.component.html, client/src/app/+videos/+video-watch/video-watch.component.ts, client/src/app/shared/shared-video-miniature/video-miniature.component.html, client/src/app/shared/shared-video-miniature/video-miniature.component.ts
add title for video-watch and video-miniature to see the details of numbers of views
Add information about the exact view of a video or live
fixes #3173
I asked a question on the issue about the translation, if you can help me :) 
https://github.com/Chocobozzz/PeerTube/issues/3173#issuecomment-732396928
=> add title attribute for exact view counters

client/src/app/shared/shared-forms/dynamic-form-field.component.html, shared/models/plugins/register-client-form-field.model.ts, support/doc/plugins/guide.md
:sparkles: Add input-password to edit sensitive information without displaying content.
Funded by @Monogramm.
* Fix #3375: Add input-password type
=> Add input-password type

client/src/app/+about/about-instance/about-instance.component.html, client/src/app/+about/about-instance/about-instance.component.ts, client/src/app/+admin/config/edit-custom-config/edit-custom-config.component.html, client/src/app/shared/shared-instance/instance.service.ts
This PR introduces Markdown formatting in additional fields of the instance's "About" page.
It replaces plain-text textareas in the admin configuration by `my-markdown-textarea` as well as adds the `<my-help helpType="markdownText"></my-help>` to all of them.
It also registers the missing fields into `instance.service.ts` so that their content gets rendered as Markdown.
Resolves https://github.com/Chocobozzz/PeerTube/issues/3368.
Since my computer is a bit of a potato, I can't efficiently run Docker on it. Therefore, I developed all of that on Gitpod.
The "new" code reuses the same "code" that previously existed. It was just a matter of tweaking some HTML tags and adding a few fields in `instance.service.ts`. I tested the code by running a dev PeerTube instance and modifying the "config" …
=> Added Markdown formatting in all the fields of the "About" page

client/src/app/menu/menu.component.scss, client/src/sass/application.scss
Fix hardcoded colors preventing correct theming.
Funded by @Monogramm.
This PR will fix themes displays, like listed in https://framagit.org/framasoft/peertube/official-plugins/-/issues/21 of [peertube-theme-dark](https://framagit.org/framasoft/peertube/official-plugins/-/tree/master/peertube-theme-dark).
WIth dark theme:
* ![image](https://user-images.githubusercontent.com/6967675/100478741-6f245800-30ec-11eb-8b75-b80df71cc2cd.png)
* 
With default theme:
* 
*
=> Fix themes colors by using SCSS variables

server/initializers/constants.ts
displayName does not exist in VideoPlaylistModel, the correct field is `name`
=> Fix sort fields  on Video Playlists

client/src/app/+my-library/my-ownership/my-accept-ownership/my-accept-ownership.component.html, client/src/app/+my-library/my-ownership/my-accept-ownership/my-accept-ownership.component.ts
**This is a draft as the implementation it introduces must be discussed.**
Per request in #2240, I've slightly changed the select form in `my-accept-ownership.component.html` so that the first element of `videoChannels` is automatically selected. This, however, **occurs regardless of the amount of channels an account has**. This is the behavior I want to discuss with you. Should it remain as is, or should I refactor this PR to follow more closely the request of #2240?
Secondly, I had to change the `disable` condition of the "Accept" button. While the aforementioned change somehow worked fine if an account had multiple channels, the "Accept" button would remain greyed out if the account only had one channel.
Resolves https://github.com/Chocobozzz/PeerTube/issues/2240
I don't know if tests …
=> Select first available channel when accepting ownership change

support/docker/gitpod/Dockerfile
PeerTube's Gitpod dev image still uses Node.js 10, while [upstream]() was updated to Node.js 12.
The reason is that no change has been made to the Dockerfile in a while.
Adding a trivial change invalidates & rebuilds the dev image, and I've also added a comment to explain why.
=> Trigger a Gitpod dev image rebuild (in order to get upstream's Node.js 12 upgrade)

client/src/app/+signup/+register/custom-stepper.component.html, client/src/app/+signup/+register/register-step-user.component.html, client/src/app/+signup/+register/register-step-user.component.ts, client/src/app/+signup/+register/register.component.html, client/src/app/+signup/+register/register.component.ts
When default upload quota is set to 0, the channel step in the registration will be hidden, as proposed in #782 
closing #782 
relates #2805 
I couldn't find any appropriate way to add tests since there's no unit tests for the client and the tests in `server/tests/client.ts` seems to be on a higher lever than this feature.
=> register: hide channel step if upload quota is 0

client/src/assets/player/p2p-media-loader/p2p-media-loader-plugin.ts, client/src/assets/player/peertube-videojs-typings.ts, client/src/assets/player/videojs-components/p2p-info-button.ts, client/src/assets/player/webtorrent/webtorrent-plugin.ts
This PR implements #3384 with the changes @Chocobozzz suggested in https://github.com/Chocobozzz/PeerTube/issues/3384#issuecomment-737112057. Namely:
* adding a `source` field in `PlayerNetworkInfo`
* adding the requested information in `subDivWebtorrent.title` (from `p2p-info-button.ts`) **if** the server uses HLS.
WebTorrent is seemingly not able to tell the difference between the server and other peers, hence why it's left out of that PR.
Resolves https://github.com/Chocobozzz/PeerTube/issues/3384
=> Added 'total downloaded' from server and peers in the player

.gitpod.yml, support/docker/gitpod/Dockerfile
Fixes https://github.com/gitpod-io/gitpod/issues/2429
> Unable to boot a Workspace : fails at "Building Workspace Image"
---
Solution: https://github.com/gitpod-io/gitpod/issues/2429#issuecomment-739238805
> I think I know what the problem is. PeerTube's Gitpod Dockerfile attempts to initialize a PostgreSQL database:
> 
> https://github.com/Chocobozzz/PeerTube/blob/95bd9515b86e577033d9929c829c77c0df761acf/support/docker/gitpod/Dockerfile#L15
> 
> For some reason, this now fails with "Permission denied", when `pg_start` tries to create `/workspace/.pgsql/data` with `mkdir -p`:
> 
> https://github.com/gitpod-io/workspace-images/blob/c9896cde76e0698b1ed1b93ad464d77f87dd96e6/postgres/Dockerfile#L13
> 
> Probably user `gitpod` is not authorized to create directories under `/`.
> 
> However, …
=> Fix PostreSQL initialization for Gitpod

client/src/assets/player/p2p-media-loader/hls-plugin.ts
According to hls.js docs `hls.destroy()` should be called
https://github.com/video-dev/hls.js/blob/master/docs/API.md#final-step-destroying-switching-between-streams
I think it's a bit fussy to create a unit test just to verify this, but if you want to I'll add one.
=> hls-plugin: destroy hls upon third err

client/src/assets/player/webtorrent/webtorrent-plugin.ts
This PR shouldn't change any functionality, but just give a more clear error message when `videoFiles`
#3412 
1) Start the dev server
1) Start a video
1) Verify nothing is broken
=> WebTorrent Plugin: Clearify error message

.github/CONTRIBUTING.md
Add parallel as a dependency in contribution docs,
Closes #3405
=> docs(contributing): add parallel as dependency

server/controllers/api/accounts.ts, server/controllers/api/video-channel.ts, server/tests/fixtures/peertube-plugin-test/main.js, server/tests/plugins/filter-hooks.ts, shared/models/plugins/server-hook.model.ts
`filter:api.videos.list.*` hooks weren't triggered when listing an accounts videos. It's still not working for `/me/videos` since I don't know how to solve it there. I
1) Visit an accounts videos page (ie /accounts/root/videos) and verify it's not broken
1) Install a plugin that hooks `filter:api.videos.list.result` and verify it works (for example https://www.npmjs.com/package/peertube-plugin-sort-originally-published-at)
=> server accounts/videos: trigger filter hook

server/controllers/plugins.ts, server/middlewares/oauth.ts, server/tests/fixtures/peertube-plugin-test-five/main.js, server/tests/plugins/plugin-router.ts
* When creating custom routes with plugins, let the plugin author check if the user is authenticated or not.
* `authenticate` middleware now sets `res.locals.authenticated` to `true` upon successful authentication.
=> add optional authentication for plugin routes

server/lib/client-html.ts, server/models/account/account.ts, server/models/video/video-channel.ts, server/tests/client.ts, shared/extra-utils/server/servers.ts
The local URL was used instead of the original url
The local URL was used instead of the original url
Previously fixed in https://github.com/Chocobozzz/PeerTube/issues/1539
Added a test to check but didn't manage to run them, so they're all yours.
=> Set canonical link to original video/playlist url

client/src/app/+admin/config/edit-custom-config/edit-custom-config.component.html
>  e.g. is short for exempli gratia, a Latin phrase that means “for the sake of example.” 
> ...
>  I.e.’s Latin origin is the phrase id est, which translates to English as “that is to say” or “in other words.”
https://www.grammarly.com/blog/know-your-latin-i-e-vs-e-g/
=> Fix typ in admin config

server/lib/notifier.ts
When sending an abuse message and the sender is the only moderator or is the reporter, the notification sending fails.
Before calling `notify` a check is done to verify that we really have someone to notify.
Closes #3445
1) Create a video with user1
1) Report the video with admin1
1) Send a abuse report message from admin1 to user1
=> Fix sending notification upon abuse report message

client/src/standalone/videos/embed.html, client/webpack/webpack.video-embed.js, server/lib/client-html.ts
* Add the custom CSS to video embed HTML page.
* Add a CSS class to the body element to make it easier to target.
* Set HTML title at embed page to the instance name.
closes #3420
1) Set `.standalone-video-embed { background: green; } .standalone-video-embed #video-wrapper { display: none; }` as custom CSS.
1) Set a custom name for your PeerTube instance.
1) Copy the iframe target for an embed tag and visit the page.
1) Watch green.
=> Video embed page: Inject custom CSS and set page title

server/lib/emailer.ts, server/lib/emails/abuse-new-message/html.pug, server/lib/emails/abuse-state-change/html.pug, server/lib/emails/account-abuse-new/html.pug, server/lib/emails/common/base.pug, server/lib/emails/contact-form/html.pug, server/lib/emails/password-create/html.pug, server/lib/emails/password-reset/html.pug, server/lib/emails/verify-email/html.pug, server/lib/emails/video-abuse-new/html.pug, server/lib/emails/video-comment-abuse-new/html.pug
* Instead of communicating the hostname to the user in emails, show the instance name.
* It's not always that the end user knows that he's using a PeerTube platform, therefore it can be confusing when receiving an email stating "Welcome to PeerTube", etc.
* Sometimes the instance name is linked to the instance and sometimes not.
* It can be hard to read the email when the full link text is shown in the middle of the email. Putting it on bottom should make the email more readable.
* The video blacklisted/unblacklisted contains a link that's not clickable (it just prints the link code).
* Printing the video name in the subject can result in very long subjects.
Partially solves #3392
1) Login as root.
1) Configure email verification upon user registration.
1) Configure that you'll get an …
=> Make emails more user friendly

server/tests/cli/peertube.ts, server/tools/peertube-auth.ts
**The Solution:**
I have hardened `auth add` by stripping out everything from the third '/' to the end of the instance URL.
**The Problem:**
When adding an authorization for the peertube-cli, before this commit you could not have anything after the domain_name:port.
For instance, if there was a trailing / in your instance URL, before this commit it will always fail with
expected 200 "OK", got 404 "Not Found".
It took me over 20 minutes to figure out that this was the problem.
* Issue #3091: Peertube CLI auth got forbidden
* Issue #3520: Accept trailing slash with `peertube auth add`
Please describe the tests that you ran to verify your changes.
I attempted to run the entire test suite, but after many failed starts and one really long one, I cancelled the run after it had been going 37+ …
=> cli `auth add`: do not fail with extraneous characters

client/src/main.ts, client/src/ngsw-config.json, scripts/build/client.sh
Registers the ng service worker. I guess the asset names has changed since `ngsw-config.json` was written, therefore I just switched just to wildcard. 
Closes #296
Open up DevTools in Brave and check in Network tab to see that JS and CSS assets are fetched via service worker.
=> Register service worker

client/src/app/+my-account/my-account-settings/my-account-settings.component.html, client/src/app/+my-account/my-account-settings/my-account-settings.component.ts, client/src/app/+my-library/+my-video-channels/my-video-channel-edit.component.html, client/src/app/+my-library/+my-video-channels/my-video-channel-edit.ts, client/src/app/+my-library/+my-video-channels/my-video-channel-update.component.ts, client/src/app/core/users/user.model.ts, client/src/app/core/users/user.service.ts, client/src/app/shared/shared-main/account/account.model.ts, client/src/app/shared/shared-main/account/actor-avatar-info.component.html, client/src/app/shared/shared-main/account/actor-avatar-info.component.scss, client/src/app/shared/shared-main/account/actor-avatar-info.component.ts, client/src/app/shared/shared-main/video-channel/video-channel.model.ts, client/src/app/shared/shared-main/video-channel/video-channel.service.ts, client/src/sass/include/_mixins.scss, server/controllers/api/users/me.ts, server/controllers/api/video-channel.ts, server/lib/activitypub/actor.ts, server/lib/avatar.ts
This PR adds a delete route for account avatars and one for channel avatars.
I should add tests to the test suite.
No avatar:
With an avatar:
=> add ability to remove one's avatar for account and channels

client/src/app/+admin/config/edit-custom-config/edit-custom-config.component.ts, config/default.yaml, config/production.yaml.example, config/test.yaml, server/controllers/api/config.ts, server/helpers/ffprobe-utils.ts, server/initializers/checker-before-init.ts, server/initializers/config.ts, server/middlewares/validators/config.ts, server/tests/api/check-params/config.ts, server/tests/api/live/live-constraints.ts, server/tests/api/live/live-permanent.ts, server/tests/api/live/live-save-replay.ts, server/tests/api/server/config.ts, server/tests/api/server/stats.ts, server/tests/api/videos/audio-only.ts, server/tests/api/videos/video-hls.ts, server/tests/cli/create-transcoding-job.ts, shared/extra-utils/server/config.ts, shared/models/server/custom-config.model.ts, shared/models/videos/video-resolution.enum.ts, support/doc/api/openapi.yaml, support/docker/production/config/custom-environment-variables.yaml
resolves #3500. The CI harness is supposedly enough to catch mistakes but I might need to add 1440p videos to it.
=> add support for 1440p (Quad HD/QHD/WQHD) videos

config/default.yaml, config/production.yaml.example, server.ts, server/initializers/config.ts, support/docker/production/config/custom-environment-variables.yaml
Allow administrator to disable logging of ping requests on `/api/v1/ping`.
This is disabled by default, but can be enabled by setting `log.log_ping_requests` to `true` (or the `PEERTUBE_LOG_PING_REQUESTS` environment variable in Docker).
Implements #3544
Not sure how I can implement unit test for that.
=> Allow administrator to disable logging of ping requests

client/src/app/+my-library/my-history/my-history.component.html, client/src/app/+my-library/my-history/my-history.component.scss, client/src/app/+my-library/my-history/my-history.component.ts, client/src/app/+my-library/my-subscriptions/my-subscriptions.component.html, client/src/app/shared/shared-main/users/user-history.service.ts, server/controllers/api/users/my-history.ts, server/middlewares/validators/user-history.ts, server/models/account/user-video-history.ts, server/models/video/video.ts, server/tests/api/videos/videos-history.ts, shared/extra-utils/videos/video-history.ts, support/doc/api/openapi.yaml
Adds support for a `search` query parameter and adds a corresponding search field within the history interface.
Some interface corrections applied to the history interface.
related to meta #3486
=> Allow user to search through their watch history

server/helpers/ffmpeg-utils.ts, server/initializers/constants.ts
Split live and vod transcoding niceness values to reflect their priorities.
Closes https://github.com/Chocobozzz/PeerTube/issues/3583
=> higher priority for live transcoding compared to vod transcoding

support/nginx/peertube
5f59cf077fd9f9c0c91c7bb56efbfd5db103bff2 introduced requirements on additional nginx modules:
nginx: [emerg] "aio threads" is unsupported on this platform in /etc/nginx/sites-enabled/peertube:247
https://nginx.org/en/docs/http/ngx_http_core_module.html#aio
nginx: [emerg] unknown directive "deny" in /etc/nginx/sites-enabled/peertube:83
https://nginx.org/en/docs/http/ngx_http_access_module.html
Note: Not sure how you differentiate between what is a `STANDARD` and an `OPTIONAL` HTTP MODULE in your documentation, so I put `AIO Multithreading` to `STANDARD` as it's a core module and `access` to `OPTIONAL` however when judging on what is required for the PeerTube included nginx config to actuall work there are no real `OPTIONAL` modules as every mising one will throw an error(?).
=> Mention additional nginx modules required since #3313

client/src/app/+accounts/account-search/account-search.component.ts, client/src/app/+accounts/accounts-routing.module.ts, client/src/app/+accounts/accounts.component.html, client/src/app/+accounts/accounts.component.ts, client/src/app/+accounts/accounts.module.ts, client/src/app/shared/shared-main/misc/index.ts, client/src/app/shared/shared-main/misc/simple-search-input.component.html, client/src/app/shared/shared-main/misc/simple-search-input.component.scss, client/src/app/shared/shared-main/misc/simple-search-input.component.ts, client/src/app/shared/shared-main/shared-main.module.ts, client/src/app/shared/shared-main/video/video.service.ts, client/src/sass/include/_mixins.scss, server/controllers/api/accounts.ts, server/middlewares/validators/videos/videos.ts, server/tests/api/users/users-multiple-servers.ts, shared/extra-utils/videos/videos.ts
Adds a search icon that on click reveals a search input. Upon validating the search (pressing enter), a listing of videos is taken and filtered with the search terms.
related to meta #3486
=> Allow users/visitors to search through an account's videos

client/src/app/+admin/system/jobs/jobs.component.html, client/src/app/+admin/system/jobs/jobs.component.scss, client/src/app/+admin/system/jobs/jobs.component.ts, server/controllers/api/jobs.ts, server/controllers/api/videos/index.ts, server/helpers/database-utils.ts, server/helpers/video.ts, server/initializers/constants.ts, server/lib/job-queue/handlers/video-file-import.ts, server/lib/job-queue/handlers/video-import.ts, server/lib/job-queue/handlers/video-transcoding.ts, server/lib/job-queue/job-queue.ts, server/lib/video.ts, server/models/video/video.ts, server/tests/api/videos/video-transcoder.ts, shared/models/server/job.model.ts
Add priority to transcoding jobs
(1 = highest priority)
100 for new resolutions
10 for original file optimization
Add a malus for transcoding jobs depending on how many uploads the user did in the
last 7 days
Fixes https://github.com/Chocobozzz/PeerTube/issues/1192 and https://github.com/Chocobozzz/PeerTube/issues/3596
=> Fair transcoding jobs

client/src/app/+accounts/accounts.component.ts, client/src/app/+page-not-found/page-not-found.component.html, client/src/app/+page-not-found/page-not-found.component.ts, client/src/app/+video-channels/video-channels.component.ts, client/src/app/+videos/+video-watch/video-watch.component.ts, client/src/app/core/rest/rest-extractor.service.ts, client/src/app/shared/shared-main/auth/auth-interceptor.service.ts
Outside of components using `LoginGuard`, we can detect which objects require to be logged in based on their return code, which `AuthInterceptor` can help us redirect. This is especially useful for internal videos, as mentioned in https://framacolibri.org/t/avoir-le-bouton-de-login-sur-lerreur-404/10761.
This is done client-side only, relying on existing server codes, so no tests were added to the CI harness. However, I tested manually for internal, private and blocked videos.
=> redirect to login on 401, display 403 variant

support/nginx/peertube
The `proxy_ignore_client_abort` flag specifies whether nginx will
monitor possible connection close while waiting for an upstream
server response. If an error occurs while sending a response, the
connection will be closed regardless of the flag, much like if
there where no nginx at all.
fixes #3484
=> add `proxy_ignore_client_abort` flag to Nginx conf

client/src/app/shared/shared-main/angular/number-formatter.pipe.ts, client/src/app/shared/shared-video-miniature/video-download.component.ts
[Some countries](https://en.wikipedia.org/wiki/Decimal_separator#Countries_using_decimal_comma) are using comma as decimal separator.
https://caniuse.com/internationalization
1) Switch language to Swedish.
1) See that decimal points for video views are comma.
=> localize decimal separator in video miniatures

client/src/index.html, client/src/sass/application.scss
This should improve the clarity of the message and make it easy to
understand what the problem is at a glance.
- Clearly show that the page is PeerTube, without having to read the whole prose
- Clearly show that the problem is JavaScript, without having to read the whole prose
- Reorganise suggestions into a bullet list
I figured this was trivial enough that I didn't need to open an issue for discussion first. Just let me know if you have comments :)
Yes, manually, by loading the HTML file in a browser with scripts disabled, and checking that the page looked like what I wanted.
=> Rewrite prose for JavaScript disabled message

client/src/app/+admin/config/edit-custom-config/edit-custom-config.component.html, client/src/app/+videos/video-list/trending/video-trending-header.component.ts, client/src/app/core/server/server.service.ts, client/src/app/shared/shared-icons/global-icon.component.ts, client/src/assets/images/feather/award.svg, config/default.yaml, config/production.yaml.example, server/initializers/constants.ts, server/models/video/video-query-builder.ts, server/models/video/video.ts, server/tests/api/check-params/config.ts, server/tests/api/server/config.ts, server/tests/api/videos/single-server.ts, shared/extra-utils/server/config.ts, shared/models/videos/video-sort-field.type.ts
inspired from https://www.reddit.com/r/changelog/comments/7spgg0/best_is_the_new_hotness/
this implementation only adds freshness, and doesn't personalize based
on subscribed communities yet.
None.
Should I merge this with `hot` sort?
Should I only display `best` sort for logged-in users?
=> add best trending strategy based on Reddit's best

support/doc/dependencies.md
Removes outdated dependency libvips from freebsd instructions
=> Remove vips dependency from FreeBSD instructions

client/src/assets/player/peertube-player-manager.ts
* Stricten _fullscreen_ hotkey to only be targeted when shift, ctrl, alt and meta key isn't pressed.
* Stricten _increase/decrease playback rate_ hotkey to only be targeted when shift, ctrl, alt and meta key isn't pressed.
* Stricten _frame by frame_ hotkey to only be targeted when ctrl, alt and meta key isn't pressed.
* Remove VLC mimic when using arrow keys to instead popular video web apps.
fixes #2810
1) Play a video and try hotkeys listen under _Description_.
=> Tighten hotkeys definitions

support/doc/dependencies.md
The "Production guide" states to use `wget` to download the latest version of the Peertube client, and it was not included in the `apt install` dependency list
=> Add missing dependency to Debian / Ubuntu section

client/src/app/shared/form-validators/video-validators.ts
Fix titles do not trim leading and trailing spaces
fixes #3623 
- [x ] 🙅 no, because they aren't needed
1. Upload/Edit video properties
2. Type a leading space or a trailing space
=> Fix titles do not trim leading and trailing spaces

scripts/upgrade.sh
fix upgrade.sh after 3.1.0
I just upgraded to v3.1.0-rc.1, but the upgrade got interrupted (I didn't have a symlink from python3 to python, which the youtube-dl installer expected).
I ran the upgrade script again and only got the following error:
> /var/www/peertube/versions/peertube-v3.1.0-rc.1/node_modules/js-yaml/index.js:10
>     throw new Error('Function yaml.' + from + ' is removed in js-yaml 4. ' +
>     ^
> 
> Error: Function yaml.safeLoad is removed in js-yaml 4. Use yaml.load instead, which is now safe by default.
>     at Object.safeLoad (/var/www/peertube/versions/peertube-v3.1.0-rc.1/node_modules/js-yaml/index.js:10:11)
>     at [eval]:1:32
>     at Script.runInThisContext (vm.js:120:18)
>     at Object.runInThisContext (vm.js:309:38)
>     at Object.<anonymous> …
=> use yaml.load instead of yaml.safeLoad in upgrade script

client/src/sass/bootstrap.scss
Fix long word on modal.
Fixes #3492 
- Tested in chrome. With this video: https://videos.lukesmith.xyz/videos/watch/e0f5a4d7-070d-4a03-aca4-3d898b5c5002
=> fix: long text on modals

client/src/app/+accounts/accounts.component.html, client/src/app/+video-channels/video-channels.component.html, client/src/app/shared/shared-forms/input-toggle-hidden.component.html, client/src/app/shared/shared-video-miniature/video-download.component.html, client/src/sass/bootstrap.scss
1) Replaces `icon-copy` with `icon-duplicate` since the latter is more common (https://www.google.com/search?q=copy+icon&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiI1OS1rpLvAhVpkosKHfrTBAQQ_AUoAXoECBQQAw&biw=1650&bih=819)
1) Adds "Copy" text next to the icon when used in input fields.
* #3810 
1) Visit a video page and open share modal.
1) Visit a video page and open download modal.
1) Visit an account page and check "copy account name" icon.
1) Visit a video channel page and check "copy channel name" icon.
=> Change copy icon

client/src/app/shared/shared-video-miniature/video-download.component.ts
By setting direct download as default method users with low tech skills can just click "Download" and it works as they expect. Whilst users that want to use torrent probably also are more technological skilled and therefore more comfortable in the UX and can easily switch to torrent if they'd like.
Relates to #3810 
1) Go to a video watch page.
1) Open download modal.
1) See that direct dl is checked as default.
=> Set direct download as default download method

client/src/assets/player/peertube-player-manager.ts
Option to set playback speed to 1.75
closes https://github.com/Chocobozzz/PeerTube/issues/3881
=> Add 1.75 option to playback rates

scripts/upgrade.sh
Fixes so that the upgrade script is using the `database.name` config if it's set.
1) Copy line 34-47 to the top of upgrade.sh and add `echo $PGPASSWORD` to see the value.
1) Run script and verify output.
1) Set `database.name` in config.
1) Run script and verify output.
=> Use database.name config value in upgrade script

client/src/app/shared/shared-video-miniature/video-download.component.html, client/src/app/shared/shared-video-miniature/video-download.component.scss, client/src/app/shared/shared-video-miniature/video-download.component.ts
* Resolution is switched with tabs instead of select list.
* Metadata is collapsed by default.
* Solves a bug: previously the metadata wasn't updated when choosing a resolution for the second time (check the last commit).
Closes #3810 
1) Visit a video that has subtitles and multiple resolutions.
1) Open Download modal.
1) Switch between video and subtitle.
1) Switch between resolutions.
=> Show less information in download modal

support/docker/production/config/custom-environment-variables.yaml
When enabling hls, one might want to disable webtorrent, so exposing it in the OS variable config
Related to our work on #3864
=> [support/docker] expose webtorrent setting in os variable settings

client/src/app/+videos/+video-watch/video-watch.component.ts, client/src/app/app.component.ts, client/src/assets/player/peertube-player-local-storage.ts, client/src/assets/player/peertube-player-manager.ts, client/src/assets/player/peertube-plugin.ts, client/src/assets/player/peertube-videojs-typings.ts, client/src/standalone/videos/embed.ts
Stores the current video duration in local storage for non-logged in users so that they can go back to a video and continue where they ended.
Upon app init a check is done to cleanup old durations.
closes #3866
1) Logout.
1) Watch a video for a few seconds.
1) Reload the page.
1) Edit the local storage and change the date in `peertube-videojs-video-watch` to a date more than 31 days back.
1) Reload the page.
1) See that the duration has been cleared.
=> Resume videos for non-logged in users

client/src/app/+videos/+video-watch/video-watch.component.scss
This removes the unnecessary black border/space above and below the video in normal player mode (if browser window is wide). It's achieved by further precising the aspect ratio 16/9 which is not just 1.7, but ~1.777777778. Therefore the video control take a little less vertical space and a 16/9 video fits perfectly into the same space. (see Screenshots below)
none AFAIK
visual difference can be seen on Screenshots below
| before | after |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/22591354/113494210-9221a700-94e6-11eb-9a11-94d36175cb13.png) | ![image](https://user-images.githubusercontent.com/22591354/113494219-a4034a00-94e6-11eb-83fb-64a65c637a0c.png) |
=> remove unnecessary black border above and below video in player

client/src/app/menu/menu.component.ts, client/src/app/shared/shared-instance/instance-features-table.component.html, client/src/app/shared/shared-instance/instance-features-table.component.ts, client/src/app/shared/shared-main/peertube-modal/index.ts, client/src/app/shared/shared-main/peertube-modal/peertube-modal.service.ts
Fixes #2576.
In the dev environment, open the About page and click on "can be redefined by the users". The expected result is that the settings dialog opens.
=> Minimal PeertubeModalService to open settings from "can be redefined..."

client/src/sass/ng-select.scss
Removed the use of `!important` that caused this issue, and specified rules more in line with `theme.default.css` to minimize overrides and unnecessary rules to ensure tag input fields do not have excessive padding. Ensured entered tags have a `3px` margin on the left to maintain their positioning (because `.ng-input` gets `3px` padding by default already).
Fixes #3915.
Visually inspected the following relevant input fields in Firefox and a Chrome-based browser (screenshots below, in order listed):
- Advanced search tag inputs
- Video (metadata) editing tag input
- Transcoding configuration inputs (for which 149e4cc, which contained the CSS rule with `!important` seemed to be intended)
=> Reducing tag input excessive padding; fixes #3915

client/src/app/+my-library/my-videos/my-videos.component.html, client/src/app/+my-library/my-videos/my-videos.component.scss
Corrected minor UI inconsistency in spacing around "Sort By" for narrow screens. 
Fixes #3936.
Visual inspection in Firefox on Linux and Bromite on Android.
=> correct inconsistency in spacing "Sort By" for narrow screens

client/src/app/app.component.scss, client/src/app/header/search-typeahead.component.scss
Fixed the hamburger menu button disappearing on (physically) narrow screens through CSS tweaks.
Fixes #3199.
Resized the browser window to be sufficiently narrow to reproduce #3199 and added scaling to the search field to make it exceedingly unlikely that the hamburger menu button will disappear. It will still disappear for screen widths under `160px`, but at that point other portions of the UI need work as well; at `184px` and up, it is present without being scaled down, and the search field is barely usable at that point anyway.
=> Fixing disappearing hamburger menu for narrow screens

.gitignore, client/src/app/+videos/+video-watch/video-watch.component.html, client/src/app/+videos/+video-watch/video-watch.component.ts
Removes the pausing of video upon modal open.
Closes #3816 
1) Start a video.
1) Open share modal.
1) Open download modal.
1) Open some other modal from the action menu.
=> Don't pause video upon modal open

server/helpers/ffmpeg-utils.ts, server/lib/video-transcoding-profiles.ts, server/tests/cli/print-transcode-command.ts, server/tests/fixtures/peertube-plugin-test-transcoding-one/main.js, server/tests/plugins/plugin-transcoding.ts, shared/models/videos/video-transcoding.model.ts, support/doc/plugins/guide.md
This PR adds support for inputOptions and videoFilters in transcode plugins.
Transcode plugins can be used to add support for new encoders.
However, some require inputOptions and thus cannot be used with current transcode plugin API.
For instance, vaapi hardware accelerated encoders require these input options `-hwaccel vaapi -hwaccel_output_format vaapi -vaapi_device /dev/dri/renderD128`
Closes #3846
=> add support for inputOptions and videoFilters in transcode plugin

client/package.json, client/src/assets/player/peertube-player-manager.ts, client/yarn.lock
This PR replaces the current `videojs-contextmenu-ui` with an owned and modified version that allows evaluating the value of the context menu `content` at `oncontextmenu` event, allowing dynamic context menus in the player.
_side note_: having our own version of this videojs plugin will come in handy for future work in the contextmenu, for instance adding support for icons.
closes #3802
Open any video and toggle the loop feature.
=> add loop toggle to the player contextmenu

server/lib/stat-manager.ts, server/models/video/video-channel.ts, server/models/video/video-playlist.ts, server/tests/api/server/stats.ts, shared/models/server/server-stats.model.ts
Adds the number of local playlists, local channels and active local channels on various timeframes (akin to active users stats): daily/weekly/monthly.
=> add channel and playlist stats to server stats endpoint

client/src/app/+videos/+video-watch/video-watch.component.html, client/src/app/+videos/+video-watch/video-watch.component.ts
Adds a "open video there" link next to the origin instance value. It is inconspicuous enough to not clutter the interface, yet communicates the action clearly in the context of the "origin instance" label and value, which is renamed as "origin" for this new dual usage.
closes #3624
=> add link to open video on origin instance

server/helpers/markdown.ts, server/lib/client-html.ts, server/lib/emailer.ts, server/tests/client.ts
Render markdown then strip html tags for link previews.
fixes #3839
Tested manually video/playlist pages with markdown descriptions (lists, emphasis, etc.) on https://socialsharepreview.com/
=> render plaintext descriptions on link previews

support/doc/api/openapi.yaml
In https://framacolibri.org/t/more-details-about-the-video-file-type/11680 the difference between the 4 URL fields in the VideoFile structure was explained.
This PR adds this information in the REST API doc to share the knowledge :)
I didn't create an issue for such a simple change but if it's required, please let me know.
=> Update VideoFile structure in the API doc

client/src/app/shared/form-validators/custom-config-validators.ts
While working on #3612, I noticed there was a typo in the 'min' error message of the SIGNUP_LIMIT_VALIDATOR.
None.
None.
=> rephrase signup limit validator error

client/src/app/+videos/+video-watch/video-watch-playlist.component.ts, client/src/app/+videos/+video-watch/video-watch.component.ts
I have added a "previous" button on the player, as requested in https://github.com/Chocobozzz/PeerTube/issues/3485. 
There are currently a few issues though:
* It duplicates code from `findNextPlaylistVideo()` and `navigateToNextPlaylistVideo()`
* Light tests showed this button was showing even when the user was not watching a playlist 
Resolves https://github.com/Chocobozzz/PeerTube/issues/3485
=> Added a "previous" button on player when watching playlist

client/src/app/+videos/+video-watch/video-watch-playlist.component.ts, client/src/app/+videos/+video-watch/video-watch.component.ts
I implemented the `?playlistPosition=last` alongside a "new" feature: the ability to provide a negative playlistPosition, which acts like a "reversed" array index. `?playlistPosition=-1` selects the first video **from the bottom of the playlist**, `?playlistPosition=-2` the second, etc.
This was done as to avoid modifying the prototype of the `updatePlaylistIndex (position: number)` method. 
Resolves https://github.com/Chocobozzz/PeerTube/issues/3897.
1. Create a playlist and add a dozen videos to it.
2. Check that `?playlistPosition=last` works.
3. Check that `?playlistPosition=-1`, `?playlistPosition=-3`, etc. works.
4. Check that `?playlistPosition=1`, `?playlistPosition=3`, etc. works.
5. Check that `?playlistPosition=-100` is defaulted to 1.
6. Check that …
=> Added "last" and a reversed ?playlistPosition in playlist URL

client/src/app/+videos/+video-watch/comment/video-comment.component.html
I got rid of the conditions that required a user to be logged in in order to reply to comments.
Resolves https://github.com/Chocobozzz/PeerTube/issues/3725
While non-logged-in users now have access to the reply button (see screenshot), I could not test if the reply worked properly (I expect it should, though) because my pleroma instance wouldn't let me do a remote interaction (no clue why that is).
=> Added ability to reply to comments with remote interaction

client/src/app/+admin/users/user-list/user-list.component.html, client/src/app/shared/shared-account-avatar/account-avatar.component.html, client/src/app/shared/shared-account-avatar/account-avatar.component.scss, client/src/app/shared/shared-account-avatar/account-avatar.component.ts, client/src/app/shared/shared-main/account/account.model.ts, client/src/sass/include/_mixins.scss
Change default avatar to account name initial.
closes #3935
1) Check avatar on account page.
1) Check avatar on channel page.
1) Check avatar in notifications.
1) Check avatar in comments.
1) Check avatar in comment add component.
1) Check avatar in video watch page.
1) Check avatar in my subscriptions.
=> Use account initial as default avatar

client/src/assets/player/images/info.svg, client/src/assets/player/p2p-media-loader/p2p-media-loader-plugin.ts, client/src/assets/player/peertube-player-local-storage.ts, client/src/assets/player/peertube-player-manager.ts, client/src/assets/player/peertube-videojs-typings.ts, client/src/assets/player/stats/stats-card.ts, client/src/assets/player/stats/stats-plugin.ts, client/src/assets/player/webtorrent/webtorrent-plugin.ts, client/src/sass/player/context-menu.scss, client/src/sass/player/index.scss, client/src/sass/player/stats.scss, scripts/i18n/create-custom-files.ts
This PR adds a "stats for nerds" panel, like YouTube provides, minus a few things: no mystery text, no exposure of an optimal resolution, no loudness normalization (we don't have that yet), no fancy graphs (yet).
It serves as a good debug tool for advanced users, where we could move some of the information we currently display in the bar (like p2p traffic) - taking precious space.
closes #1788 
TODO:
- test with:
Don't mind the fluffy cat 😉
=> add stats videojs plugin

README.md
Apparently the FAQ has moved, see the [old URL](https://github.com/Chocobozzz/PeerTube/blob/develop/FAQ.md).
=> update FAQ urls in README

server/lib/hls.ts
Remove prefixed comma when there's no video codec.
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=2500677,RESOLUTION=1920x1080,FRAME-RATE=30,CODECS=",mp4a.40.2"
1080.m3u8
```
1) Watch a video with both video and audio codec.
1) Watch a video with only audio codec.
=> Fix HLS playlist format

support/doc/dependencies.md
Specify message of possible Mac OS error in dependencies documentation, so people know whether to apply the suggested solution.
N/A
Just a minor addition to documentation :)
=> add possible OSX/postgres message to dependencies documentation

server/tools/peertube-plugins.ts
The `plugins list` command was not using --url, --username and --password parameters, and was always requesting on the first server in the .netrc file.
=> Fix CLI plugins list command: use command parameters.

support/docker/production/.env, support/docker/production/config/custom-environment-variables.yaml
Allow SSL database parameter via environment variable
=> Allow SSL database parameter

server/models/server/plugin.ts
If a plugin checkbox settings has a default value true, the frontend receive always true as value.
NB: I'm merging this on release/3.2.0 because I need this fix for the 3.2.0 release, and I tested the fix on this branch. Sorry if this is not right.
Fix for https://github.com/Chocobozzz/PeerTube/issues/4106
I have no time to add tests to this PR, sorry.
=> Fix 4106: default boolean plugin setting for frontend

client/src/app/+videos/+video-edit/shared/video-edit.component.html
Change "license" to "licence" for consistency in the user interface in English. 
- License is both a noun and a verb in the United States.
- If you live in any other English-speaking country, you will spell it "licence" when you use it as a noun and "license" when you use it as a verb.
=> change license to licence

client/src/app/app.component.scss
Changes the mobile CSS so that only the instance name is hidden in mobile view.
1) Open the site with a screen res with max-width < 500 px.
=> Show logo in mobile view

support/docker/production/config/custom-environment-variables.yaml
Add an environment variable for `log.level`.
I was asked in #4071 to run PeerTube with log level set to debug and figured it was not possible to set it using an environment variable.
I tested on my own instance by modifying the `custom-environment-variables.yaml` file and setting `LOG_LEVEL=debug`.
=> Allow setting log level using PEERTUBE_LOG_LEVEL envvar

scripts/upgrade.sh
After running the automatic upgrade script a lot of paths get an extra slash (like the symbolic link for peertube-latest), because PEERTUBE_PATH has an unnecessary trailing slash. Although this doesn't lead to bugs, it's annoying the hell out of me for a couple of years now.
=> Remove annoying superfluous slash

client/src/app/+videos/+video-edit/shared/video-edit.component.ts, client/src/app/+videos/+video-edit/video-add-components/video-go-live.component.ts, client/src/app/+videos/+video-edit/video-add-components/video-import-torrent.component.ts, client/src/app/+videos/+video-edit/video-add-components/video-import-url.component.ts, client/src/app/+videos/+video-edit/video-add-components/video-send.ts, client/src/app/+videos/+video-edit/video-add-components/video-upload.component.ts, client/src/app/shared/shared-main/video/video.service.ts
A small fix that factorises the static default video privacy to the function returning filtered video privacies, and computes the default video privacy based on those returned by the API.
fixes #4159
=> allow public video privacy to be deleted in the web client

client/src/app/+about/about-instance/about-instance.component.html, client/src/app/+about/about-instance/about-instance.component.scss, client/src/app/+about/about-instance/about-instance.component.ts, client/src/app/+about/about-instance/contact-admin-modal.component.html, client/src/app/+about/about-instance/contact-admin-modal.component.scss, client/src/app/+about/about-instance/contact-admin-modal.component.ts, client/src/app/+about/about-routing.module.ts, client/src/sass/include/_mixins.scss
This PR adds a sub-route `/about/instance/contact` in order to prefill the contact form with a subject and a body queryParams.
Also fixes minor CSS issues for input displaying in the contact-form.
closes https://github.com/Chocobozzz/PeerTube/issues/4160
1. Enable the contact-form in the administration and configure a SMTP mail to test it.
- Click on the contact form button in `/about/instance`, it should open the modal with `/about/instance/contact`
- When you close the modal the router should redirect to `/about/instance`
- When you click on the modal body overlay, it should keeps the input value history when re-open the modal
- Access to `/about/instance/contact?subject=My Subject&body=My Body multiline%0Aline 1%0Aline 2`
- It should display the contact form in the modal with …
=> Prefilled contact form with subject and body queryParams

support/doc/api/openapi.yaml
When updating a video through the API, you can set the downloadEnabled boolean on PUT, but it's missing from the OpenAPI doc.
Yes, I'm using a script on the API to bulk update downloadEnabled to true for all videos from a channel. Tested on a live production instance with the latest release.
This pull request also contains an addition of the word 'video' which seemed to be accidentally left out in a description for handling live videos.
=> API doc: downloadEnabled boolean to PUT video

support/doc/plugins/guide.md
May comes in very handy to quickly test a plugin in a production like environment before it reaches a greater world.
> This magic trick comes from @Chocobozzz himself, who passed it on to @JohnXLivingston, who then passed it down to me.
=> Document a way to update the last available version of a plugin manually

server.ts
Currently access logs are printed with double line breaks at the end:
```
[peertube.br0.fr:443] 2021-07-05 15:40:55.767 info: xxx - - [05/Jul/2021:15:40:55 +0000] "GET /api/v1/instance HTTP/1.1" 400 - "-" "FediList agent (https://fedilist.com/)"
[peertube.br0.fr:443] 2021-07-05 15:40:55.940 info: xxx - - [05/Jul/2021:15:40:55 +0000] "GET /.well-known/nodeinfo HTTP/1.1" 200 120 "-" "FediList agent (https://fedilist.com/)"
[peertube.br0.fr:443] 2021-07-05 15:40:56.155 info: xxx - - [05/Jul/2021:15:40:56 +0000] "GET /nodeinfo/2.0.json HTTP/1.1" 200 1659 "-" "FediList agent (https://fedilist.com/)"
```
Other logs are printed with only one line break:
```
[peertube.br0.fr:443] 2021-07-05 15:38:25.784 info: Processing ActivityPub fetcher in job 98.
[peertube.br0.fr:443] 2021-07-05 15:38:25.789 …
```
=> Trim access log messages to prevent double line break

support/doc/dependencies.md
Initializing the postgresql database uses `ident` instead of `md5` as authentication for host on Red Hat family distributions. PeerTube uses (and expects) password authentication for postgresql. By using postgresql-setup/initdb with this specific setup option, one doesn't need to install oidentd which needs a 'peertube' Linux user to match authentication and doesn't exist yet when you are using the dependencies guide for development (in the production guide the peertube user is created in /var/www/peertube). This way of setup also prevents editing the pg_hba.conf manually afterwards.
Tested on RHEL8 and Fedora. Syntax for postgresql-setup with --initdb as argument replaces obsoleted initdb mode call. See 'Post-installation' at https://www.postgresql.org/download/linux/redhat/
Result after …
=> Postgresql-setup init option for auth-host

client/src/app/+videos/+video-watch/shared/information/privacy-concerns.component.scss, client/src/sass/bootstrap.scss, client/src/sass/include/_variables.scss
This PR try to correct all known issues about dropdown z-index especially with :
- user dropdown notification placing hover the sub-menu titles (also as a dropdown-menu)
- dropdowns moving hover the header and privacy message on scroll
- missing `.dropup` z-index rule especially in report admin page
Closes https://github.com/Chocobozzz/PeerTube/issues/4262 and https://github.com/Chocobozzz/PeerTube/issues/4265
Plus floating dropdown hover menu and privacy message on scroll as the following screenshots :
=> Correct dropdown/dropup z-index

server/lib/plugins/register-helpers.ts, server/lib/plugins/video-constant-manager-factory.ts, server/tests/fixtures/peertube-plugin-test-video-constants/main.js, server/tests/lib/plugins/video-constant-registry-factory.test.ts, server/tests/plugins/video-constants.ts, shared/models/plugins/server/managers/plugin-playlist-privacy-manager.model.ts, shared/models/plugins/server/managers/plugin-video-category-manager.model.ts, shared/models/plugins/server/managers/plugin-video-language-manager.model.ts, shared/models/plugins/server/managers/plugin-video-licence-manager.model.ts, shared/models/plugins/server/managers/plugin-video-privacy-manager.model.ts, shared/models/plugins/server/plugin-constant-manager.model.ts, support/doc/plugins/guide.md
Allow a plugin developer to get back constants values, and reset constants deletions or additions.
> see https://www.martinfowler.com/eaaCatalog/registry.html for a quick `registry` definition
This would introduce a lot of *deprecations*, so feel free to disagree on the naming changes. 
Initial suggestion was :
> ```ts
> export interface ConstantManager <K> {
>  add: (key: K, label: string) => boolean
>  delete: (key: K) => boolean
>  get: () => { [ id: K ]: string }
>  reset: () => void
>}
>```
> https://github.com/Chocobozzz/PeerTube/pull/4214#issuecomment-871453519
But imho this would convey more meaning:
```ts
export interface ConstantRegistry <K extends string | number> {
addConstant: (key: K, label: string) => boolean
deleteConstant: (key: K) => boolean
getConstantValue: (key: K) => …
```
=> Introduce generic constant registries for plugins

client/src/app/menu/menu.component.scss
Remove padding-left and adapt max-width for user dropdown-toggle on touchscreens in order to get the correct position of the indicator.
Closes https://github.com/Chocobozzz/PeerTube/issues/4263
=> Fix user-dropdown-indicator position on touchscreens

support/doc/dependencies.md
Adding documentation for Rocky Linux 8.4
Adapted from CentOS 8... but seems like there is stuff missing from that section.
Tested in AWS up until the steps end.
- [X ] 💭 no, because this PR is a draft and still needs work
=> Adding Rocky Linux 8.4

support/systemd/peertube.service
removing the setting
StandardOutput
StandardError
Standard output type syslog is obsolete in systemd
no, because this PR does not update server code
=> Standard output type syslog is obsolete in systemd

client/src/app/+about/about-instance/about-instance.component.html, client/src/app/+about/about-instance/contact-admin-modal.component.html, client/src/app/+about/about-instance/contact-admin-modal.component.scss, client/src/app/+about/about-instance/contact-admin-modal.component.ts, client/src/app/+videos/+video-edit/video-add.component.html, client/src/app/+videos/+video-edit/video-add.component.scss, client/src/app/+videos/+video-edit/video-add.component.ts, client/src/app/core/users/user.model.ts, server/models/user/user.ts, server/tests/api/users/users.ts, shared/models/plugins/client/client-hook.model.ts
This PR introduces:
1. Display alerts on the top of the upload page when the user has for its account
- quota left lower than 10%
- video review turned on 
2. Display `Contact us` button in alerts of upload page when contact form is enabled
3. Shorter text for the contact button of the about page:
`Contact us` instead of `Contact administrator` as it's more explicit for a call-to-action button, and an instance can be maintained by more than one admin
**For the french translation I suggest «`Nous contacter`» instead of «~`Contact de l'administrateur`~**».
Fixes https://github.com/Chocobozzz/PeerTube/issues/4335 and https://github.com/Chocobozzz/PeerTube/issues/4333
=> Alert user for low quota and video auto-block on upload page

client/src/app/+signup/shared/signup-success.component.html
This PR follows the discussion https://github.com/Chocobozzz/PeerTube/pull/4352#issuecomment-907118886
To avoid breaking the message before clicking on the documentation link, the message is the last one.
Also, this is a `routerLink` navigation to avoid displaying the warning setup modal on the new page.
https://github.com/Chocobozzz/PeerTube/issues/3331
=> Add account setup message to welcome alert after signup

client/src/app/+admin/follows/followers-list/followers-list.component.scss, client/src/app/+admin/follows/following-list/following-list.component.html, client/src/app/+admin/follows/following-list/following-list.component.scss, client/src/app/shared/shared-main/buttons/button.component.scss
Fixes broken my-delete buttons into admin federation lists depending on language.
Use  the generic label «Remove » on following list to keep consistency with follower list.
Resolves https://github.com/Chocobozzz/PeerTube/issues/3953
=> Fix broken delete buttons of admin federation lists

client/src/app/shared/shared-main/misc/channels-setup-message.component.ts
Check if `this.user.videoChannels` not undefined in the getter `hasChannelNotConfigured` to avoid errors until user information fully loaded.
Resolves https://github.com/Chocobozzz/PeerTube/issues/4379
=> Fix undefined this.user.videoChannels on production build

support/docker/gitpod/Dockerfile
Gitpod's docker image for PeerTube hasn't been rebuilt for some time, and started to have compatibility issues between dependencies and the node engine. Triggering this rebuild should force Gitpod to rebuild the image with node v16.13.0 instead of node v12.20.0.
None.
But in fact, yes : I did trigger a rebuild of the image on my fork, and it's working great!
=> Trigger rebuild of Gitpod's image for PeerTube

scripts/upgrade.sh
If yarn fails because we don't have the correct nodejs version, we want to know earlier, so that we can upgrade nodejs without having a non-working half-installed peertube instance.
I got an issue on latest upgrade of Peertube, because I was still on nodejs 10. The `yarn` command failed, and I thought that I didn't need to upgrade node immediately, but could wait one more day. I was mistaken :( 
This problem was seen on https://github.com/osm-fr/infrastructure/issues/330. 
Note that I didn't yet tested the change on the upgrade script, but firstly want to make that you agree that we can run `yarn` on the version path instead of running in the production path.
=> Launch yarn before linking to new peertube version

server/tools/peertube-import-videos.ts
When importing videos from another service, an interval can be applied between each download.  
It only really makes sense to apply this interval when the last attempted download actually happened, and not when it was skipped.
I originally had to edit code in `dist/` directly, as I needed the functionality immediately.  
I have tested it only manually and it appears to behave as I would expect.
I am not an experienced `type/javascript` programmer and would like to confirm that the fix is as you might expect or want it to be.  
The problem is trivial, but is the solutions satisfactory?
=> Apply import interval only when reasonable

server/controllers/api/bulk.ts, server/controllers/api/users/index.ts, server/controllers/api/users/token.ts, server/controllers/api/video-playlist.ts, server/controllers/api/videos/comment.ts, server/controllers/api/videos/index.ts, server/controllers/api/videos/live.ts, server/controllers/api/videos/update.ts, server/controllers/api/videos/upload.ts, server/lib/video-comment.ts, shared/models/plugins/server/server-hook.model.ts, support/doc/plugins/guide.md
Add `token` to hook parameters `action:api.video.updated` and `action:api.video.uploaded`.
I'm developing a plugin which generates a subtitle (server side) if a video has a `language` set  and this is supported by the plugin.
This generation is done as part of the video creation/update process and I'd like to be able to add this subtitle to the video.
As far as I'm aware of, the API endpoint `PUT /videos/${videoUuid}/captions/${captionLanguage}` looks like the best entrypoint to do so, even from a plugin perspective. 
However, this endpoint is only accessible by an authenticated user.
It seems it's possible to make use of the user token client side, it feel like a legitimate use-case to do the same server-side in the context of a user related request.
I evaluate other options, one of …
=> [Plugin][Hook] Add token as parameters to video creation and update hooks

server/controllers/client.ts, server/lib/client-html.ts, support/nginx/peertube
Since PeerTube uses Accept-Language header to determine response language, the HTTP response should include the `Vary: Accept-Languge` header to ensure no cache will prevent language detection.
solves #3647
Yes, manually.
=> Add header Vary Accept-Language

server/controllers/api/plugins.ts, server/middlewares/validators/plugins.ts, server/tests/cli/peertube.ts, server/tools/peertube-plugins.ts, shared/extra-utils/server/plugins-command.ts, shared/models/plugins/server/api/install-plugin.model.ts
It is already possible to specify a plugin version when doing `run plugin:install -- --npm-name peertube-plugin-myplugin --plugin-version 0.0.1`.
This PR add the same parameters for the CLI `plugins install` commands.
=> CLI: plugins install command accept a --plugin-version parameter.

scripts/clean/server/test.sh
Add support for running tests with GNU xargs (which are used by MacOS).
```
man xargs:
-r      Compatibility with GNU xargs.  The GNU version of xargs runs the utility argument at least once, even if xargs input is empty, and it supports a -r option to inhibit this
behavior.  The FreeBSD version of xargs does not run the utility argument on empty input, but it supports the -r option for command-line compatibility with GNU xargs, but the
-r option does nothing in the FreeBSD version of xargs.
```
=> scripts/test: make MacOS compatible

client/src/app/+videos/+video-edit/shared/video-edit.component.ts, server/initializers/constants.ts
It adds `zxx` as part of the available "language codes" in the backend. `zxx` is the ISO-639 code for the absence of linguistic content, according to Wikipedia (https://en.wikipedia.org/wiki/ISO_639): 
> No linguistic information at all (added 2006-01-11). The content (e.g. graphics, photos or audio/video records not including text in a human language, or technical metadata and most programming source code) is usable as is with any language and should not be translated (except for its description possibly associated in separate contents, or for non-essential fragments of the content).
As this "language" also appeared in the group "All languages" in the forms, I had to create a dedicated group for it. Feel free to suggest better names 😉.
Closes …
=> Added "zxx" (no linguistic content) in available video languages

server/tools/peertube-redundancy.ts
I think this is a copy/paste typo.
=> Fix typo for cli redundancy action

server/models/server/plugin.ts, server/tests/fixtures/peertube-plugin-test-six/main.js, server/tests/plugins/plugin-storage.ts
Fix plugin storage return value when storing a Json array.
We may as well entirely rely on `JSON.parse` which is foolproof.
=> Fix plugin storage return value when storing a Json array

server/controllers/api/videos/captions.ts, server/tests/fixtures/peertube-plugin-test/main.js, server/tests/plugins/action-hooks.ts, shared/models/plugins/server/server-hook.model.ts
Add video caption `created` and `deleted` hooks.
=> Add video caption created and deleted hooks

support/doc/api/openapi.yaml
The API reference was falling behind: I added all the new types in the openapi reference.
Relates to https://github.com/Chocobozzz/PeerTube/issues/1565
=> Updated notification types in openapi reference

client/src/app/shared/shared-forms/select/select-languages.component.ts, client/src/types/select-options-item.model.ts
#4631 introduced the `zxx` language code and put it in a "Other" group in the language selector of the video-edit page. However, `zxx` was not in a dedicated group in the more widely-used `my-select-languages` component.
This PR adds a `groupOrder` attribute to `SelectOptionsItem` and puts `zxx` in group "Other" (order 0), and all languages remain in the "All languages" group (order 1).
None.
=> Move zxx to its own group in select-languages component

config/default.yaml, config/production.yaml.example, server/helpers/youtube-dl/youtube-dl-cli.ts, server/initializers/config.ts
On Debian, the `python` often points to `/usr/bin/python2`.
This PR aims at giving the ability to define the python path so the administrator can choose the path to the python with which PeerTube executes youtube-dl or yt-dlp.
- https://github.com/Chocobozzz/PeerTube/issues/4682
- https://github.com/YunoHost-Apps/peertube_ynh/issues/295
(*not sure whether it is relevant here as long as the tests continue passing ?*)
=> Give the ability to define python path for youtube-dl / yt-dlp

server/types/plugins/register-server-option.model.ts
I'm trying to use the new @peertube/peertype-types npm package for my peertube-plugin-livechat.
The function getAuthUser return type was missing the user.Account.name property.
This is an expected property, so that we can have the user displayName. See for example this test file:
https://github.com/Chocobozzz/PeerTube/blob/73e64592b9b949bf9b895e2fae8dafcfab0b5124/server/tests/fixtures/peertube-plugin-test-four/main.js#L101
=> Fix missing user.Account.name on getAuthUser return type.

.github/CONTRIBUTING.md
This PR removes redundant `#/` in some links after the root URI in the contributing guideline, fixing broken links.
See links to client-side architecture and server-side architecture on https://github.com/Chocobozzz/PeerTube/blob/3726c3725506d0f8a26ded34f42d7bcfb5d0e639/.github/CONTRIBUTING.md
=> Fix broken links in contributing guideline

client/src/app/menu/menu.component.html
Hide my-global-icon when custom menu items are added without icon property.
=> menu: hide undefined icons

client/src/types/register-client-option.model.ts, server/lib/plugins/register-helpers.ts, server/models/server/plugin.ts, shared/models/plugins/server/managers/plugin-settings-manager.model.ts, shared/models/plugins/server/settings/public-server.setting.ts
This mainly fix the `onSettingsChange` argument typing.
I'm not 100% sure the setting `value` can be a boolean though.
But this is how it was typed before so I just made it consistent.
=> Fix plugin settings manager definition

support/docker/production/Dockerfile.bullseye
Hello !
Regarding issue #4812, python virtual package uses python-is-python2 and so install python2 instead of python3
But we need to explicitly use python3 for PeerTube tools (especially ytp-dl)
May need an hotfix to propagate changes as currently import is probably broken for everyone using the official docker image :-/
Issue #4812 
- [x ] 🙅 no, because this PR does not update server code
However, I test installing python3 inside the official docker image and it solves the problem with ytp-dl
=> Install python3 instead of global python in docker image

client/src/app/+videos/+video-edit/shared/video-caption-add-modal.component.ts, client/src/app/+videos/+video-edit/shared/video-caption-edit-modal/video-caption-edit-modal.component.html, client/src/app/+videos/+video-edit/shared/video-caption-edit-modal/video-caption-edit-modal.component.scss, client/src/app/+videos/+video-edit/shared/video-caption-edit-modal/video-caption-edit-modal.component.ts, client/src/app/+videos/+video-edit/shared/video-edit.component.html, client/src/app/+videos/+video-edit/shared/video-edit.component.scss, client/src/app/+videos/+video-edit/shared/video-edit.component.ts, client/src/app/+videos/+video-edit/shared/video-edit.module.ts, client/src/app/shared/form-validators/video-captions-validators.ts, client/src/app/shared/shared-main/video-caption/video-caption-edit.model.ts, client/src/app/shared/shared-main/video-caption/video-caption.service.ts
Introduce a new __Edit__ button on a subtitle.
It opens a modal with simple textarea allowing the user to do quick corrections
on a subtitle.
https://github.com/Chocobozzz/PeerTube/issues/1481
=> Add simple subtitle edition from video captions tab

client/src/app/shared/shared-user-settings/user-video-settings.component.html
When a user clicks on *sharing system* in the user settings, then the privacy notice is opened, but still covered by the settings. Closing the settings is confusing. Hence, we open a new window with the privacy notice.
=> open privacy info in user settings dialogue in new window

.gitignore, package.json, server/lib/object-storage/shared/object-storage-helpers.ts, server/tests/api/object-storage/videos.ts, yarn.lock
Use [@aws-sdk/lib-storage](https://github.com/aws/aws-sdk-js-v3/tree/main/lib/lib-storage) for multipart upload
#3407
=> object-storage: @aws-sdk/lib-storage for multipart

client/src/app/shared/shared-video-miniature/video-filters-header.component.html, client/src/app/shared/shared-video-miniature/video-filters-header.component.scss, shared/models/videos/video-sort-field.type.ts
This allows the user to sort videos by the **Original publication date**, allowing them to differentiate between the date of publication on PeerTube and for example the date of publication on other platforms.
Resolves #4959
=> (#4959) Add 'Originally Published At' sort option in videos pages

client/src/app/+my-library/+my-video-channels/my-video-channels.component.html
It displays "No subscribers" instead of "0 subscribers" in the my-library, to follow what happens with the videos count.
It was originally part of https://github.com/Chocobozzz/PeerTube/pull/4484, but I decided to split it into its own PR.
=> Display "No subscribers" in my-library instead of "0 subscribers"

support/doc/docker.md
Broken since the production guide was *emojified* 6 months ago.
=> fix(doc): fix links to 'anchors' in install doc

scripts/upgrade.sh, support/doc/production.md
More readable diff on configuration file when upgrading.
When we use the upgrade.sh script, the script does a diff between the current production.yaml file and the production.yaml.example file. This diff is difficult to read, because there are many customizations in the production.yaml file.
This PR replaces the diff in upgrade.sh by the same kind of diff mentioned in the documentation for nginx and systemd: a diff between production.yaml.example in the 2 last available versions.
https://github.com/Chocobozzz/PeerTube/issues/5036
=> Implement 5036: more readable diff on configuration file when upgrading.

server/controllers/services.ts, server/tests/api/server/services.ts
Since the oembed service of peertube ignores the parameters passed in the URL, here with the changes the parameters are added to the oembed URL by extracting the query parameters.
This fixes issue [#4974](https://github.com/Chocobozzz/PeerTube/issues/4974)
=> fixes video not played from defined parameters in embed service 

support/doc/production.md
On Ubuntu 22.04, the dir `/var/www/peertube` is restricted to user peertube & group peertube. This causes issues with many of the subsequent sudo commands, and also results in white-screen on initial visit to the site due to JS files not being accessible. 
JS console output:
```
Loading module from “https://watch.thelema.social/client/en-US/runtime.a28a87033973e138.js” was blocked because of a disallowed MIME type (“text/html”).
Loading module from “https://watch.thelema.social/client/en-US/polyfills.4dee205ae13c48d1.js” was blocked because of a disallowed MIME type (“text/html”).
Loading module from “https://watch.thelema.social/client/en-US/main.559407a6b86e978c.js” was blocked because of a disallowed MIME type (“text/html”).
Loading failed for the module with source …
```
=> Ensure peertube root directory is setup to be traversed by nginx

server/initializers/installer.ts
Password should remain "test" in dev mode for root.
Fix regression of 9452d4fd33 which introduces NODE_ENV=dev
Steps to reproduce:
```bash
sudo -u postgres dropdb peertube_dev
sudo -u postgres createdb -O peertube peertube_dev
sudo -u postgres psql -c "CREATE EXTENSION unaccent;" peertube_dev
sudo -u postgres psql -c "CREATE EXTENSION pg_trgm;" peertube_dev
```
=> Fix password for root in dev mode

support/doc/development/tests.md
Nowhere the contributor is told to install parallel. This fixes that.
Also explain how to install parallel and exiftool on debian-based systems.
N/A
=> document parallel depedency for tests and how to install it

server/lib/hls.ts
npm run lint report an error on server/lib/hls.ts
And indeed, the `async` is useless in this function as we just need to return the result of `playlistFilesQueue.add` which is a Promise.
=> Fix lint on server/lib/hls.ts

client/angular.json
Each time we run `npm run build`, a prompt asks us whether we want to send analytics data to angular.
I think we should disallow that by default.
=> Disallow sending analytics data to Angular team

shared/server-commands/requests/requests.ts
Show the error message the server returned in the response when the status is not the one expected.
Note: I proposed to help the user so they can see more details in log. The last line displays a URL. I am not very sure of the relevancy, feedback welcome.
=> Tests: Add response error along with unexpected status in report

.editorconfig, scripts/parse-log.ts, support/doc/development/tests.md
While testing APIs, one may want to only print latest logs and continuously follow them in order to ease the logs analysis.
This PR aims at allowing parse-log to read stdin so it can be piped with the output of commands like `tail` and `tail -f`.
=> Allow continusously printing logs through tail and parse-log

support/doc/tools.md
% is a special character for crontab. From man 5 crontab: A "%" character in the command, unless escaped with a backslash (\), will be changed into newline characters, and all data after the first % will be sent to the command as standard input.
=> Escape % signs in crontab example (CLI tools docs)

support/doc/plugins/guide.md
Adding peertube-plugin-quickstart-typescript in the documentation.
Related to https://github.com/Chocobozzz/PeerTube/issues/5187
=> #5187: Adding peertube-plugin-quickstart-typescript in the documentation.

client/src/app/+videos/+video-edit/video-add-components/video-upload.component.ts
Do not delete a partially uploaded file on the server when you close the upload page.
#5078, #4432
=> fix: keep partially uploaded files

client/src/assets/player/peertube-player-manager.ts, client/src/assets/player/shared/manager-options/hls-options-builder.ts, client/src/assets/player/shared/manager-options/manager-options-builder.ts, shared/models/plugins/client/client-hook.model.ts
Add filter for p2p-media-loader-options filter
closes #5317
=> feat(plugins): add p2p-media-loader options filter

client/src/app/+my-library/my-video-channel-syncs/my-video-channel-syncs.component.html, client/src/app/+my-library/my-video-channel-syncs/my-video-channel-syncs.component.ts
On channel sync screen, move the list imports button form the left of the table into the action buttons list.
Fixes #5337
Previously:
With the patch:
=> Sync channel: move the list imports button #5337

client/src/app/shared/shared-video-miniature/video-filters-header.component.html
As requested in #5134, I have added an option in the "sort" menu in order to use the already-existing "name" filter.
Implements https://github.com/Chocobozzz/PeerTube/issues/5134
(you can see it's sorting alphabetically, instead of any other sorts that would put the SkylandStyle video first (date, view count, etc.))
=> Added filter to sort videos by name (alphabetical order)

support/doc/plugins/guide.md
Websocket handlers for plugins is a new feature, coming with Peertube 5.0.0 (unreleased yet).
This information is missing in the documentation.
=> Fix: missing peertube version in documentation

client/src/app/+admin/config/edit-custom-config/edit-basic-configuration.component.html, client/src/app/+videos/video-list/videos-list-common-page.component.ts
Add missing options to define the default sort in trending page
Create new case for `name` sorting in `parseTrendingAlgorithm` because the `name` algorithm is not prefixed by `-`
https://github.com/Chocobozzz/PeerTube/issues/5363
| Before | After |
| ---------  | ------- |
| ![before](https://user-images.githubusercontent.com/11453567/196344727-6b9e26d1-193b-46a4-88d7-b67c7b747cd1.png) | ![Capture d’écran du 2022-12-17 22-57-14](https://user-images.githubusercontent.com/18343818/208267448-8648f23c-aeb1-4bcc-a8dd-096a18b6fb20.png)  |
=> feat(config): add missing videos sort options in admin

client/src/assets/player/shared/p2p-media-loader/hls-plugin.ts
HLS.js fatal errors are currently logged as warnings, and non-fatal as errors. I assume this is a typo. Additionally I added the current time in the error logging, so it's gets easier to reproduce these errors.
=> Log HLS fatal error with error label

client/src/app/+videos/+video-watch/video-watch.component.ts, client/src/assets/player/peertube-player-manager.ts, client/src/assets/player/types/manager-options.ts
I'm using a puppeter script that runs to test PeerTubes video streams. To increase the speed it would be great to set the playback rate via an URL parameter.
=> feat(player/playbackRate): set rate with url param

client/proxy.config.json
There is a problem with Node 18 and `localhost` redirection with Angular proxy. To resolve it, we set directly the IPv4 address.
=> Fix Angular proxy with Node 18

client/src/app/menu/notification.component.scss, client/src/sass/include/_mixins.scss
I just updated files where I found the usage of a SCSS variable instead of the pvar() function.
=> Use pvar() instead of SCSS variables

client/src/app/+my-library/my-videos/my-videos.component.ts
In My Library => Videos, filtering by channels is actually displaying channel's name instead of channel's displayName as label.
Fixes #5038
=> Use displayName as label in channelFilters

server/lib/auth/oauth-model.ts
A secret bearerToken was written in debug logs.
https://github.com/Chocobozzz/PeerTube/issues/5614
=> Fix #5614: do not log bearerToken.

server/controllers/api/users/my-subscriptions.ts, server/tests/fixtures/peertube-plugin-test/main.js, server/tests/plugins/filter-hooks.ts, shared/models/plugins/server/server-hook.model.ts
Adding server hooks to list subscription videos
https://github.com/Chocobozzz/PeerTube/issues/5574
=> Add server hooks to list subscriptions

client/src/assets/player/shared/hotkeys/peertube-hotkeys-plugin.ts
Add player hotkey support for non-Latin keyboard layouts
https://github.com/Chocobozzz/PeerTube/issues/5682
=> Non latin keyboard layout support player shortcut

server/controllers/object-storage-proxy.ts
When S3 returns a HTTP 206 response the content-range should be proxied as well.
=> object-storage-proxy: set content-range

config/production.yaml.example
=> Correct API docs link in `./config/production.yaml.example`

client/src/app/+admin/config/edit-custom-config/edit-instance-information.component.html, client/src/app/shared/shared-instance/instance.service.ts
Closes https://github.com/Chocobozzz/PeerTube/issues/5710
It looks to me that why it works in the "Support" section is because it's using `this.markdownService.enhancedMarkdownToHTML()` 
https://github.com/Chocobozzz/PeerTube/blob/00ee545c2444c35ed0d37df9f91984246aa36124/client/src/app/shared/shared-support-modal/support-modal.component.ts
which has different rules set in https://github.com/Chocobozzz/PeerTube/blob/00ee545c2444c35ed0d37df9f91984246aa36124/shared/core-utils/renderer/markdown.ts#L17 which allows `image`
So I changed the relevant line for the "About" page fields and now it works 🎊 
https://github.com/Chocobozzz/PeerTube/issues/5710
Do we need to run or have a test for this?
Before
After
=> feat(about): render images in markdown

support/docker/production/.env, support/docker/production/config/custom-environment-variables.yaml
I found that it should be configurable via `name` from the config file here: https://github.com/Chocobozzz/PeerTube/blob/9258e9a4a37911fc64b5faada2a7e604bd1ede1f/server/initializers/database.ts#LL59C36-L59C36
Closes https://github.com/Chocobozzz/PeerTube/issues/5708
I tested following the instructions from https://docs.joinpeertube.org/install/docker
Before
```
peertube-docker-peertube-1   |       "message": "database \"custom\" does not exist",
peertube-docker-peertube-1   |       "length": 93,
peertube-docker-peertube-1   |       "name": "error",
peertube-docker-peertube-1   |       "severity": "FATAL",
peertube-docker-peertube-1   |       "code": "3D000",
peertube-docker-peertube-1   |       "file": "postinit.c",
peertube-docker-peertube-1   |       "line": "875", …
```
=> feat(docker): make database name configurable

client/src/app/+admin/config/edit-custom-config/edit-instance-information.component.html, client/src/app/+my-account/my-account-notifications/my-account-notifications.component.html
There was a typo in the code that prevented a sentence from being translated and a missing `i18n` parameter. 
Fixes https://github.com/Chocobozzz/PeerTube/issues/5771
Fixes https://github.com/Chocobozzz/PeerTube/issues/5758
=> I18n missing parameter

scripts/upgrade.sh
The `ls` CLI command of FreebSD does not understand the `--search=time` parameter. "ls -t" is eequivalent and behaves the same on Linux as it does on FreeBSD.
The script scripts/update.sh contains code for updating the peertube server. It works fine, but the last command, which shows differences to the former config file, does not work on FreeBSD: the FreeBSD `ls` CLI command does not support `--search=time` parameter.
This change changes the parameter to `-t`, which is supported on Linux and FreeBSD and behaves the same on Linux as it does on FreeBSD. As a result, this notation trades some readability for better compatibility.
none
=> Make the update script fully FreeBSD compatible

config/default.yaml, config/production.yaml.example, server/initializers/checker-before-init.ts, server/initializers/config.ts, server/lib/redis.ts
Adds [redis sentinel](https://redis.io/docs/management/sentinel/) support.
closes #5141
Yes, manually. By setting up the following sentinel and connecting:
```
version: '2'
services:
redis-sentinel:
image: docker.io/bitnami/redis-sentinel:7.0
environment:
- REDIS_MASTER_HOST=127.0.0.1
networks:
- webproxy
ports:
- 26379:26379
volumes:
- redis-sentinel_data:/bitnami
redis:
image: docker.io/bitnami/redis:7.0
environment:
- ALLOW_EMPTY_PASSWORD=yes
networks:
- webproxy
ports:
- 6379:6379
volumes:
- redis_data:/bitnami
volumes:
redis-sentinel_data:
driver: local
redis_data:
driver: local
networks:
webproxy:
driver: bridge
```
Not sure if it's worth to setup a test for this feature?
=> feat(server): add redis sentinel support

server/lib/client-html.ts, server/lib/plugins/plugin-manager.ts
On startup, people trying to display the Peertube index page could face an error, because of a missing plugins-global.css file.
There was also a missing `async` attribute on a related function.
See https://github.com/Chocobozzz/PeerTube/issues/5744
I tested it by building Peertube, and running it again.
=> Fix #5744: Missing plugins-global.css + missing async

server/controllers/feeds/shared/common-feed-utils.ts, server/controllers/feeds/video-podcast-feeds.ts, server/middlewares/validators/feeds.ts, server/tests/feeds/feeds.ts
This pull request adjusts the following:
1. In Podcast RSS feeds, it uses the largest available actor avatar instead of the first available.  Greatly improves user experience in applications.
2. Sets a unique `<guid>` element in `<podcast:liveItem>` to make it easier for applications to uniquely identify different times the same permanent live stream goes live.
Updated tests for `<guid>`.  Avatar checks will need more work to pull in avatars during testing, but they have been checked manually.
Testing in production on 5.2.0-rc.1
=> Use largest avatar in RSS feeds, unique guid for liveItems

server/middlewares/validators/videos/videos.ts, server/tests/api/videos/resumable-upload.ts
Along with the failed uploaded file, the metadata file will also be removed from the disk and cache.
https://github.com/Chocobozzz/PeerTube/issues/5812#issuecomment-1596060166
=> Fix the cleanup after a failed upload

.github/workflows/docker.yml, support/doc/docker.md, support/docker/production/Dockerfile.bookworm, support/docker/production/docker-compose.yml
Switch docker base from bullseye to bookworm
My motivation was to get ffmpeg >= 5.1 which is available in bookworm while bullseye still has 4.3.x
=> Switch from debian bullseye to bookworm

packages/ffmpeg/src/ffmpeg-version.ts, packages/tests/src/server-helpers/core-utils.ts, server/server/helpers/core-utils.ts, server/server/initializers/checker-after-init.ts
Resolves the error that occurred when using an unconventional distribution of FFmpeg with a non-standard version string. For example, compiled from source, or a third-party fork.
* `#getFFmpegVersion` returns the full version string of the FFmpeg now, regardless of format.
* `#parseSemVersion` returns `null` if the string is not a semantic version string.
* `#parseSemVersion` handles normalization, such as if the patch segment is missing.
* If the FFmpeg version does not follow semver (so `#parseSemVersion` returns `null`), then we log a warning that we can't check compatibility. 
* Fixes https://github.com/Chocobozzz/PeerTube/issues/5911
=> fix: handle git installation of ffmpeg

CHANGELOG.md
Reference to `Add storage.tmp_persistent directory in configuration file` has the wrong line.
Currently it's pointing to line 128 which is empty.
Instead it should be 148 which is:
```
tmp_persistent: '/var/www/peertube/storage/tmp-persistent/' # As tmp but the directory is not cleaned up between PeerTube restarts
```
=> Corrected storage tmp location

server/scripts/upgrade.sh
During latest upgrade to 5.2.1, I had a message about /var/www/peertube not existing which is normal, because I'm using a different directory for Peertube.
=> Fix path to Peertube installation in upgrade.sh

server/server/initializers/constants.ts
Add Valencian option for video/captions languages
In KDE community, we started to create subtitles for our videos and upload them automatically to our instance (https://invent.kde.org/websites/video-subtitles). In our community, we have both Brazilian Portuguese translators and Valencian translators.
Brazilian translation is being dealt with in https://github.com/Chocobozzz/PeerTube/pull/5971, but it would be great to also add Valencian.
- [x ] 🙅 no, because this PR does not update server code
=> Add Valencian option for video/captions languages

scripts/upgrade.sh
=> Fix upgrade.sh when Peertube is installed outside the standard path

apps/peertube-runner/package.json, apps/peertube-runner/src/shared/http.ts, apps/peertube-runner/yarn.lock
Currently, the runner downloads the video file from the url set in the paylaod of a transcoding job. This url is pointing to our API and the runner will make POST request  to it with an jobToken and a runnerToken. Doing this ensure we can verify the tokens and return the video file. But returning the video file also means that we are using server resources to serve the file. 
If the runner is able to follow the redirect, it changes nothing for Peertube but if offers the possibility for applications using remote runners to do a redirect (to an s3 URL for example) and avoiding a downloading through their server, thus reducing traffic and memory usage.
#6125
=> Runner download videoFileUrl follow redirect

support/doc/tools.md
As asked here: https://framacolibri.org/t/remote-runner-installer-en-tant-que-service-systemd/18617/11 by Chocobozzz, here is some documentation on how you can setup the Peertube Runner as a SystemD service.
=> Documentation: how to create a systemd service for the Peertube runner.

support/doc/api/embeds.md
Add default values for all fields in iFrame API documentation.
Also fix description regarding to real usage
Note: This is a draft PR, please give me feedbacks and I will fix it.
See FIXME in the PR please
=> doc: add default values in iFrame api doc

packages/core-utils/src/renderer/html.ts, packages/tests/src/client/og-twitter-tags.ts
HTML attributes used for rendering embeds break if they contain double quote characters. The commit edc6952 attempts to address this issue using backslash escapes. However, this does not work because inserting backslash characters does not actually escape the problematic double quote character from the HTML value.
The current, resultant behavior is that the truncated description gets cut short early after the first backslash character, terminating where the double quote character would be.
The expected behavior is for the truncated description to render with the embed in its entirety.
This would require for double quote characters to be replaced with the  `&quot;` HTML entity instead of being backslash-escaped, which is what this PR does.
https://github.com/Chocobozzz/PeerTube/issues/6205 …
=> Fix the escapeAttribute function using HTML entities instead of backslash escapes

server/core/middlewares/error.ts, server/core/middlewares/validators/videos/video-view.ts, server/core/types/express.d.ts
Log a warning when a POST request is done to /api/v1/videos/{id}/views with an invalid currentTime.
#6285
=> fix(server/video-view): log invalid currentTime req

support/doc/api/openapi.yaml
The VideoPrivacy value `5` was missing in the documentation: https://docs.joinpeertube.org/api-rest-reference.html#tag/Video/operation/getVideos
No issue created.
=> Missing video privacy value

packages/models/src/plugins/server/server-hook.model.ts, packages/tests/fixtures/peertube-plugin-test/main.js, packages/tests/src/plugins/filter-hooks.ts, server/core/controllers/api/users/me.ts
Adds `filter:api.user.me.get.result` to let plugins modify the response of GET /api/v1/users/me
relates to #6219
=> feat(plugins): add filter:api.user.me.get.result

packages/tests/fixtures/peertube-plugin-test-five/main.js, packages/tests/src/plugins/plugin-router.ts, server/core/types/express.d.ts, server/server.ts, support/doc/plugins/guide.md
Stripe webhooks endpoints requires to read the raw request body.
https://docs.stripe.com/webhooks#verify-webhook-signatures-with-official-libraries
=> feat(plugins): add req.rawBody for routes

packages/tests/fixtures/peertube-plugin-test-four/main.js, server/core/lib/plugins/plugin-helpers-builder.ts, server/core/types/plugins/register-server-option.model.ts
Let plugin authors to load a video with all its files. This can be useful when a plugin want to switch video files based on the users capabilities.
=> feat(plugins): add peertubeHelpers.loadWithFiles

server/core/lib/html/client-html.ts
Tell the clients to not cache the HTML response.
closes #6393
=> feat(server): dont client cache HTML files

config/default.yaml, config/production.yaml.example
In default.yaml and production.yaml.example there is what seems to be a typo at log.rotation.enabled
I'm not sure this typo caused any problem as i couldn't see any config parsing error on my instance but for coherence sake, i though i would still PR that.
=> Fix typo at log.rotation.enabled

client/src/app/core/plugins/plugin.service.ts, client/src/app/core/users/user.model.ts, client/src/standalone/videos/shared/peertube-plugin.ts, client/src/types/register-client-option.model.ts
Let plugins access the user object.
* I wasn't sure how to handle the plugin helpers for the standalone version, so I set it to unimplemented.
* Should getUser return `ServerMyUserModel` instead of `AuthUser`? By doing that the methods in `AuthUser` doesn't need to be a part of the public API.
closes #6355
There's no test suites for the client.
=> feat(client/plugins): add getUser to helpers

support/doc/production.md
The `--sort` argument to ls is a linuxism (more precisely a gnu-coreutilsism). I get this output when attempting these instructions on FreeBSD (13):
$ diff -u "$(ls --sort=t | head -2 | tail -1)/config/production.yaml.example" "$(ls --sort=t | head -1)/config/production.yaml.example"
ls: unrecognized option `--sort=t'
usage: ls [-ABCFGHILPRSTUWZabcdfghiklmnopqrstuvwxy1,] [--color=when] [-D format] [file ...]
ls: unrecognized option `--sort=t'
usage: ls [-ABCFGHILPRSTUWZabcdfghiklmnopqrstuvwxy1,] [--color=when] [-D format] [file ...]
diff: /config/production.yaml.example: No such file or directory
Changing `--sort=t` to the POSIX-compliant `-t` makes this work as expected and operates just fine on Linux (tested on Fedora Linux 39).
Fixes #6412
=> Make instructions work on more platforms

support/doc/api/embeds.md
Fix typo in documentation
getPlaybackRate() : Promise<number> documentation
instead of
getPlaybackRate**s**() : Promise<number> documentation
- [X ] 🙅 no, because this PR does not update server code
=> docs: fix typo in getPlaybackRate() : Promise<number> documentation

config/default.yaml, config/production.yaml.example, server/core/initializers/checker-before-init.ts, server/core/initializers/config.ts, server/core/lib/object-storage/shared/client.ts
Backblaze recommends to have a high amount of attempts since they've designed their architecture so that it will return 5xx errors to indicate that the client should do a new attempt.
https://www.backblaze.com/blog/b2-503-500-server-error/
closes #6415
Only manual test with a local Minio server.
=> feat: config option object_storage.max_request_attempts

server/core/controllers/api/videos/index.ts
Add req param to `filter:api.video.get.result` hook in order to let a plugin read the request headers.
=> feat(plugins/filter): add req to api.video.get.result

server/core/controllers/api/search/search-videos.ts
Add Express request & response to `filter:api.search.videos.local.list.params`'s hook context.
I believe this was needed because the query given to the hook has already been filtered for unwanted parameters before the hook executes, this adds the request & response to allow access to those query parameters that might've been removed.
N/A
I do not believe this change needs tests written for it
=> Add Express req, res to filter:api.search.videos.local.list.params

support/docker/production/config/custom-environment-variables.yaml
Allow to configure `object_storage.max_request_attempts` in Docker environments
Close #6536
=> Add option for configuring object_storage.max_request_attempts in Docker

packages/tests/src/api/check-params/services.ts, server/core/controllers/services.ts
It's handy to be able to access the [oEmbed API](https://oembed.com) from a browser, in order to construct `<iframe>` tags to embed videos. However, web browsers have security policies that prevent cross-domain communication -- unless that security policy is specifically bypassed using a [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) header. In this case, the oEmbed API returns no personal data about the logged-in user, so there is no reason to prevent cross-domain communication.
By adding this header, it allows third-party websites to construct `<iframe>` embeds directly in client-side JavaScript, without needing a backend server to act as a proxy.
=> oEmbed API should use CORS

support/doc/tools.md
This pull request adds the correct Docker syntax for the `prune-storage` script, which was missing in the previous version of the documentation.
No related issues were reported.
N/A
=> Add missing Docker syntax for prune-storage

client/src/app/shared/shared-support-modal/support-modal.component.html
This pull request resolves the issue#6479 where value "Maybe Later" is changed to "Close"
issue#6479
(The page doesn't look asusaul because i haven't downloaded all the dependencies but my changes doesn't affect anyother file changes are only done in support-model.component.html file )
=> change message from maybe later to close

README.md
This PR:
- Fixes the broken 'Test Suite' badge.
- Removes redundant blue underlines between badges by consolidating the `<a>` and `<img>` tags as Markdown elements.
Fixes #6596
N/A
=> Fixed broken test badge; removed redundant underline

support/docker/production/Dockerfile.bookworm
This adds support for specifying the peertube user and group IDs using the standard environment variable pattern similar to linuxserver.io images.  This allows for better external permission management, specifically this makes it easier to support mapping volumes to NFS shares using nfs4 id mapping.
This changes elects *not* to use the linuxserver.io variable names of PUID and PGID since the peertube container ends up having both a "node" and "peertube" user created and it would not be obvious which of those PUID/PGID should apply to.
New variables are `PEERTUBE_UID` and `PEERTUBE_GID` respectively.
[Existing feature request that was closed due to inactivity
](https://github.com/Chocobozzz/PeerTube/issues/2424)
=> Add the ability to specify peertube UID and GID via environment variables

packages/tests/src/plugins/action-hooks.ts, server/core/controllers/api/users/me.ts
Call `action:api.user.deleted` upon `DELETE /me`.
closes #6859
=> fix(plugins/hooks): call user delete upon delete me

packages/server-commands/src/users/users-command.ts, packages/tests/src/api/check-params/my-user.ts, packages/tests/src/api/check-params/registrations.ts, packages/tests/src/api/check-params/users-admin.ts, packages/tests/src/api/check-params/users-emails.ts, packages/tests/src/api/server/email.ts, packages/tests/src/api/users/oauth.ts, packages/tests/src/shared/sql-command.ts, server/core/lib/auth/oauth-model.ts, server/core/lib/auth/oauth.ts, server/core/lib/user.ts, server/core/middlewares/validators/shared/users.ts, server/core/middlewares/validators/users/shared/user-registrations.ts, server/core/middlewares/validators/users/user-email-verification.ts, server/core/middlewares/validators/users/user-registrations.ts, server/core/middlewares/validators/users/users.ts, server/core/models/user/user-registration.ts, server/core/models/user/user.ts
In order to not force users to be case sensitive when asking for password reset or resend email verification. When there's multiple emails where the only difference in the local is the capitalized letters, in those cases the users has to be case sensitive.
closes #6570
=> feat(API): permissive email check in login, reset & verification

server/core/lib/html/shared/video-html.ts
Currently Google Search Console reports issue with `Value for property duration must be positive` for permanent lives where the duration value is `PT0S`. This PR will hide the duration property when the duration is falsy.
=> server: hide meta duration when duration is 0

client/src/app/header/header.component.scss
Hitbox of logo + title `<a>` link is too large
This is how it is currently:
This fix changes it to so:
=> Fix header hit box

support/docker/production/config/custom-environment-variables.yaml
This pull request adds all live options as docker env vars.
I have manually tested some options (live.rtmp.*)
=> add missing docker env options to configure live settings

package.json, packages/models/src/plugins/server/server-hook.model.ts, packages/tests/fixtures/peertube-plugin-test/emails/password-reset.pug, packages/tests/fixtures/peertube-plugin-test/main.js, packages/tests/src/plugins/filter-hooks.ts, server/core/lib/emailer.ts, yarn.lock
Add `filter:email.template-path.result` / `filter:email.subject.result` in order to get plugins ability to customize emails sent from Peertube.
closes #3392
=> add filter:email.template-path.result / filter:email.subject.result

support/docker/production/docker-compose.yml
This commit adds the folder /var/log/ngnix of the webserver container to the volume mount.
This commit adds the folder /var/log/ngnix of the webserver container to the volume mount. The motivation to add this change is to make it easier for the users to extract logs when asked.
=> feat (docker): Expose NGINX logs folder.

support/conf.d/peertube, support/doc/production.md, support/init.d/peertube
This change uses openrc-run instead of a simple shell script which allows to mainly use a declarative configuration, manages dependencies, pid file, privileges drop and more. It also uses supervise-daemon as supervisor so that the service can be restarted when crashing.
The production guide now also contains instructions when updating on an OpenRC system.
#4678 (This PR doesn't use start-stop-daemon but supervise-daemon that brings actual supervision)
=> Modernize the OpenRC service with openrc-run and improve production guide

support/docker/production/config/production.yaml
=> Fix typo in production.yaml

apps/peertube-runner/src/shared/logger.ts
Use pino-prettyprint ability to detect if the TTY supports colors to choose when coloring logs.
Issue discussed directly with @Chocobozzz: if using rsyslog to store prunner logs, the logs are polluted with color escape sequences. This PR allows to avoid that, but keep colors when executing the runner from the command line.
=> 🔊 — [peertube-runner] Disable log coloring when TTY does not support it

client/src/app/+videos-publish-manage/shared-manage/common/video-manage-page-common.scss, client/src/app/+videos-publish-manage/shared-manage/replace-file/video-replace-file.component.html, client/src/app/+videos-publish-manage/shared-manage/replace-file/video-replace-file.component.scss, client/src/app/+videos-publish-manage/shared-manage/replace-file/video-replace-file.component.ts
Added the drag and drop functionality (that was already used for publishing videos) for replacing the video files
Now there is the possibility to drag a file from the file exporer to the "Replace file" area to replace a video (add a new version of the video), as well as upload that file using the button.
Solves issue "Add hint for drag and drop for replace video #6094".
Note: When dragging the file over other elements in the drop area, the DnD hint flickers, and if you happen to drop the file in between the flickers (when the hint does not appear), the file will not be selected. As far as I looked into that, that has to do with hovering over nested components within the drop area which messes with the onEnter and onLeave methods of the Drag and Drop directive. The exact same thing happens …
=> Add Drag-and-Drop to Replace File

client/src/app/shared/shared-custom-markup/custom-markup.service.ts, client/src/app/shared/shared-custom-markup/peertube-custom-tags/embed-markup.component.ts, packages/models/src/custom-markup/custom-markup-data.model.ts
Currently, all videos embedded on a page using the `<peertube-video-embed>` tag have hard-coded dimensions. 
Therefore this PR adds the `data-responsive` tag to `<peertube-video-embed>` together with a bunch of other tags (see overview below)
`<peertube-video-embed>`:
`data-start-at`, `data-subtitle`, `data-responsive`, `data-stop-at`, `data-autoplay`, `data-muted`, `data-loop`, `data-title`, `data-p2p`, `data-warning-title`, `data-control-bar`, `data-peertube-link`
`<peertube-playlist-embed>`:
`data-responsive`,  `data-playlist-position`
#6834 
embed with and without the data-responsive attribute
=> Add embed paramaters

client/src/sass/include/_miniature.scss
Use SVG filter for thumbnail blurs and fix thumbnail corner coloring
The values for the SVG filter were derived from the current `filter: blur(20px);` property. I took the video height from the video miniatures on channel pages and rounded up to 160.
`0.125` comes from `20 ÷ 160`, and `0.07` comes from `20 ÷ ( 160 ÷ 9 × 16)`.
Chocobozzz/PeerTube#7104
=> Use SVG filter for thumbnail blurs and fix thumbnail corner coloring

client/src/root-helpers/video.ts, packages/tests/src/api/server/services.ts, server/core/controllers/services.ts
Based on https://github.com/Chocobozzz/PeerTube/pull/4606
[allowFullScreen](https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement/allowFullscreen) property is considered legacy and use of allow='fullscreen' is recommended.
[caniuse](https://caniuse.com/mdn-html_elements_iframe_allow)
[HTMLIFrameElement.frameBorder](https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement) is deprecated and use of border in CSS is recommended.
fixes #7042
=> update allowfullscreen property
